### ISSUE TITLE
Add to README Section on Why use Flask-Migrate vs just Alembic

### ISSUE THREAD

**Issue by cancan101** [miguelgrinberg/Flask-Migrate#101]
As a potential new user of Flask-Migrate, I looked for a section in the README as to why use Flask-Migrate instead of just using the CLI that comes with alembic.

**Comment by miguelgrinberg** [comment]
Okay, fair point. The reason is that Flask-Migrate gives you a zero configuration set up when using Flask-SQLAlchemy, Flask-Script and Alembic. You can use Alembic alone, but you'll have to do some configuration work, as Alembic knows nothing about Flask or Flask-SQLAlchemy.

**Comment by Guttz** [comment]
What about a flask application but with sqlalchemy and not flask_sqlalchemy? Does it work/requires zero configuration?

**Comment by miguelgrinberg** [comment]
This package works with Flask-SQLAlchemy. If you are using plain SQLAlchemy you can't use it.
