### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by jaapz** [miguelgrinberg/Flask-Migrate#102]
It would be nice to have a changelog, as now it is not very clear what's changing in each version and we have to look at and interpret terse commit messages to see what actually changed in a new version.

**Comment by miguelgrinberg** [comment]
Agreed. I wish maintaining a change log was easier, but yes, I have to figure out how to do it, not only for this but my other projects as well.

**Comment by jaapz** [comment]
I suggest to follow a convention like [this one](http://keepachangelog.com/), and require pull-requests to add an entry to the changelog file. This way you have a default set of rules you can fall back on and the people proposing the changes also change the changelog, unburdening you a bit.

**Comment by miguelgrinberg** [comment]
Okay, change log for this project is done. Now on to other projects...

**Comment by jaapz** [comment]
Thanks!
