### ISSUE TITLE
Datetime in filename migration

### ISSUE THREAD

**Issue by bekerov** [miguelgrinberg/Flask-Migrate#104]
I cant figure out which migration is next. 
![image](https://cloud.githubusercontent.com/assets/2405629/14089818/a479e9d6-f53f-11e5-882f-9f745b7da518.png)

Can you say chains of the migrations ? i'm not. i need `python manage.py db history` and match each file. Also i cant figure out if other developer added table with migration in other branch, and also i added new table. How resolve this conflict ?

**Comment by miguelgrinberg** [comment]
I have no control over this, this is done by Alembic, which is the migration engine for SQLAlchemy. But in any case, the output from `manage.py db history` should give you the order, and any branches that exist.

You can also implement a pre-commit check on your source control that prevents someone to commit a migration history with conflicts.

**Comment by deeTEEcee** [comment]
@bekerov in alembic.ini, `file_template = %%(year)d_%%(month).2d%%(day).2d%%(hour).2d%%(minute).2d%%(second).2d_%%(rev)s_%%(slug)s`.
