### ISSUE TITLE
Using Flask migrate via console scripts

### ISSUE THREAD

**Issue by amitsaha** [miguelgrinberg/Flask-Migrate#107]
First of all, thanks for this package. In my app, I am trying to define a entry point:

```
app-db-upgrade=app:upgrade
```
And in `app.py`, I have:

```
def upgrade_db():
     upgrade()
```

However, I get a: ```RuntimeError: working outside of application context```. I understand why it is happening. So I am wondering if this is the way to go about this and If I am doing something wrong?

Or, is there a better way?

**Comment by miguelgrinberg** [comment]
It's okay to do this, you just need to create an app and app context:

    def upgrade_db():
        with app.app_context():
            upgrade()

**Comment by amitsaha** [comment]
Thank you. I did try it before, but something else was wrong on my part. That works.
