### ISSUE TITLE
Alembic seems no reference to models.py when migration

### ISSUE THREAD

**Issue by wonderchang** [miguelgrinberg/Flask-Migrate#109]
The default `env.py` is generated as below,

`target_metadata = current_app.extensions['migrate'].db.metadata`

But it seems no reference to `app/models.py`. I modify the `target_metadata` manually by assigning `db` directly,

```
from app import db
target_metadata = db.metadata
```

then, it works.

Although this solution is workaround, I feel it is not the right way. What does `current_app.extensions['migrate']` stored? Do I miss some configurations? I wonder whether I am missing something or not. 

My `manage.py` is as below,
```
#!/usr/bin/env python
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.script import Manager
from flask.ext.migrate import Migrate, MigrateCommand
from config import SQLALCHEMY_DATABASE_URI
from app import app

app.config['SQLALCHEMY_DATABASE_URI'] = SQLALCHEMY_DATABASE_URI

db = SQLAlchemy(app)
migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```

**Comment by miguelgrinberg** [comment]
Importing the models is normally something that occurs as part of the app creation, so in manage.py, when you create an app, you have already the models imported, and you should not need to import them again. Importing the models during app creation is actually necessary for the application as well, as that ensures that all models are register with SQLAlchemy when the app starts.

The `current_app.extensions['migrate']` object contains a reference to `db`. This is populated when you create the `Migrate()` instance, or when you call `Migrate.init_app(app, db)` on it.

**Comment by wonderchang** [comment]
Oh, I found that I got silly. I should import the existed db from the app, rather then re-create the one which it can not be referable to the `models.py`. The `manage.py` should be as follow,

```
#!/usr/bin/env python
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.script import Manager
from flask.ext.migrate import Migrate, MigrateCommand
from config import SQLALCHEMY_DATABASE_URI
from app import app, db

app.config['SQLALCHEMY_DATABASE_URI'] = SQLALCHEMY_DATABASE_URI

migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```

Thank anyway.

**Comment by eugenius1** [comment]
I came here via Google, so if is there anyone like me looking to combine multiple model-metadata (app models, `PSABase.metadata`) into one:
http://liuhongjiang.github.io/hexotech/2015/10/14/alembic-support-multiple-model-files/

**Comment by fanhaipeng0403** [comment]
thanks
