### ISSUE TITLE
server_default migrate failed

### ISSUE THREAD

**Issue by woshihaoren** [miguelgrinberg/Flask-Migrate#111]
I defind test table,The table has create_time field,server_default current_timestamp.
```
class test(db.Model):
    __tablename__ = 'test'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255), default='aaa')
    create_time = db.Column(db.DateTime(), server_default=db.func.current_timestamp())
```
When I exec   db migrate and upgrade,It's failed,Because migrate script is worry.
```
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
```
The server_default should is server_default=sa.sql.func.current_timestamp()

**Comment by miguelgrinberg** [comment]
Can you just change it? Automatic migrations are not always accurate, note the comment `please adjust!` in all autogenerated scripts.

**Comment by woshihaoren** [comment]
Yeah It's OK
Thanks , I just want to know this problem

**Comment by miguelgrinberg** [comment]
You should as in the Alembic project, which is the engine that actually generates the migrations. This project is just an Alembic wrapper for Flask.
