### ISSUE TITLE
why flask-migrate can't create table without "import models" in the __init__.py

### ISSUE THREAD

**Issue by viperstars** [miguelgrinberg/Flask-Migrate#113]
Hi, miguelgrinberg

my problem is same as https://github.com/miguelgrinberg/Flask-Migrate/issues/50

When I add "import models" in the app/__init__.py  it will work fine. But without "import models",  it can't create any tables defined in app/models.py.

According to you example project https://github.com/miguelgrinberg/flasky, there seems not any "import models" in the app/___init__.py.

I don't know what causes difference. Would you like to answer it ?

**Comment by miguelgrinberg** [comment]
Sometimes you can get away without importing the models explicitly. But in the cases in which everything works without doing that, the models are indirectly imported by other modules. SQLAlchemy and Alembic require all the models to be imported, if the models aren't imported then they are not seen by these tools.

**Comment by viperstars** [comment]
Thanks for you help. I finally know about this: if the models in models.py are not imported in other modules, we should do it explicitly.
