### ISSUE TITLE
Do you have any plans to integrate with Click?

### ISSUE THREAD

**Issue by c-bata** [miguelgrinberg/Flask-Migrate#114]
This is very useful library for me. But, as you know flask supports click-based interface from v0.11.
Do you have any plans to integrate with click-based interface?

http://flask.pocoo.org/docs/0.11/cli/

**Comment by miguelgrinberg** [comment]
Need to think about how to add click support without breaking users who decide to stay with 0.10.x.

**Comment by c-bata** [comment]
👍  thank you!!

**Comment by prokaktus** [comment]
@miguelgrinberg thanks a lot, looks awesome! But I cannot find any notice about `click` integration in docs... Should it be there?

**Comment by miguelgrinberg** [comment]
@prokaktus Really? All the examples use `flask db ...` instead of `manage.py db ...`. That's the click integration.

**Comment by prokaktus** [comment]
@miguelgrinberg ah, ok. It was not obvious for me from example https://github.com/miguelgrinberg/Flask-Migrate#example, that `click` support was already integrated. `cmd+f` for docs didn't help also :) But if this obvious for most people, then cool! Thanks for quick reply!
