### ISSUE TITLE
flask-migrate not detecting 'compare_server_default' in env.py

### ISSUE THREAD

**Issue by kilgorejd** [miguelgrinberg/Flask-Migrate#116]
When setting up a new database, my initial migration script does not contain the defaults i put in the model.  For example, if in my model.py I have:
`class Devices(db.Model):`
`    id = db.Column(db.Integer, primary_key=True, autoincrement=True)`
`    name = db.Column(db.String(255), unique=True, nullable=False)`
`    enabled = db.Column(db.Boolean, nullable=False, default=1)`

And in my migrations/env.py I change the run_migrations_online(): to have:
`context.configure(connection=connection, target_metadata=target_metadata, `
`    process_revision_directives=process_revision_directives,`
`    compare_server_default=True,`
`    **current_app.extensions['migrate'].configure_args)`

My resulting migrations/versions/foo.py doesn't have any defaults. What am I doing wrong?

**Comment by miguelgrinberg** [comment]
You are using `default` in your models, not `server_default`. The `default` is not set at the database level, only SQLAlchemy knows about it.

**Comment by kilgorejd** [comment]
Ah, ok, thanks! So just change `default=1` to `server_default='1'` and we should be fine, correct?

**Comment by miguelgrinberg** [comment]
I think so. I have never done this myself though. But if you find any problems, not that it is Alembic doing all the work, Flask-Migrate is just a Flask friendly wrapper for it.

**Comment by kilgorejd** [comment]
Super, that did work!  Cheers!
