### ISSUE TITLE
no such template flask from alembic

### ISSUE THREAD

**Issue by johnpa** [miguelgrinberg/Flask-Migrate#120]
Hi.

I am getting no such template error thrown from alembic when I issue "db init -d `pwd`/migrations" command. Am I missing any dependency? or is my funky environment (of not using pip and messing around with pkgdir) any assumptions built into the code?

Currently, I am using following dependencies (not installed through pip due to restrictions. let me know if any dependencies are missing) 
flask-migrate 1.8.0
flask-script 2.0.3
alembic 0.8.6
flask 0.10

Traceback (most recent call last):
  File "./manage.py", line 28, in <module>
    manager.run()
  File "build/bdist/egg/flask_script/__init__.py", line 412, in run
  File "build/bdist/egg/flask_script/__init__.py", line 383, in handle
  File "build/bdist/egg/flask_script/commands.py", line 215, in __call__
  File "build/bdist/egg/flask_migrate/__init__.py", line 98, in init
  File "build/bdist/egg/alembic/command.py", line 34, in init
alembic.util.exc.CommandError: No such template 'flask'

manage.py script 
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand

app = create_app(conn) 
db = setup_database()  # SQLAlchemy(app) from other file
    migrate = Migrate(app, db)
    manager = Manager(app)
    manager.add_command("db", MigrateCommand)
if __name__ == "__main__":
    manager.run()

**Comment by miguelgrinberg** [comment]
there are a bunch of files that Flask-Migrate needs in addition to the Python code. Did you install those as well? The error suggests you did not.

**Comment by johnpa** [comment]
Hmm. Are those neglected when building egg file using "python setup.py bdist_egg"?

**Comment by miguelgrinberg** [comment]
I just built an egg here and it did get those files, so the build is not the problem. Can you please check if the `templates` directory got installed in your system?

**Comment by johnpa** [comment]
I am not sure what you mean by installed in your system. Our runtime takes eggs directly (each packages packed individually so alembic and flask-migrate sits in different file) upon referencing the code. Do you depend on the template files to be installed on specific path?

**Comment by miguelgrinberg** [comment]
@johnpa The files cannot be inside the egg if that is what you are asking. The code looks for these files in the file system, so you need to do a source install.

**Comment by johnpa** [comment]
right. I tried taking it out of egg and it works like a charm. Thanks!

**Comment by reganbu** [comment]
Sorry to re-open something that's been closed for 2 years. I'm new to web dev, and I'm having this same template error when I run `flask db init`, however, I have verified that I have indeed installed the `templates` directory in my system, but I'm still getting this error. Do you have any suggestions on how I could fix this? Should the directory be in a specific place within the file system other than the `flask_migrate` folder? Thanks for your help

**Comment by miguelgrinberg** [comment]
@reganbu Are you using a standard virtual environment and pip or some other method of installation?
