### ISSUE TITLE
ImportError: No module named alembic

### ISSUE THREAD

**Issue by Mon0ncle** [miguelgrinberg/Flask-Migrate#124]
Hey,
I recently installed Flask-Migrate and Flask-Script. When I try to run the app I get the following exception:
`Traceback (most recent call last):
  File "E:\Developing\bischoffmusik\runserver.py", line 1, in <module>
    from bischoffmusik import manager
  File "E:\Developing\bischoffmusik\bischoffmusik\__init__.py", line 3, in <module>
    from flask_migrate import Migrate, MigrateCommand
  File "E:\Developing\bischoffmusik\lib\site-packages\flask_migrate\__init__.py", line 5, in <module>
    from alembic import __version__ as __alembic_version__
ImportError: No module named alembic`

These are the installed packages (the relevant ones):
`alembic (0.8.7)
Flask (0.11.1)
Flask-Alembic (2.0.0)
Flask-Migrate (2.0.0)
Flask-Script (2.0.5)
Flask-SQLAlchemy (2.1)
Flask-WhooshAlchemy (0.56)
Flask-WTF (0.12)
SQLAlchemy (1.0.14)
sqlalchemy-migrate (0.10.0)
`

**Comment by miguelgrinberg** [comment]
how did you create your virtual environment and then installed all these packages? The structure that is shown in the error message looks odd.

**Comment by Mon0ncle** [comment]
![structure](https://cloud.githubusercontent.com/assets/15527639/17459336/4d29df8c-5c33-11e6-9a07-21f727ba2099.png)

I attached a picture. I let PyCharm generating the virtualenv for me and then I simply used pip to install the packages (while the virtualenv was active..).

**Comment by miguelgrinberg** [comment]
Yeah, it looks like you have your application mixed up with the virtualenv. That seems strange, and clearly suggests either the library path or some other setting prevents the application from finding alembic.

My recommendation is that you build a new virtualenv from scratch and load all the dependecies again. Try building a virtualenv from the command line, and let me know if that fails for you.

**Comment by Mon0ncle** [comment]
I made a fresh install via cli and it worked. It basicly moved the venv files into a seperate folder in the project directory.

Thanks for your advice!
