### ISSUE TITLE
Support flask 0.11

### ISSUE THREAD

**Issue by JiefeiC** [miguelgrinberg/Flask-Migrate#127]
Flask 0.11 has new dependency with Click instead of flask_script.
They have fairly similar api, it will be easy to migrate to Click.

**Comment by JiefeiC** [comment]
And by the way, your flasky and the book may need some update, too.

**Comment by miguelgrinberg** [comment]
The work to support the new Flask CLI was already done. But I forgot to update the change log with the new release that has this work. It's updated now.
