### ISSUE TITLE
cli: default name of flask.commands entry point

### ISSUE THREAD

**Issue by jirikuncar** [miguelgrinberg/Flask-Migrate#132]
I would like to start using Flask-Migrate but unfortunately the default command name `db` conflicts with our generic database scripts. Is it possible to change the default name to `migrate` or `alembic`? Btw previously it was possible to register the Flask-Script command under custom name.

**Comment by miguelgrinberg** [comment]
Unfortunately the name has been `db` for a very long time, changing it would mean lots of people will have to make changes to their own scripts.

You can probably install the Flask-Migrate cli handler under a different name as part of your own application, have you tried that?

**Comment by jirikuncar** [comment]
The problem is in https://github.com/miguelgrinberg/Flask-Migrate/commit/8c208b54837ccbf65eee8d95fc623057e2753b4e since it's part of entry points.

a) remove `db` from `flask.commands`
b) rename `db` to `migrate` to keep cli name same as extension name.

Otherwise it's impossible to use this project in sensible manner.

**Comment by jirikuncar** [comment]
Before one was able to register command under it's own name:

```python
manager = Manager(app)
manager.add_command('db', MigrateCommand)
```
If you want to keep compatibility then don't use `flask.commands` entry point but move the registration to [`init_app`](https://github.com/miguelgrinberg/Flask-Migrate/blob/master/flask_migrate/__init__.py#L43) with following snippet:

```python
def init_app(self, app):
    # ...
    if hasattr(app, 'cli'):
        name = app.config.get('MIGRATE_CLI_NAME', 'db')
        if name:
            app.cli.add_command(name, db)
    # ...
```

**Comment by miguelgrinberg** [comment]
Here is an example of how you can override commands installed by flask or extensions: https://github.com/pallets/flask/issues/2020#issuecomment-252455025

**Comment by jirikuncar** [comment]
@miguelgrinberg sure we have our own `FlaskGroup`, but I still think that Flask-Migrate should not add entry point called `db` since it's not its "namespace". It might be easier to keep a fork which changes only the entry point name rather than filtering one that doesn't follow naming conventions.

**Comment by jirikuncar** [comment]
Anyway, it looks like Flask-Alembic has the command name [configurable](https://bitbucket.org/davidism/flask-alembic/src/0a37cb7c356355b80ca614e2402dd2c8047948c8/flask_alembic/extension.py?at=default&fileviewer=file-view-default#extension.py-85) so for now it looks like a winner. Thanks anyway for your time!
