### ISSUE TITLE
Unable to detect models in folder

### ISSUE THREAD

**Issue by vabs** [miguelgrinberg/Flask-Migrate#140]
Hi,

Please find the repo here: https://github.com/vabs/flask-template

I am trying to create migrations from the folder models in my app. But when running the command `python manager.py db migrate`, the code is unable to detect any models. It is generating empty revision files.

Help is appreciated.

**Comment by miguelgrinberg** [comment]
You are not importing your models, so SQLAlchemy does not see them.

**Comment by vabs** [comment]
in `manager.py` I am imported models module. Still empty revisions.

**Comment by miguelgrinberg** [comment]
appname.models is not a proper Python package, it does not have an `__init__.py` file. Try to reference your model(s) after you import them to ensure they are accessible. I believe they are not right now.

**Comment by vabs** [comment]
I have been stuck in this problem for quite some time. I think my understanding is lacking. 
I made `models` as a valid python package.

Still no luck. Am I missing some configuration?

**Comment by miguelgrinberg** [comment]
Well, yes. You put an empty `__init__.py` file, and that's what you are importing. The models are still not being imported. Either import them explicitly from `manage.py` or import them in the `__init__.py` file so that they are imported by default when the package is imported.

**Comment by vabs** [comment]
Is that what you meant by explicit importing? `from appname.models.points import Points`

sqlalchemy doesn't detect them even doing that.

**Comment by miguelgrinberg** [comment]
And you have two `db` objects in your application. You are giving one to Flask-Migrate, and use the other to create your models.

**Comment by vabs** [comment]
Thanks miguel for helping me out. Now I can generate proper revision files.
The last question I have is, I have to specify each file which I add in models folder explicitly. Is there a way in which sqlalchemy can detect the all. 
Tried doing `from appname.models import *`, it didn't worked.

Again thank you for quick replies and your contribution for making flask an amazing framework.

**Comment by miguelgrinberg** [comment]
The Python documentation covers how to do this: https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

**Comment by vabs** [comment]
Thank you. Closing the issue.
