### ISSUE TITLE
Is it better to use flask-script or the flask to deal with migration?

### ISSUE THREAD

**Issue by rlam3** [miguelgrinberg/Flask-Migrate#141]
@miguelgrinberg  Is it better to use flask-script or the flask to deal with migration?

**Comment by miguelgrinberg** [comment]
In terms of this extension, both cli options achieve the same goal. If you are starting a new project, you should use the `flask` command, since that is the official way of writing cli tools. If you have an old project that used Flask-Script, then keep using it, until and if you decide to migrate away from it.

**Comment by fgblomqvist** [comment]
I was wondering the same thing. Maybe you should add this to the readme? Currently, it only shows an example utilizing Flask-Script, which I found out is really old and replaced by the Flask CLI (aka the `flask` command).

**Comment by miguelgrinberg** [comment]
Actually, the documentation has been updated to use the CLI long ago. What I apparently forgot is to update the README file in the same way.

**Comment by fgblomqvist** [comment]
Oh okay cool, easy fix then 😎

**Comment by abigperson** [comment]
thanks for the clarification... had the same question regarding this dependency (e.g. if you do `pip install Flask-Migrate` it will pull **Flask-Script** as a dependency. Can I remove this from a new project if I am using the flask cli? _(looks like you've got some try/except logic which deals with this)_

**Comment by miguelgrinberg** [comment]
@abigperson I inadvertently left the Flask-Script dependency enabled and was alerted of this fact just yesterday. The latest release of Flask-Migrate as of yesterday does not install Flask-Script anymore. You can uninstall it from your project if you don't use it.

**Comment by miguelgrinberg** [comment]
Looks like I also forgot to update the README.md as a result of this issue. I just did that, so I'm closing it.
