### ISSUE TITLE
Can't downgrade

### ISSUE THREAD

**Issue by ColdHeat** [miguelgrinberg/Flask-Migrate#147]
For some reason in my application I can't downgrade and I get the following error:

```
alembic.util.exc.CommandError: Relative revision -1 didn't produce 1 migrations
```

I've also noticed that when my database is first created from sqlalchemy it doesn't seem like the alembic version table is created when migrate.init_app is called? Perhaps I'm calling Migrate incorrectly?

**Comment by miguelgrinberg** [comment]
The `Migrate.init_app` call does not actually do anything with the database. The version table is created when you do the first `upgrade`.

The error that you are getting is odd, I don't think I've ever seen that myself. Does the `history` command work for you? My first guess is that your migration chain is broken.

**Comment by ColdHeat** [comment]
I played around with it and I believe the issue is related to not having an alembic_version table since the database is automatically created by sqlalchemy. 

I added the table and the right Revision ID and was able to upgrade/downgrade (disregarding some fixes to my migrations).

Now I suppose the question is how do I create the version table from within the application?

**Comment by miguelgrinberg** [comment]
As I said above, when you use the `upgrade` command the table is created if it doesn't exist already. How are you running your upgrades?

**Comment by ColdHeat** [comment]
Now that I've fixed up the table `history` does work btw. 

This application didn't previously have any upgrades so I'm adding it in and trying to not break any user's databases in the process. Right now I run upgrades with `python manage.py db upgrade`.

**Comment by ColdHeat** [comment]
`python manage.py db history`
```
cb3cfcc47e2f -> 87733981ca0e (head), Adds challenge types and uses keys table
<base> -> cb3cfcc47e2f, Base 1.0.0 CTFd database
```

But yet I cannot run either upgrade or downgrade for the following reasons:

downgrade: `alembic.util.exc.CommandError: Relative revision -1 didn't produce 1 migrations`
upgrade: `sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1050, u"Table 'challenges' already exists") [SQL: u'\nCREATE TABLE challenges (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(80), \n\tdescription TEXT, \n\tvalue INTEGER, \n\tcategory VARCHAR(80), \n\tflags TEXT, \n\thidden BOOL, \n\tPRIMARY KEY (id), \n\tCHECK (hidden IN (0, 1))\n)\n\n']`

The upgrade shouldn't work as the head is wrong but the downgrade should work?

**Comment by miguelgrinberg** [comment]
Sorry, but I don't follow what you are saying. You just say that you are starting to use migrations now, so why do you expect downgrades to work? If you haven't applied any migrations yet, then it is expected that the database will not have any alembic data in it.

First of all, make a backup of your data. You do not want to make a mistake and lose all your data, so stop everything until you have your data backed up.

The process to start migrations on an existing database is not really different than doing it on a new database. You just need to generate a new migration file (your first), and if that looks all right to you, then use the `upgrade` command to apply it. That's all there is to it.

**Comment by ColdHeat** [comment]
This is a development database, it doesn't exist after I shut off the database, there's no need for me to specifically backup anything. 

I have a migration file already created but applying an upgrade complains that the table exists. 

How should a user who needs to upgrade to a new release which requires some migrations proceed after they run `git pull` considering in this scenario they wouldn't have an `alembic_version` table?

**Comment by miguelgrinberg** [comment]
> I have a migration file already created but applying an upgrade complains that the table exists.

If you migration scripts create table X, and table X already exists in the database, then the upgrade will fail.

If your first migration script migrates the database from an empty state, then for that to work, your database must be empty when you apply the migration. There is actually no magic in this. If this script wants to create table X, X must not already be in the database. There are no provisions to skip existing stuff, the script is executed literally step by step.

**Comment by deckar01** [comment]
I was able to initialize the version table by running `python manage.py db stamp head`.
