### ISSUE TITLE
New Alembic 0.9.2 release: UserWarning: 'connection' error

### ISSUE THREAD

**Issue by dmsimard** [miguelgrinberg/Flask-Migrate#156]
Hi,

Reference:
- http://alembic.zzzcomputing.com/en/latest/changelog.html#change-0.9.2-misc
- https://bitbucket.org/zzzeek/alembic/issues/419

There is now some warnings printed when running migrations, for example:
```
/tmp/venv/local/lib/python2.7/site-packages/alembic/util/messaging.py:69: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got Engine(sqlite:////home/jenkins/database.sqlite)
```

I'm not entirely sure what's the fix yet, need to look but wanted to report it quickly.

**Comment by miguelgrinberg** [comment]
I'll look into it, thanks.

**Comment by miguelgrinberg** [comment]
@dmsimard have you, by any chance, modified the `env.py` script generated by Flask-Migrate in the `migrations` directory? I do not get this warning myself, and if you look at the generated env.py script, it does pass a connection instance, not an engine. Can you show me your env.py file?

**Comment by dmsimard** [comment]
@miguelgrinberg This is for the project I have encountered the issue with: https://github.com/openstack/ara/blob/master/ara/db/env.py

**Comment by miguelgrinberg** [comment]
That's odd, because the script in that project also looks correct. Do you have the complete stack trace for the error?

**Comment by dmsimard** [comment]
I don't have a stack trace, really just a warning which I provided in the initial issue report.
Perhaps there's something I'm not doing right around the initialization of the database connection/engine, I need to look but I might not have the time today.

What I do know is that the warning started appearing once 0.9.2 started rolling out to continuous integration jobs. I'll let you know if I figure it out.

**Comment by miguelgrinberg** [comment]
@dmsimard what I did to confirm that this wasn't an issue is add a print statement right before the `configure()` call in `env.py`:

```python
    connection = engine.connect()
    print(type(connection))
    context.configure(connection=connection,
                      target_metadata=target_metadata,
                      process_revision_directives=process_revision_directives,
                      **current_app.extensions['migrate'].configure_args)
```

That shows up as a `Connection` instance for me, and I'm also using sqlite, like you when you obtained that warning.

Can you point me to the build that shows this? I've worked on OpenStack before, btw, so fully familiar with gerrit and the gating process.

**Comment by dmsimard** [comment]
This is what it looks like: http://logs.openstack.org/51/466351/1/check/gate-ara-integration-latest-centos-7/b355f85/console.html#_2017-05-19_16_47_03_965311

ARA happens to be used in different OpenStack projects so a used pointed out the new warning to me.

If the issue is on my end, it's perhaps around these bits where I initialize the db but I would need to experiment: https://github.com/openstack/ara/blob/master/ara/webapp.py#L90-L128

**Comment by miguelgrinberg** [comment]
@dmsimard yeah, I believe the problem is in your code, specifically this line: https://github.com/openstack/ara/blob/master/ara/webapp.py#L118.

See how I call configure in env.py, I think you need to do something similar.

**Comment by dmsimard** [comment]
Looks like this fixes it: https://review.openstack.org/#/c/466482/1/ara/webapp.py

Sorry for bothering you and thanks a lot for your help !
