### ISSUE TITLE
can't capture stdout from 'python app.py db migrate'?

### ISSUE THREAD

**Issue by horizon365** [miguelgrinberg/Flask-Migrate#157]
In [47]: from subprocess import Popen, check_output

In [48]: s =check_output('python add.py db upgrade',shell=True)
In [49]: s
Out[49]: ''

In [55]: s = Popen(['python','add.py','db','init'],stdout=subprocess.PIPE)
In [56]: s.communicate()
Out[56]: ('', None)

i want capture stdout message like this :+1: 

INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.

**Comment by miguelgrinberg** [comment]
Try the following:

    s =check_output('python add.py db upgrade', stderr=subprocess.STDOUT, shell=True)

**Comment by horizon365** [comment]
Thanks a lot!! You save me a lot time!
These INFO is redirection to stderr, get it.
