### ISSUE TITLE
cannot add foreign key constraints

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/Flask-Migrate#162]
The following does not do the intended work
wallet_id = db.Column(db.Integer, db.ForeignKey('wallet.id', use_alter=True, post_update=True), unique=True)
What can I do?

**Comment by miguelgrinberg** [comment]
I don't understand what you mean. What did you expect, and what happens instead?

**Comment by deveshaggrawal19** [comment]
The thing is, I have multiple tables that have foreign keys linked to each other, so I cannot use drop_all method of db. After a little searching on forums the above constraints were told to do the trick, but it's not recognized in the migration and also the following warning popups every time a session is created.
Can't validate argument 'post_update'; can't locate any SQLAlchemy dialect named 'post'.\
Can you enlighten me? Please

**Comment by miguelgrinberg** [comment]
The `post_update=True` option goes in the `db.relationship()` definition, not on the foreign key.

**Comment by deveshaggrawal19** [comment]
and what about use_alter, is it okay?

**Comment by miguelgrinberg** [comment]
I recommend that you consult the SQLAlchemy documentation to learn what you can and cannot do. The `use_alter` is a valid option for ForeignKey. See http://docs.sqlalchemy.org/en/latest/core/constraints.html#sqlalchemy.schema.ForeignKeyConstraint.

**Comment by deveshaggrawal19** [comment]
Thank you very much for the quick response
