### ISSUE TITLE
How to call apis(upgrade, current) in python script

### ISSUE THREAD

**Issue by zhangjiajie023** [miguelgrinberg/Flask-Migrate#163]
I have a database `db`. I want to judge if `flask_migrate` has created tables in `db`. If not, `upgrade db`. 
There are commands, but no examples about calling `migrate, upgrade` in python script. 
The test files in flask_migrate also run commands, such as:
`(o, e, s) = run_cmd('python app.py db migrate')`

**Comment by miguelgrinberg** [comment]
The tests are based on the most common usage, which is people running the commands manually from the shell.

But all commands have an API version, which is documented here: https://flask-migrate.readthedocs.io/en/latest/#api-reference. For an example, see https://github.com/miguelgrinberg/flasky/blob/master/manage.py#L67-L71.

You can also use the Alembic API if you need low level access.

**Comment by dradux** [comment]
If anyone else lands here searching for a way to run migrations on start of your app (e.g. useful for containerized flask apps) here is how I do it:
```
...
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
...
db = SQLAlchemy(app)
migrate = Migrate(app, db)
# apply any/all pending migrations.
with app.app_context():
  from flask_migrate import upgrade as _upgrade
  _upgrade()
```
Take caution to ensure that you handle migrations and corresponding app code in a manner that works with migrations being applied on start of the app (e.g. if you have multiple instances of your app running in a containerized/load balanced manner make sure one updating of one of the containers does not break other containers).

**Comment by snixon** [comment]
If you're curious how to run flask db init/migrate/upgrade from a click command...

```
import click
from flask.cli import with_appcontext
from flask_migrate import init, migrate, upgrade
...
@click.command()
@with_appcontext
def setup_db():
    init_db = init()
    migrate_db = migrate()
    upgrade_db = upgrade()
```

Then you'd call this at the CLI with:

`flask setup_db`

**Comment by HRX46** [comment]
> If anyone else lands here searching for a way to run migrations on start of your app (e.g. useful for containerized flask apps) here is how I do it:
> 
> ```
> ...
> from flask_sqlalchemy import SQLAlchemy
> from flask_migrate import Migrate
> ...
> db = SQLAlchemy(app)
> migrate = Migrate(app, db)
> # apply any/all pending migrations.
> with app.app_context():
     from flask_migrate import migrate as _migrate
>   from flask_migrate import upgrade as _upgrade
     _migrate()
>   _upgrade()
> ```
> 
> Take caution to ensure that you handle migrations and corresponding app code in a manner that works with migrations being applied on start of the app (e.g. if you have multiple instances of your app running in a containerized/load balanced manner make sure one updating of one of the containers does not break other containers).

**Comment by miguelgrinberg** [comment]
@HRX46 FYI, I think your soltuion isn't good, and will not work for a lot of use cases. First of all, the `migrate` command is not a command that you should issue from a script. Migrations should be created manually and inspected to make sure they are correct before they are incorporated into the project. Also, consider an application that starts multiple workers. In that case all the workers would be running migrations, which is not really what you want.

A much better solution is to create a start up script for your container that runs the database upgrade (not the migrate). See the Dockerfile and boot.sh files in [this project](https://github.com/miguelgrinberg/microblog) for a working example.
