### ISSUE TITLE
Feature request: Using Flask CLI instead of Flask-Script dependency

### ISSUE THREAD

**Issue by Mukhametvaleev** [miguelgrinberg/Flask-Migrate#165]
It's a Flask way to implement that functionality without Flask-Script dependency

**Comment by miguelgrinberg** [comment]
You can use the Flask CLI, that's already supported. Use `flask db upgrade`, etc.

**Comment by Mukhametvaleev** [comment]
Yes, i can. But i see that Flask-Script dependency was installed as well.

**Comment by miguelgrinberg** [comment]
Oh, sorry, I see, I forgot to remove the dependency in `setup.py`. I'll fix that, thanks.

**Comment by Mukhametvaleev** [comment]
Thanks, you are the best! :)

**Comment by miguelgrinberg** [comment]
Fixed in release 2.1.0.
