### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [miguelgrinberg/Flask-Migrate#166]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [Flask-Migrate](https://pypi.python.org/pypi/Flask-Migrate), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install Flask-Migrate with just the wheel, without having to do any extra work.

**Comment by miguelgrinberg** [comment]
Yes. I've been meaning to push wheels for all my open source projects, but since none of them really require binary builds I keep postponing it. Thanks for putting it in writing, now I have no choice. ;-)

**Comment by miguelgrinberg** [comment]
I have finally released wheels for all my projects on PyPi.
