### ISSUE TITLE
Generate upgrade command is wrong

### ISSUE THREAD

**Issue by beckjing** [miguelgrinberg/Flask-Migrate#169]
"""heheh

Revision ID: 10d1d4585f92
Revises: c6b2d0ca1b68
Create Date: 2017-08-29 15:44:42.160000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '10d1d4585f92'
down_revision = 'c6b2d0ca1b68'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Bars_bar_name'), 'Bars', ['bar_name'], unique=True)
    op.drop_index('ix_Bars_bar_name', table_name='Bars')
    op.create_index(op.f('ix_Images_image_url'), 'Images', ['image_url'], unique=False)
    op.drop_index('ix_Images_image_url', table_name='Images')
    op.create_index(op.f('ix_Topics_title'), 'Topics', ['title'], unique=False)
    op.drop_index('ix_Topics_title', table_name='Topics')
    op.create_index(op.f('ix_UploadTopics_topic_title'), 'UploadTopics', ['topic_title'], unique=False)
    op.drop_index('ix_UploadTopics_topic_title', table_name='UploadTopics')
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.drop_index('ix_Users_username', table_name='Users')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Users_username', 'Users', ['username'], unique=1)
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.create_index('ix_UploadTopics_topic_title', 'UploadTopics', ['topic_title'], unique=False)
    op.drop_index(op.f('ix_UploadTopics_topic_title'), table_name='UploadTopics')
    op.create_index('ix_Topics_title', 'Topics', ['title'], unique=1)
    op.drop_index(op.f('ix_Topics_title'), table_name='Topics')
    op.create_index('ix_Images_image_url', 'Images', ['image_url'], unique=False)
    op.drop_index(op.f('ix_Images_image_url'), table_name='Images')
    op.create_index('ix_Bars_bar_name', 'Bars', ['bar_name'], unique=1)
    op.drop_index(op.f('ix_Bars_bar_name'), table_name='Bars')
    # ### end Alembic commands ###

when I run 
`python manage.py db migrate -m "heheh"` 
the code was generated as blow.

I guess the order of op.create_index and op.drop_index is reversed.

when I run 
`python manage.py db upgrade`
always tell me wrong

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) index ix_Bars_bar_name already exists [SQL: u'CREATE UNIQUE INDEX "ix_Bars_bar_name" ON "Bars" (bar_name)']

**Comment by miguelgrinberg** [comment]
This is not something this project is doing, Flask-Migrate is just a Flask-friendly wrapper for Alembic. If you are concerned about this type of mistake, you should submit a bug report to the Alembic project on bitbucket.

But as I always say, generated migrations are not supposed to be perfect, they are just a starting point. I would personally edit the migration script to make it right.

**Comment by beckjing** [comment]
Thanks a lot! I will also check the migration script by myself.
