### ISSUE TITLE
Flask-Migrate don't support pymysql

### ISSUE THREAD

**Issue by BetterInTime1997** [miguelgrinberg/Flask-Migrate#172]
I'm working on my project using mysql and flask-SQLAlchemy.
For some reason I have to use mysql as the database of the project,but my python version is 3.6 and can't install Mysqldb which Flask-Migrate needs.
So how can I do the migrations,please give me some advice,thank you,I am a noob : )

**Comment by miguelgrinberg** [comment]
First of all, this has nothing to do with Flask-Migrate, what you are looking for is how to enable SQLalchemy to talk to a MySQL database. See http://docs.sqlalchemy.org/en/latest/dialects/mysql.html for information on your options. There are a bunch of MySQL packages for Python that SQLAlchemy supports. One that is very easy to install and works everywhere is pymysql.

**Comment by BetterInTime1997** [comment]
Thank you very much for your help! : )
