### ISSUE TITLE
upgrade tries to drop native PostGIS tables

### ISSUE THREAD

**Issue by mvexel** [miguelgrinberg/Flask-Migrate#18]
I have a PostGIS enabled PostgreSQL database I want to perform migrations on, but upon `python manage.py db upgrade` I get (last few lines):

```
File "/Users/martijnv/.virtualenvs/mr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 425, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (InternalError) cannot drop table spatial_ref_sys because extension postgis requires it
HINT:  You can drop extension postgis instead.
'\nDROP TABLE spatial_ref_sys' {}
```

Not being familiar with alembic I don't know if this is something I can make go away by manually editing the migration file, or if it's a bug in alembic, or in flask-migrate.

**Comment by renejahn** [comment]
Even if this is closed....is there any way to exclude tables, so alembic won't add them to the migration scripts? I have just added postgis for a project and would be glad if I would not have to fix all migratescripts from now on?

**Comment by miguelgrinberg** [comment]
@renejahn yes, you can use the `include_object` configuration item in env.py: http://alembic.readthedocs.org/en/latest/api/runtime.html?highlight=include_object#alembic.runtime.environment.EnvironmentContext.configure.params.include_object.

**Comment by renejahn** [comment]
@miguelgrinberg Thanks! I will have a look at that.

**Comment by stefaang** [comment]
As the link doesn't work anymore, you may use this
https://gist.github.com/utek/6163250

**Comment by miguelgrinberg** [comment]
The updated location of the `include_object` documentation is: http://alembic.zzzcomputing.com/en/latest/api/runtime.html?highlight=include_object#alembic.runtime.environment.EnvironmentContext.configure.params.include_object

**Comment by nk9** [comment]
Just a note for anyone trying to get this to work: `env.py` has TWO functions which need to be modified to use your modified `include_object`: `run_migrations_online` and `run_migrations_offline`.

See [this gist](https://gist.github.com/utek/6163250) for an example of this solution implemented.

**Comment by abhijithvijayan** [comment]
@nk9 Do I have to replace both the functions. Coz it seems like most of the code changed since the last time the gist was updated.

**Comment by nk9** [comment]
It's not a matter of replacing the functions, but rather adding the appropriate code to ignore the table in both places. As @miguelgrinberg [said above](https://github.com/miguelgrinberg/Flask-Migrate/issues/18#issuecomment-186253477), you need to define an `include_object` function which excludes the table(s) in question and then add it as a `configure` parameter in both places.

**Comment by abhijithvijayan** [comment]
Could you give a snippet for that? I already tried modifying it so many times and now I edit the generated script manually and remove the lines.

**Comment by nk9** [comment]
Well, it's right there in the gist:

```
def include_object(object, name, type_, reflected, compare_to):    
    if type_ == "table" and name == 'spatial_ref_sys':
        return False
    else:
        return True

def run_migrations_offline():
    #[…]
    context.configure(# whatever generated params already exist, then
                      include_object=include_object)
    # […]
```
And the same for the other function.

**Comment by MergenStudios** [comment]
The solutions in this issue work for preserving the spatial_ref_sys table, and by extension any arbitrary set of tables already presnt in the database, but is there a better solution than having to keep a list of every table that is used by e.g. postgis internally and exlucing them all? because that means I have to keep track of every single table postgis needs to function, which is quite the hastle
