### ISSUE TITLE
Add option to fill default column value when adding column which nullable=False

### ISSUE THREAD

**Issue by jxltom** [miguelgrinberg/Flask-Migrate#185]
Currently, it will raise error if user add columns which has ```nullable=False```

**Comment by jxltom** [comment]
Here is the solution temporarily: add ```nullable=False``` and ```default``` when during migration. And remove ```default``` aflter upgrading db.

**Comment by miguelgrinberg** [comment]
That has nothing to do with migrations, it just happens because you are adding the non-nullable column without providing a default value to insert in the existing rows.

**Comment by jxltom** [comment]
Indeed.

But it will be nice to provide a feature which prompt user to input default column value when running ```db upgrade```

**Comment by miguelgrinberg** [comment]
No, this needs to be entered in the migration script. You can expect the user to enter the value every time the migration executes.

**Comment by jxltom** [comment]
Django ORM's built-in migration command has this feature. No matter when to input the default value (in migration or in upgrading), this will save some time in such cases. :)

**Comment by miguelgrinberg** [comment]
First of all, Flask-Migrate is just a Flask friendly wrapper for Alembic. Migrations are done by Alembic, so this is the wrong project to ask for such a feature. Second, SQLAlchemy already supports providing defaults for columns, so I"m not sure what is missing. Just add the default to your migration script and you should be fine, I think.

**Comment by jxltom** [comment]
I have actually added ```default=somevalue``` in table definition. But it looks like it has been ignored by the migration command. In generated migration file, ```default``` attribute is not added...

**Comment by miguelgrinberg** [comment]
I think for this situation you want to use server-side defaults: http://docs.sqlalchemy.org/en/latest/core/defaults.html#server-side-defaults.

I don't recall if Alembic recognizes these defaults and adds them to migrations or not, but if it doesn't, just add it yourself. I see the auto-generated scripts as a starter script, nothing wrong with making changes to them to improve them.

**Comment by jxltom** [comment]
Very usefull information. Thanks. I will think about what is the best way to deal with this situation.
