### ISSUE TITLE
Auto generate rev-id

### ISSUE THREAD

**Issue by italomaia** [miguelgrinberg/Flask-Migrate#186]
One thing that is not very friendly on flask-migrate is that revision id is a hash of sorts. Quite hard to track changes in a series if they're identified by a hash value. What if rev-id could be generated as a increasing number by default or as a option?

**Comment by italomaia** [comment]
Just scripted myself into it.

**Comment by miguelgrinberg** [comment]
Flask-Migrate does not create revision ids, that is done by Alembic, so this needs to be discussed in the context of that project.

The idea of hashes as migration ids is not new though, git does the same thing. And sequential numbers do not work well if you have multiple branches.
