### ISSUE TITLE
Migration directory does not get created

### ISSUE THREAD

**Issue by sowmyg94** [miguelgrinberg/Flask-Migrate#187]
Hi,

I am following your recent Flask tutorial and tried the flask-migrate procedure given there, however when I run the command ' python run.py db init' (in windows) it fails to create the migration directory nor shows any error.

**Comment by miguelgrinberg** [comment]
None of my recent Flask tutorials use the Flask-Script based syntax, so I guess I need to know which tutorial are you following. If you are using the Flask Mega-Tutorial, the command should be `flask db init`, so I suspect you are looking at the old version of the tutorial.

**Comment by sowmyg94** [comment]
Sorry for not being specific, it is the new Flask Mega-Tutorial. I followed the script based syntax as` flask db init ` did not work even after setting FLASK_APP.
