### ISSUE TITLE
PEP8 for auto generated migrations

### ISSUE THREAD

**Issue by WesDowney** [miguelgrinberg/Flask-Migrate#193]
I noticed that the auto generated migrations don't meet the PEP 8 style guide. Would it make sense to update to format meet some or all of PEP 8 so it automatically passes linting?

Here is an example:
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_name',
    sa.Column('id', sa.Integer(), nullable=False),
```

This fails linting for these two rules:

- E128 continuation line under-indented for visual indent
- E122 continuation line missing indentation or outdented

The passing format would be like this:
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_name',
        sa.Column('id', sa.Integer(), nullable=False),
```

If this is something people would like to see added, maybe I'll give it a try to update.

**Comment by miguelgrinberg** [comment]
This project does not generate migrations, that is done by [Alembic](https://bitbucket.org/zzzeek/alembic). This should be a suggestion for that project.

**Comment by WesDowney** [comment]
Thanks! I see there was an[ issue started in 2015 for this](https://bitbucket.org/zzzeek/alembic/issues/307/pep8-format-generated-revisions). I added a comment with my findings there.
