### ISSUE TITLE
additional import in version file

### ISSUE THREAD

**Issue by runout-at** [miguelgrinberg/Flask-Migrate#195]
Hi!
with `flask db migrate` get a version file like this:

```
"""empty message

Revision ID: 7318443bfcc4
Revises: 
Create Date: 2018-04-12 13:21:39.690699

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7318443bfcc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255, collation='utf8mb4_unicode_ci'), server_default=FetchedValue(), nullable=False),
    sa.Column('maildir', sa.String(length=4096, collation='utf8mb4_unicode_ci'), server_default=FetchedValue(), nullable=False),
...
```

With this i get an error on `flask db upgrade` for unknown `FetchedValue`
How can i get an additional import generated? Like this:

```
from sqlalchemy.schema import FetchedValue
```

(The code was reverse engeneered from an existing DB with `flask-sqlacodegen --flask ...`)

**Comment by miguelgrinberg** [comment]
You can edit the migration script after it is generated, and before you run the upgrade, nothing wrong with that.

**Comment by runout-at** [comment]
Thanks! This is already my _workaround_.
I was hoping there would be a more _native_ solution to include additional code for the imports or that flask-migrate should recognize the `FetchedValue`.

```
grep -l -s -L 'from sqlalchemy.schema import FetchedValue' migrations/versions/*.py | \
    xargs sed -i 's/^import\ssqlalchemy\sas\ssa/import sqlalchemy as sa\nfrom sqlalchemy.schema import FetchedValue/'
```

**Comment by miguelgrinberg** [comment]
You can modify the template that is used in the migration if you like. This is in your `migrations` folder, look for the file with name `script.py.mako`.

**Comment by runout-at** [comment]
That looks interesting and it works once `flask db init` has been run and generated the migrations directory with some content.
Sorry if i ask stupid questions but i'm quite new to that stuff.

In `script.py.mako` is a line:
```
${imports if imports else ""}
```
can i pass something to that from my models.py?

**Comment by miguelgrinberg** [comment]
@runout-at I would just leave that line alone and add any explicit imports that you need above or below it.

**Comment by runout-at** [comment]
ok. thanks! I'll do upgrades via a shell script.

**Comment by chedrik** [comment]
@miguelgrinberg Is there any way to pass a different template file to flask-migrate? As @runout-at said above modifying the template file works once the migrations folder has been generated, but it would be awesome to either to be able 1) Not overwrite that template file every time or 2) Be able to specify a different template -> flask-migrate

**Comment by miguelgrinberg** [comment]
@chedrik there is no way to specify custom templates at this time.
