### ISSUE TITLE
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite

### ISSUE THREAD

**Issue by RobiIhs** [miguelgrinberg/Flask-Migrate#197]
I'm following precisely your Flask Mega-Tutorial (I bought the book ;-)).
I'm using windows, and pipenv for my virtual environments.

After executing p.40 << flask db init >> command I gave a look to the **env.py** file and pylint showed the error in the subject:
_Module 'alembic.context' has no 'config' member_

Nevertheless I run << flask db migrate -m "users table" >> and I had the following error:
_sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite_

Thank you in advance.
Roberto

**Comment by miguelgrinberg** [comment]
What Python version are you using?

I would not worry about the pylint error for now. Linters are often confused, specially with auto-generated code. What's important is to figure out errors that occur at runtime.

The error that you get when running the `flask db migrate` command suggests your Python installation does not have the expected stuff. I suggest you try not using pipenv, to see if that helps. I have found pipenv to not be very stable in my own tests, never seen an error like yours, but it would help to rule pipenv out by using straight pip as I show in the tutorial. If that does not help, I would look into reinstalling Python, or getting a newer version if what you are using is too old.

**Comment by RobiIhs** [comment]
Hi, unfortunately at home the problem persists.
First of all I tried avoiding pipenv following tutorial instructions, I got the same:
_sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite_
Secondly I tried to reset all python installation, uninstalling, cleaning pip cache and starting from python 3.6.5, no good news, same error:
_sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite_
Tonight I will give another try but I feel blind and I expect the same result.

So, the situation is: two windows 10 PCs with python 3.6, the job one working, the home one not.

Thanks.
Roberto

**Comment by RobiIhs** [comment]
Hello,
I can't believe it but after an accurate cleaning of the python stuff
- pip uninstalling everything
- pip cache folder deleted
- pipenv cache folder deleted
- pipenv virtual envs deleted
- venv virtual env deleted
- python 3.6 uninstall
- restart
- python folder deleted
- path cleaned
- CCleaning the registry

I installed python 3.6 with python-3.6.5-amd64.exe (checking MD5) in c:\Python36 (this time avoiding "Program Files" directory).

After that I followed the tutorial steps (as you can see in the log file).
Same error:
_sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite_

If you don't have any ideas,
I think I will try to use flask without flask-migrate.
Thank you very much.
Roberto
[20180417_pip_flask.txt](https://github.com/miguelgrinberg/Flask-Migrate/files/1921017/20180417_pip_flask.txt)

**Comment by miguelgrinberg** [comment]
Start a python shell in your virtual environment and run the following:

    import sqlalchemy.dialects.sqlite

Does that work or give you errors?

**Comment by RobiIhs** [comment]
Thank you for you reply, it works:

`(venv) E:\Work\Flask\FicoBlog>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy.dialects.sqlite
>>>
>>> dir( sqlalchemy.dialects.sqlite )
['BLOB', 'BOOLEAN', 'CHAR', 'DATE', 'DATETIME', 'DECIMAL', 'FLOAT', 'INTEGER', 'NUMERIC', 'REAL', 'SMALLINT', 'TEXT', '
TIME', 'TIMESTAMP', 'VARCHAR', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__'
, '__package__', '__path__', '__spec__', 'base', 'dialect', 'pysqlcipher', 'pysqlite']`

**Comment by ssbarnea** [comment]
I encountered the same problem on a different project, mainly `pylint` complaining about the same issue and for good reasons. I was able to replicate the problem easily:
```
>python
Python 2.7.14 (default, Nov 28 2017, 20:12:14)
from alembic import context
config = context.config
AttributeError: 'module' object has no attribute 'config'

 dir(context)
Out[5]:
['EnvironmentContext',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '_name_error',
 'begin_transaction',
 'configure',
 'create_module_class_proxy',
 'execute',
 'get_bind',
 'get_context',
 'get_head_revision',
 'get_head_revisions',
 'get_impl',
 'get_revision_argument',
 'get_starting_revision_argument',
 'get_tag_argument',
 'get_x_argument',
 'is_offline_mode',
 'is_transactional_ddl',
 'requires_connection',
 'run_migrations',
 'static_output']
```

In case it matters, I am using pyenv 2.7 on MacOS.

Any ideas?

**Comment by vishalraina** [comment]
@RobiIhs and @ssbarnea were you able to resolve this?
 I had a similar issue but turns out I had a typo in my config.py especially around sqlite:/// path.

**Comment by jodhansingh** [comment]
@RobiIhs As @vishalraina mentioned, please make sure it's sqlite:/// and NOT sqlllite:///. I was having the same issue until I fixed the type.

**Comment by RobiIhs** [comment]
Thank you very much. That was the problem.
I wrote "sqllite" instead of "sqllite" in DATABASE URI string.
I apologize for my stupid mistake.

**Comment by Mattlu88** [comment]
Hahaha... I got the same issue and I found out I made the same mistake.
Thank you all!

**Comment by 00h-i-r-a00** [comment]
I just made the same mistake as well, thanks for everyone who posted, helped me detect it.

**Comment by amitrawat14** [comment]
same here....

**Comment by EricRiml** [comment]
Yeah, me too.  Why is that such an easy mistake?

**Comment by weimingzhen** [comment]
sqllite  is error should sqlite  =>  sqlite:///test.db

**Comment by mariaiano** [comment]
I had a typo in my keystone.conf connection string written as mysql+pymsql:// instead of mysql+pymysql://. Thanks for pointing me to the solution!

**Comment by sssyam** [comment]
I made the same mistake XD

**Comment by Neel-rishabhsoft** [comment]
This chat is hilarious.. dis the same thing!

**Comment by sachsom95** [comment]
'sqlite:///xyz.db' naming issue is the most prevalent ones

**Comment by GodaProjects** [comment]
> @RobiIhs and @ssbarnea were you able to resolve this?
> I had a similar issue but turns out I had a typo in my config.py especially around sqlite:/// path.

I had this error when instead of using sqlite, i used sqllite....

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///goda.db'

Changed the typo and it worked like charm

I am a complete noob to Python (come from JS and Java world)

**Comment by Khantanjil** [comment]
Had the same error but i fixed it, i changed `app.config['SQLALCHEMY_DATABASE_URI'] = 'posgresql://...` to `app.config['SLQALCHEMY_DATABASE_URI'] = 'posgresql://...`
Changed the S**Q**L to S**L**Q

**Comment by Khantanjil** [comment]
Alright, was a mistake, i had `posgresql` instead of `pos**t**gresql`

**Comment by mmuokuba** [comment]
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:posgresql
gives this error when information is sent to the database
how can i solve this issue

**Comment by miguelgrinberg** [comment]
@mmuokuba The name is `postgresql`, not `posgresql`.

**Comment by GitauHarrison** [comment]
@miguelgrinberg Givent this configurations:

```
class Config(object):
    # Database configuration
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
```
How can I ensure that whenever I push my app to Heroku the DATABASE_URL returns `postgresql://` instead of `postgres://`? 

I have noted this on a new project I am working on. The current version of SQLALCHEMY is `SQLAlchemy==1.4.x` which give this error on Heroku:

```
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```
Changing to  `SQLAlchemy==1.3.x` fixes the issue. Understandably, `SQLAlchemy==1.3.23` is the last release.

**Comment by miguelgrinberg** [comment]
@GitauHarrison as you discovered, this is something that changed with SQLAlchemy 1.4. There is a thread about this issue with some proposed solutions here: https://github.com/pallets/flask-sqlalchemy/issues/929.

**Comment by Thanhha456** [comment]
@GitauHarrison your solution works for me with DATABASE_URL =  "postgres://..." . Thanks a lot.

**Comment by GitauHarrison** [comment]
@Thanhha456 
This solution works, but it is not recommended to downgrade to a previous version. I later found out that to work with `SQLAlchemy==1.4.x` especially with Heroku, you can simply pass `sslmode='require'` to `SQLALCHEMY_DATABASE_URI`. This is how it will look like:

```
class Config(object):
    # Database configuration
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL?sslmode=require') or \
        'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
```

**Comment by Thanhha456** [comment]
@Gitau Harrison: SLQAlchemy==1.4.4 didn't work for me, 'sslmode='require'
was included. When I switched to SLQAlchemy==1.3.23, it started working
then. Thanks for saving me :D

**Comment by caliraftdude** [comment]
> @RobiIhs As @vishalraina mentioned, please make sure it's sqlite:/// and NOT sqlllite:///. I was having the same issue until I fixed the type.

GRAAHHH!!!!   that fixed it.

**Comment by mazonalx** [comment]
> Thank you very much. That was the problem.
> I wrote "sqllite" instead of "sqlite" in DATABASE URI string.
> I apologize for my stupid mistake.

Oh man i just noticed the same mistake. Thank you

**Comment by ikamran** [comment]
> Hahaha... I got the same issue and I found out I made the same mistake. Thank you all!

I got the same issue like others instead of sqlite i wrote sqllite

**Comment by rydz99** [comment]
my solution on macos was: pip install pylint-flask

**Comment by olivia-tran** [comment]
> @RobiIhs and @ssbarnea were you able to resolve this? I had a similar issue but turns out I had a typo in my config.py especially around sqlite:/// path.

ahahah after almost 10-15 minutes of debugging, I noticed I also typed SQL instead of sqlite here!!!! typos are real! xD

**Comment by elias-henrique** [comment]
> 

my hero 💘

**Comment by AlvinKimata** [comment]
> I'm following precisely your Flask Mega-Tutorial (I bought the book ;-)). I'm using windows, and pipenv for my virtual environments.
> 
> After executing p.40 << flask db init >> command I gave a look to the **env.py** file and pylint showed the error in the subject: _Module 'alembic.context' has no 'config' member_
> 
> Nevertheless I run << flask db migrate -m "users table" >> and I had the following error: _sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite_
> 
> Thank you in advance. Roberto

I resolved this issue by downgrading SQLAlchemy from version `2.0.12` to version `1.4`

**Comment by jockgit** [comment]
Fast forward to 2024, and people are still making the mistake with sqlite, me included.

Thanks so much for posting this. Was just about the blowup my 💻 😉

**Comment by alexman128** [comment]
> > @RobiIhs and @ssbarnea were you able to resolve this? I had a similar issue but turns out I had a typo in my config.py especially around sqlite:/// path.
> 
> ahahah after almost 10-15 minutes of debugging, I noticed I also typed SQL instead of sqlite here!!!! typos are real! xD

Come on, did the same mistake as well hahahahahah
