### ISSUE TITLE
Can't install Flask-Migrate. TooManyRedirects

### ISSUE THREAD

**Issue by cythgear** [miguelgrinberg/Flask-Migrate#198]
Everytime I try to install Flask-Migrate through pip, I get a long stack trace followed by:
`
raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)pip._vendor.requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`

**Comment by miguelgrinberg** [comment]
There was a pypi.org outage today, that is likely the cause of your error.
