### ISSUE TITLE
Support for multiple databases

### ISSUE THREAD

**Issue by mr-pj** [miguelgrinberg/Flask-Migrate#20]
I was wondering if Flask-Migrate would be able to support the SQLALCHEMY_BINDS option.

I want to have frontend and backend database models be seperated for an application I am developing. 

SQLAlchemy provides this option with SQLALCHEMY_BINDS and with defining the context in the table (example see here: http://pythonhosted.org/Flask-SQLAlchemy/binds.html)

Can you support this? If not is there any other recommendation of handling multiple databases in sqlalchemy with migrations?

**Comment by jonelovemira** [comment]
@miguelgrinberg was right. I have tried to use include_object in migrations/env.py like this:

# add a function 
def include_object(object, name, type_, reflected, compare_to):
    if object.info.has_key('bind_key'):
        if object.info['bind_key'] == 'bindkey':
            return False

    return True

# add callbacks in configure of context ( in the function named 'run_migrations_online' )
context.configure(
                connection=connection,
                target_metadata=target_metadata,
                include_object = include_object
                )

but this method is only for separate the bind and default databases.

**Comment by briglass** [comment]
Hello,

I've built my Flask site using Flask-Security and Flask-Migrate, meaning I have a SQLite database. I've deployed it to AWS, and it seems as though MySQL is better for this (especially if I use RDS). Hopefully I am wrong, and there is a decent way to continue to use SQLite on AWS EB. If not, is there a fairly simple way to switch over to MySQL (maintaining my use of Flask-Migrate and Flask-Security)?

Thanks

**Comment by reee** [comment]
As dict.has_key() has been removed in python3, the python3 version should go as blow:
1. Add the include_object fuction:
`
 def include_object(object, name, type_, reflected, compare_to):                                            
     if 'bind_key' in object.info:                                                                          
         if object.info['bind_key'] == 'radius':                                                            
             return False                                                                                   
     return True
`

2. add callbacks in configure of context ( in the function named 'run_migrations_online' )
`context.configure(                                                                                 
            connection=connection,                                                                         
            target_metadata=target_metadata,                                                               
            **include_object=include_object,**                                                                 
            process_revision_directives=process_revision_directives,                                       
            **current_app.extensions['migrate'].configure_args                                             
        )`
