### ISSUE TITLE
Confusing log entries for the normal case

### ISSUE THREAD

**Issue by vidstige** [miguelgrinberg/Flask-Migrate#201]
Then running the `upgrade()` function, the following is printed in the log

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

This does not make much sense to me, these log entries should either be removed or set as `debug`, instead it should say something like `Schema up to date` or similar when the `upgrade()` function did not perform any schema-altering operations.

**Comment by miguelgrinberg** [comment]
These are not generated by this package, but by Alembic. But I agree, they should be suppressed unless you want the all the verbosity.

**Comment by vidstige** [comment]
There does not seem to be any way to enter issues over at https://github.com/zzzeek/alembic 

How do we move forward? I just want to get impressed when trying out Flask-Migrate... 🤔

**Comment by miguelgrinberg** [comment]
I don't think this is an Alembic issue, btw. I should adjust the level of logging so that INFO messages do not appear. But in any case, Alembic's main repository is on bitbucket: https://bitbucket.org/zzzeek/alembic. The GitHub repo is a mirror.

**Comment by miguelgrinberg** [comment]
The default logging level is now WARN.

**Comment by vidstige** [comment]
Oh, snap :-/ What's a good solution then? Change it just for the `upgrade` command?

**Comment by miguelgrinberg** [comment]
I'm not sure. The best solution would be for Alembic to reorganize the logging levels so that nothing shown with INFO level is important information.

**Comment by vidstige** [comment]
Alright, lets file an issue over at [bitbucket](https://bitbucket.org/zzzeek/alembic/issues?status=new&status=open). I can do it if you want?

**Comment by miguelgrinberg** [comment]
@vidstige sure, go for it.
