### ISSUE TITLE
Issue with Flask > 1.0

### ISSUE THREAD

**Issue by Mappboy** [miguelgrinberg/Flask-Migrate#202]
This may be a more general problem but I am recieving this error after upgrading Flask (greater than 1.0), when running `flask db upgrade` .

> Table 'app.role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

Flask 0.12.4, seems to work fine. I am guessing it might have something to do with the metadata in the env file or maybe it is just a Flask problem?

Any ideas?

**Comment by miguelgrinberg** [comment]
I can't reproduce this with the test project in this repository, so I don't believe this is a problem with Flask 1.0.

The error seems to suggest you have duplicated table names.

Have you also upgraded Flask-SQLAlchemy at the same time as Flask, by any chance? There were some changes in recent versions that may cause this error for certain projects. Check the names of all the tables in your database and look for duplicates.

**Comment by Mappboy** [comment]
Hi Michael, 
Thanks for the speedy reply. 

Pretty positive I don't have any duplicate names. 
I can still do flask run and everything works fine.

I am guessing this may have something to do with Flask-SQLAlchemy, any idea on what the error that may cause this in Flask-SQLAlchemy ?
I'll poke around.

**Comment by miguelgrinberg** [comment]
Was Flask-SQLAlchemy upgraded at the same time you upgraded Flask? Maybe try to downgrade Flask-SQLAlchemy to the version you had before and see if that helps.

Also, if you can reproduce this with a complete example that you can share with me, I can investigate more in detail.

**Comment by Mappboy** [comment]
Hi Michael,

Thanks for your help. The problem was entirely my fault. 
I think it was slightly tied to https://github.com/pallets/flask/issues/1847. 
I was importing modules from my package instead of directly from the file. 
This was then causing the `__init__.py` file to be reimported which lead to my models.py file being reimported. 

To clarify:
```
# I was doing this, 
<module>.views import <blueprint>

# Instead of 
from <application>.<module>.views import <blueprint>
```
Pretty surprised it worked normally before the upgrade. 

Cheers
