### ISSUE TITLE
Is it possible to migrate a certain DB only?

### ISSUE THREAD

**Issue by bruce3557** [miguelgrinberg/Flask-Migrate#205]
Hi,

I want to know does it support migrating a certain DB? (or does it make sense?)

The case in our development is like we can access some "read-only" databases and use ORM to manage the queries. In the same time, we have our application database which we need to do CRUD operation on it.
If I use `flask db init` and `flask db migrate`, it will create the tables in "read-only" database.
Another try is to use `flask db init --multidb` and `flask db migrate`, and it will try to change the state of "read-only" DB.

So is it possible to have the flow like:
1. init with multidb: `flask db init --multidb`
2. migrate with a certain database: `flask db migrate db1`

Thanks!

**Comment by miguelgrinberg** [comment]
If you use the multidb option and never change anything in your read-only database models, then there will never be an attempt to migrate that database.

The alternative, which I think is simpler and more robust, is to define your own database as the main database in Flask-SQLAlchemy, and add the read-only one as secondary. Then use the regular single-database configuration for Flask-Migrate.

**Comment by bruce3557** [comment]
Thanks, that is a good suggestion and we will try this first!

By the way, we have a short discussion about the design XD. Not sure whether our guess is correct.
Is this kind of migration mechanism designed for sharding databases but not databases for different purpose?

**Comment by miguelgrinberg** [comment]
This is designed for separate databases. Each model needs to be tagged with the database it belongs to, that is why I said in the beginning that as long as you don't change the models associated with your read-only database, then you should be fine.

**Comment by bruce3557** [comment]
got it, thanks!
