### ISSUE TITLE
Flask-Migrate 2.2 not compatible with alembic 0.6.5

### ISSUE THREAD

**Issue by jwg4** [miguelgrinberg/Flask-Migrate#211]
Hi there,
The current version of setup.py specifies a version of alembic of 0.6 or better (see https://github.com/miguelgrinberg/Flask-Migrate/blob/1cc819e9f2a17435429c16531043d0a874f76288/setup.py#L27).

However, Flask-Migrate 2.2, the last released version, doesn't seem to work with alembic 0.6.5.

```
(venv) jack@foo:~/z/migrate_versions$ pip freeze
alembic==0.6.5
click==6.7
Flask==1.0.2
Flask-Migrate==2.2.0
Flask-SQLAlchemy==2.3.2
itsdangerous==0.24
Jinja2==2.10
Mako==1.0.7
MarkupSafe==1.0
SQLAlchemy==1.2.8
Werkzeug==0.14.1
```

```
(venv) jack@foo:~/z/migrate_versions$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask_migrate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack/z/migrate_versions/venv/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 14, in <module>
    from alembic.util.exc import CommandError
ImportError: No module named exc
```

We can work around this. However, we'd be pleased if the setup.py had a reasonable value, so that `pip-compile` just works for us. Let me know if more info is needed. Thanks in advance!

**Comment by jwg4** [comment]
After a little more investigation, it seems like Flask-Migrate 2.2 works with alembic==0.8.6 but not earlier.

**Comment by miguelgrinberg** [comment]
Good catch!

I have made some changes to that import and was able to set the alembic dependency as far back as 0.7.

**Comment by jwg4** [comment]
Thanks for the fix @miguelgrinberg speedy as ever :)
