### ISSUE TITLE
Flask-Migrate not updating revision in database

### ISSUE THREAD

**Issue by nsiregar** [miguelgrinberg/Flask-Migrate#214]
while running command `flask db migrate` , migration doesn't run because revision in database not updated during last `flask db upgrade`. need to update the revision manually with `flask db stamp <last revision>`.

**Comment by miguelgrinberg** [comment]
Can you include the output of a complete session, where you run `migrate`, followed by an `upgrade`, followed by another `migrate` that shows this error?

**Comment by nsiregar** [comment]
here is tho complete session until get the `head stamp`
![flask-migrate-issue](https://user-images.githubusercontent.com/18432852/42435418-72b66edc-8391-11e8-85be-b1396fd6618b.png)

**Comment by miguelgrinberg** [comment]
This is very weird, never seen this problem. Are your migration scripts making any changes to the database? I noticed that the first migrate did not generate anything, or at least that's what it looks like, since there is no output on the command.

In any case, you may need to ask in the Alembic, I think your problem is more with the Alembic package than with Flask-Migrate which is just the Flask wrapper.

**Comment by miguelgrinberg** [comment]
The `flask db migrate` command does not generate databases, it generates migration scripts. The correct process is as follows:

1. `flask db init` when you set up your migration repository
2. create or modify your database models
3. `flask db migrate` to generate a migration script for the changes made in step 2
4. `flask db upgrade` to apply the changes in the migration script generated in step 3
5. go back to step 2

**Comment by cancan101** [comment]
maybe: https://github.com/miguelgrinberg/Flask-Migrate/commit/2dd45d0037cb62bc7a8a981f0de70071b891a2ff#r30781562

**Comment by raphaeloneves** [comment]
> The `flask db migrate` command does not generate databases, it generates migration scripts. The correct process is as follows:
> 
> 1. `flask db init` when you set up your migration repository
> 2. create or modify your database models
> 3. `flask db migrate` to generate a migration script for the changes made in step 2
> 4. `flask db upgrade` to apply the changes in the migration script generated in step 3
> 5. go back to step 2

`db upgrade` has worked for me. Thanks a lot!

**Comment by karolpawlowski** [comment]
Hey @miguelgrinberg 

I also encountered this problem on Sqlite database and current Flask-Migrate version (2.7.0)

```(measurements-repository) $(f_notifyme)karol@Karols-MacBook-Pro measurements-repository % flask db upgrade             
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e77c5105c15c, Initial migration.
(measurements-repository) $(f_notifyme)karol@Karols-MacBook-Pro measurements-repository % flask db current
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
e77c5105c15c (head)
(measurements-repository) $(f_notifyme)karol@Karols-MacBook-Pro measurements-repository % flask db migrate
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added column 'measurement.device_type'
INFO  [alembic.autogenerate.compare] Detected added column 'measurement.filename'
INFO  [alembic.autogenerate.compare] Detected added unique constraint 'None' on '['filename']'
INFO  [alembic.autogenerate.compare] Detected removed column 'measurement_row.filename'
  Generating /Users/karol/PycharmProjects/measurements-repository/migrations/versions/ffbabb3e36e3_.py ...  done
(measurements-repository) $(f_notifyme)karol@Karols-MacBook-Pro measurements-repository % flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade e77c5105c15c -> ffbabb3e36e3, empty message
(measurements-repository) $(f_notifyme)karol@Karols-MacBook-Pro measurements-repository % flask db current
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
e77c5105c15c
(measurements-repository) $(f_notifyme)karol@Karols-MacBook-Pro measurements-repository % 
```

**Comment by miguelgrinberg** [comment]
@karolpawlowski the problem is with Alembic. Flask-Migrate is just a simple wrapper that makes Alembic easier to use with Flask.
