### ISSUE TITLE
Picking up changes to field(s) when running flask migrate command on MySQL

### ISSUE THREAD

**Issue by melv1n** [miguelgrinberg/Flask-Migrate#218]
I was trying to modify an relationship table where I forgot to set the primary keys. I discovered that after saving my model the flask migrate command doesn't pickup changes to the field.

**Example**

I first had this and executed the migrate/upgrade: 
```
user_has_task = db.Table('user_has_task', db.Model.metadata,
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('task_id', db.Integer, db.ForeignKey('task.id')),
)
```

Forgot to add the primary keys, so I added them:

```
user_has_task = db.Table('user_has_task', db.Model.metadata,
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True),
    db.Column('task_id', db.Integer, db.ForeignKey('task.id'), primary_key=True),
)
```
The flask migrate command didn't pickup any changes when those keys were added.
Is there any way that it can detect changes to any fields within the column when hitting the flask migrate command? I've searched and didn't find a specific answer whether this is by design or something that should work.

MySQL version: 5.7.12

**Comment by miguelgrinberg** [comment]
Flask-Migrate is a wrapper for Alembic, it does not have any migration logic itself. This could be an Alembic problem, but in any case, anything that Alembic does not pick up by itself you can hand edit in the migration script. The Alembic documentation shows what operations can be defined in scripts.

**Comment by melv1n** [comment]
That's a clear answer. Thanks for this package @miguelgrinberg, love it!
