### ISSUE TITLE
Flask not generating any migration

### ISSUE THREAD

**Issue by michaelbukachi** [miguelgrinberg/Flask-Migrate#220]
Hello there,
I'm in a huge pickle. Flask-Migrate is not generating any migrations. I keep getting the following:
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.env] No changes in schema detected.

```
My directory structure is as follows:
```
.
├── app
│   ├── config.py
│   ├── credentials.json
│   ├── database.py
│   ├── errors.py
│   ├── factory.py
│   ├── fake.json
│   ├── models
│   │   ├── helium.py
│   │   ├── __init__.py
│   │   ├── logs.py
├── app.db
├── credentials.json
├── env-example
├── fake.json
├── migrations
│   ├── alembic.ini
│   ├── env.py
│   ├── env.pyc
│   ├── README
│   ├── script.py.mako
│   └── versions
├── pytest.ini
├── README.md
├── requirements.txt
├── run.py
├── sample-loan.json
├── tasks.py
├── test.sh
├── worker.sh
├── wsgi.py

```

Here's my main `__init__.py` file:

```
from .factory import Factory


def create_app(environment='development'):
    factory = Factory(environment)
    factory.set_flask()
    factory.set_celery()

    factory.set_db()
    factory.set_migration()
    from . import models


    factory.register(lms_blueprint)
    factory.register(mifos_blueprint)
    factory.register(br_blueprint)

    return factory.flask
```
My model's `__init__.py` file is as follows:
```
__all__ = ['helium', 'logs']
```
My `database.py` file is as follows:
```
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
migrate = Migrate()
```
They are later initialized in `factory.py` below:
```
from __future__ import absolute_import

import logging
import logging.config
import os
import sys
from logging.handlers import RotatingFileHandler

from flask import Flask

from .config import config
from .database import db, migrate
from .tasks import celery_app, redis


class Factory:

    def __init__(self, environment='development'):
        self._environment = os.environ.get('APP_ENVIRONMENT', environment)

    @property
    def environment(self):
        return self._environment

    @environment.setter
    def environment(self, environment):
        self._environment = environment
        self.flask.config.from_object(config[self._environment])

    def set_flask(self, **kwargs):
        self.flask = Flask(__name__, **kwargs)
        self.flask.config.from_object(config[self._environment])
        # setup logging
        file_handler = RotatingFileHandler('br.log', maxBytes=10000, backupCount=1)
        file_handler.setLevel(logging.INFO)
        self.flask.logger.addHandler(file_handler)
        stdout = logging.StreamHandler(sys.stdout)
        stdout.setLevel(logging.DEBUG)
        self.flask.logger.addHandler(stdout)
        # werkzeug = logging.getLogger('werkzeug')
        # werkzeug.setLevel(logging.DEBUG)
        # self.flask.logger.addHandler(werkzeug)
        return self.flask

    def set_celery(self, **kwargs):
        return celery_app

    def set_db(self):
        db.init_app(self.flask)
        return db

    def set_migration(self):
        migrate.init_app(self.flask, db)
        return migrate
```

I can't get it to work with sqlite or postgres. I'm not sure if my directory structure is the problem or I'm missing a step. Some guidance would be highly appreciated.

Thanks.

**Comment by miguelgrinberg** [comment]
What are the contents of the file `app/models/__init__.py`?

**Comment by michaelbukachi** [comment]
These are the contents `__all__ = ['helium', 'logs']`

**Comment by miguelgrinberg** [comment]
Did you import `helium` and `logs`?

**Comment by michaelbukachi** [comment]
Just did, made the following changes in the app's `__init__.py` file:
```
# from . import models
    from .models import Log, FollowupMessagesModel, SMSMessages, MezzanineRequestLogModel, FarmerModel, LoanModel
```
Also the made the following changes in the models `__init__.py` file:
```
#__all__ = ['helium', 'logs']
from logs import Log
from helium import FollowupMessagesModel, SMSMessages, MezzanineRequestLogModel, FarmerModel, LoanModel
```
It didn't work at first. I commented out the following lines in `env.py`
```
        if getattr(config.cmd_opts, 'autogenerate', False):
            script = directives[0]
            if script.upgrade_ops.is_empty():
                directives[:] = []
                logger.info('No changes in schema detected.')
```
and run the migrations and it worked, I then uncommented the lines again and it worked. It's quite puzzling really, is there some kind of cache that happens, that we should be aware of? This problems tend to appear for a new dev as soon as they've cloned the project ad are setting up.

**Comment by miguelgrinberg** [comment]
Not sure, but I think I was right with my guess that your models weren't being imported when you run `flask db` commands. The changes that you made caused the models to be imported, which is required for Alembic to be able to find changes.

**Comment by michaelbukachi** [comment]
Okay. I think I need to do a bit more research on the occasional odd behaviour. Just to clarify one thing though, models should be imported after the instantiation of db and migrate, right?

**Comment by miguelgrinberg** [comment]
Your model classes inherit from `db.Model`, so you have to have `db` defined or imported before your models. Likewise, your `Migrate` instance needs to take `db` as an argument in the constructor. The `Migrate` instance and the models do not have any dependency between them, but it is common to have `Migrate` defined right after `db`, so to summarize, the usual order is `db` is defined/imported first, then your `Migrate` instance, and then your models.

Note that if you use a linter, it may flag the models as being unused imports. This is fine, importing the models is necessary anyway, as Alembic and SQLAlchemy use introspection to find the models among all the imported symbols. If the models are not imported, then Alembic will think you have no models in your database schema, which is what happened to you.

**Comment by michaelbukachi** [comment]
Thanks for the clarification.

**Comment by michaelbukachi** [comment]
Thanks for clarifying that.

**Comment by johndiego** [comment]
Hello @miguelgrinberg 

I 'm understand , how i can make in factory app?
your have examples?

**Comment by miguelgrinberg** [comment]
@johndiego see https://github.com/miguelgrinberg/flasky for an example.

**Comment by johndiego** [comment]
Thanks @michaelbukachi !!
I'm new in flask!

**Comment by johndiego** [comment]
@miguelgrinberg  I'm try create new project , but don't work the flask migrate!
you can help-me please!!
my project is  https://github.com/johndiego/project

**Comment by miguelgrinberg** [comment]
@johndiego The "target is not up to date" error means that you have migrations that haven't been applied to the database. You need to look in your migrations/versions directory to see if you have any extra migrations that should not be there, or else you may need to run "flask db upgrade" to apply any migrations that are part of your project.

**Comment by michaelbukachi** [comment]
@4vadim4 I was able to fix the issue. It seems my models weren't being imported properly.

**Comment by 5hraddha** [comment]
> @michaelbukachi , i had same trouble and i found solve for me in alembic env.py file - pay attention for this lines:
> _# add your model's MetaData object here_
> _# for 'autogenerate' support_
> _# from myapp import mymodel_
> _# target_metadata = mymodel.Base.metadata_
> i imported my model class redefined _target_metadata_ , see below:
> from src.models.UserModel import UserModel
> target_metadata = UserModel.metadata
> documentation: https://alembic.sqlalchemy.org/en/latest/autogenerate.html

Thanks..!! This worked for me too..!! Now, flask db migrate is working fine and generating migrations..

**Comment by miguelgrinberg** [comment]
@5hraddha @michaelbukachi all you are doing is explicitly import your models in the Alembic config file. This would not be necessary if the models were imported somewhere in your app, which was my diagnosis when this issue started:

> Not sure, but I think I was right with my guess that your models weren't being imported when you run flask db commands

Given that you guys are now functional I'm going to close this issue. Please reopen if there are still problems.

**Comment by pranaykhilari** [comment]
Hi Miguel,

I am using flask-migrate library for migration. I have created models in models package not in my manage.py file. When I tried to migrate the model using

>  python3 manage.py db migrate
_INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.env] No changes in schema detected._

is my output. It means it is not detecting the models which I define in model folder. 

This is my manage.py content

_from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from app import app, db

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()_

This is my model file content

_from manage import db

class Employee(db.Model):
    __tablename__ = 'Employee'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128))
    email = db.Column(db.String(128))_

Please help me.

**Comment by bqube** [comment]
Hi there, I am unable to figure out why my migration files not generating for flask multidb. Since the last two days I have tried, and gone through all the comments, but unable to resolve. Can you help me with this, please!!

```
app
│   ├── module1
│   │   ├── generators
│   │   ├── helpers
│   │   ├── __init__.py
│   │   ├── resources
│   │   ├── schemas
│   │   └── services
│   ├── __init__.py
│   └── module2
│       ├── generators
│       ├── helpers
│       ├── __init__.py
│       ├── resources
│       ├── schemas
│       └── services
├── automation.py
├── config.py
├── database
│   ├── data_mart
│   ├── data_warehouse
│   │   ├── base.py
│   │   ├── fact_crawl_data.py
│   ├── __init__.py
```

this is the `config.py`

```
import os
from dotenv import load_dotenv

basedir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(basedir, '.env'))


class Config(object):
    # Database
    SQLALCHEMY_DATABASE_URI = f"{os.environ.get('DATA_MART_DRIVER')}" \
                              f"://{os.environ.get('DATA_MART_USER_NAME')}" \
                              f":{os.environ.get('DATA_MART_PASSWORD')}" \
                              f"@{os.environ.get('DATA_MART_HOST')}" \
                              f"/{os.environ.get('DATA_MART_DB_NAME')}"
    SQLALCHEMY_BINDS = {
        'db_dw': f"{os.environ.get('WAREHOUSE_DRIVER')}://{os.environ.get('WAREHOUSE_USER_NAME')}"
                 f":{os.environ.get('WAREHOUSE_PASSWORD')}"
                 f"@{os.environ.get('WAREHOUSE_HOST')}/{os.environ.get('WAREHOUSE_DB_NAME')}",
    }
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_RECORD_QUERIES = True

    # Mail
    MAIL_SERVER = os.environ.get('MAIL_SERVER')
    MAIL_PORT = os.environ.get('MAIL_PORT')
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS')
    MAIL_USE_SSL = os.environ.get('MAIL_USE_SSL')
    MAIL_SUPPRESS_SEND = os.environ.get('MAIL_SUPPRESS_SEND')

    @staticmethod
    def init_app(app):
        pass
```
this is my ` app/__init__.py`
```
import logging
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_mail import Mail
from config import config

db = SQLAlchemy()
migrate = Migrate()
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    app.logger.setLevel(logging.INFO)
    app.logger.info('App started')
    return app


from database.data_warehouse.base import Base
from database.data_warehouse.fact_crawl_data import FactCrawlData
```

this is `base.py`

```
from sqlalchemy.ext.declarative import declared_attr, as_declarative
from sqlalchemy import DDL, Column, Integer, DateTime
from sqlalchemy.sql import func

updated_at = DDL(
    "CREATE OR REPLACE FUNCTION update_changetimestamp_column()"
    "RETURNS TRIGGER AS $$"
    "BEGIN"
        "NEW.changetimestamp = now();"
        "RETURN NEW;"
    "END;"
    "$$ language 'plpgsql';"
)


@as_declarative()
class Base(object):
    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime(timezone=True), default=func.now())
    updated_at = Column(DateTime(timezone=True), default=func.now(), onupdate=func.now())
```

this is `fact_crawl_data.py`

```
from sqlalchemy import event
from app import db
from database.data_warehouse.base import Base, updated_at


class FactCrawlData(Base, db.Model):
    __bind_key__ = 'db_dw'
    __tablename__ = 'dw_fact_crawl_data'
    crawl_time = db.Column(db.DateTime)
    crawl_data_json = db.Column(db.JSON)
    product_id = db.Column(db.Integer)
    etailer_id = db.Column(db.Integer)
```

Now while running `flask db migrate ` it is giving 
```
[2020-06-23 21:20:35,992] INFO in __init__: Automation startup
INFO  [alembic.env] Migrating database <default>
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.env] Migrating database db_dw
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.env] No changes in schema detected.
```
Please help me to debug my code. If I am missing something, please tell me or my structure alteration is doing any problem, please let me know. I would be highly appreciated to get any suggestions.

Thanks,

**Comment by miguelgrinberg** [comment]
"No changes in schema detected" means that your models and the database have the same structure. Two possible reasons:

- you upgraded the database on your own sidestepping Flask-Migrate
- you are not importing your models in your application

The 2nd one has some variants. I've seen people create two database objects, and the models are imported into one, but Flask-Migrate is configured with the other. I thought I'd mention this, seeing that you are using a very strange mix of Flask-SQLAlchemy with regular SQLAlchemy.

**Comment by xiayulu** [comment]
```sh
$ python -m manage db migrate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```
When I changed something in my models, migrate didn't work.
I solved this problem by remove some files like `91c7e9304377_.py` away from the versions folder.
Then I run `$ python -m manage db migrate`, it worked.
I hope this may help you.

**Comment by emmanuel-rosillo** [comment]
need your help, I have this problem, I'm trying to make a migration, and get this error:

```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.
```

my repo is here:
[https://github.com/emmanuel-rosillo/application](url)

my app-run is run.py:

``` python
from scr import app

if __name__ == '__main__':
    app.run()
```
``` python
my app-init is inside of scr:

from flask import Flask
from flask_migrate import Migrate
from config import Config
from .routes import global_scope
from flask_sqlalchemy import SQLAlchemy
from .models import db


# initialization app
app = Flask(__name__, static_folder=Config.STATIC_FOLDER, template_folder=Config.TEMPLATE_FOLDER)
app.config.from_object(Config)

# instances
SQLAlchemy(app)
migrate = Migrate(app, db)

# create tables
with app.app_context():
    db.create_all()

# blueprints
app.register_blueprint(global_scope, url_prefix='/')
```

my import "db":
``` python
from flask_sqlalchemy import SQLAlchemy

# instance to use SQLAlchemy
db = SQLAlchemy()
```
my models is in ModelUser.py

``` python
from .db import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    firstName = db.Column(db.String(25), nullable=False)
    lastName = db.Column(db.String(25), nullable=False)
    email = db.Column(db.String(80), nullable=False)

    def __init__(self, name, firstName, lastName, email):
        self.name = name
        self.firstName = firstName
        self.lastName = lastName
        self.email = email

    def __repr__(self):
        return f'{self.name}'


class Face(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    vectorEyes = db.Column(db.Integer, nullable=False)
    vectorEars = db.Column(db.Integer, nullable=False)
    vectorLips = db.Column(db.Integer, nullable=False)
    pic = db.Column(db.BLOB)
    user = db.Column(db.String(80), nullable=False)

    def __init__(self, vectorEyes, vectorEars, vectorLips, user):
        self.vectorEyes = vectorEyes
        self.vectorEars = vectorEars
        self.vectorLips = vectorLips
        self.user = user

    def face(self, pic, user):
        self.user = user
        self.pic = pic

    def __repr__(self):
        return f'{self.pic, self.user}'


class Tickets(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    fullNameUser = db.Column(db.String(80), nullable=False)
    ticket = db.Column(db.Integer, nullable=False)

    def __init__(self, fullNameUser, ticket):
        self.fullnameUser = fullNameUser
        self.ticket = ticket

```

plss helpme, I've been trying for three days

**Comment by miguelgrinberg** [comment]
@emmanuel-rosillo I think it would be better if you start from a more "traditional" structure, and then start making changes if you need to. This is a strange way to initialize your app, where you have `db` initialized without the app. That is probably what's giving you the problem, but I'm not completely sure.

**Comment by emmanuel-rosillo** [comment]
@miguelgrinberg 

I just solved this problem, just export in this mode:

`export FLASK_APP=directory_complete_of_rute_/run.py`

in my case

`export FLASK_APP=/home/elalocador/Desktop/facial_comparate/Register/application/run.py`

pd: in my case, enter the folder scr who containing my folder_models to create folder_migrations aside.

folder models:
`/home/elalocador/Desktop/facial_comparate/Register/application/scr`

run the command in path:
`/home/elalocador/Desktop/facial_comparate/Register/application/scr`

my command complete:

``` bash
(venv) elalocador@alocadora:~/Desktop/facial_comparate/Register/application/scr$ export FLASK_APP=/home/elalocador/Desktop/facial_comparate/Register/application/run.py
(venv) elalocador@alocadora:~/Desktop/facial_comparate/Register/application/scr$ flask db init
```

thak you so much, @miguelgrinberg , for your help
