### ISSUE TITLE
How do I pre populate table data for the application using Flask-Migrate?

### ISSUE THREAD

**Issue by ilovetogetspamed** [miguelgrinberg/Flask-Migrate#221]
I found this [link to the Alembic Cookbook](http://alembic.zzzcomputing.com/en/latest/cookbook.html) in the migrations/env.py file and am very interested in the [conditional migrations implementation](
http://alembic.zzzcomputing.com/en/latest/cookbook.html#conditional-migration-elements) for pre populating table data for the application's lookup tables.  e.g. 'employee types', full-time, part-time etc.

and I found this code in flask-migrate/__init__.py:
```
...
@MigrateCommand.option('-x', '--x-arg', dest='x_arg', default=None,
                       action='append', help=("Additional arguments consumed "
                                              "by custom env.py scripts"))
def upgrade(directory=None, revision='head', sql=False, tag=None, x_arg=None):
    """Upgrade to a later version"""
    config = current_app.extensions['migrate'].migrate.get_config(directory,
                                                                  x_arg=x_arg)
    command.upgrade(config, revision, sql=sql, tag=tag)
...
```
I'm new to Python and Flask and am not sure where I should be putting/creating the
```
def data_upgrades():
    """Add any optional data upgrade migrations here!"""
...
def data_downgrades():
...
```
functions. 

Would I do the '$ flask db migrate', change the generated migration file to match the Cookbook example (with my data of course), and then execute '$flask db -x data=true upgrade'?

BTW, I bought your Book and Flask Mega Tutorial training to get up to speed.  It's helped me a lot but I'm still get lost when going deeper... ;-)  Neither of them cover extending the flask-migrations classes.

Thanks

**Comment by miguelgrinberg** [comment]
Yes, the `flask db upgrade` command is similar to `alembic upgrade` so you can move the arguments.

**Comment by ilovetogetspamed** [comment]
Thanks Miguel,

I really  appreciate your response!

Chris
