### ISSUE TITLE
Error: "sqlalchemy.exc.NoSuchTableError: sqlitestudio_temp_table"

### ISSUE THREAD

**Issue by yn-coder** [miguelgrinberg/Flask-Migrate#222]
Got this error when `flask db migrate`

    sqlalchemy.exc.NoSuchTableError: sqlitestudio_temp_table

Command working for previous checkout, when `migrations\versions` folder is empty. If it initialized with first version - migration command will break.

Troubled version is here:

https://github.com/yn-coder/CodingTeacher/commit/e8197ef61d52961bb6122bab4f3af3ed17f9e917

**Comment by yn-coder** [comment]
Sorry, I don't know. I'm testing the FM in local project with sqlite database, and got this. I think it could be some internal SQLite error. Google doesn't help.

**Comment by miguelgrinberg** [comment]
That's a table name in your database, if you did not create this table, you are using some tool that did, and the table somehow got into one of your migration scripts. Review the scripts, remove all references to this table, and maybe that'll solve the problem for you.

**Comment by yn-coder** [comment]
I think it's some sqlite error, not FM, so I close this the issue. Thank you.

**Comment by yn-coder** [comment]
close
