### ISSUE TITLE
Unable to use flask db init

### ISSUE THREAD

**Issue by lkanand** [miguelgrinberg/Flask-Migrate#224]
Even though I've installed flask migrate, I am unable to run the flask db init command on my terminal. When I do, I get the following error:
usage: flask [-h] [--logconf LOGCONF] [--props PROPS] [-q] [--tmp-dir TMP_DIR]
flask: error: unrecognized arguments: db init

**Comment by miguelgrinberg** [comment]
Check these two things please:

- Did you set the `FLASK_APP` environment variable correctly?
- Did you initialize the Flask-Migrate extension in your application?

**Comment by miguelgrinberg** [comment]
It should be set to the main file of your application, where the application instance is defined or created.

**Comment by lkanand** [comment]
That's what it's set to. My application instance is called `DAEMON_APP.flask_app` instead of `app`. Could that be the cause of the problem?
