### ISSUE TITLE
Flask migrate couldn't read models?

### ISSUE THREAD

**Issue by Calvert-NYSSL** [miguelgrinberg/Flask-Migrate#225]
I am trying to get the "python manage.py db migrate" to work but I keep getting these two lines only.

> INFO [alembic.runtime.migration] Context impl PostgresqlImpl.
> INFO [alembic.runtime.migration] Will assume transactional DDL.
> 

Can someone explains what does the two lines mean? I am guessing the heroku backend that I am having couldn't compare the models.py and update the table. Correct me if I am wrong.

In my view.py, I have "from models import *" and in my app.py, I have "from view.py".

My friend has no problem migrating the database at all and he couldn't remember what he did to solve it.

I ran "python manage.py db show" and it shows me this

> empty message
> 
> Revision ID: b8b188e67d59
> Revises: 5b82870de25a
> Create Date: 2018-08-31 13:24:27.359151

I ran this "select * from alembic_version;" and I get

> version_num
> 32a4b24d4961

Please let me know if the numbers makes any sense or the numbers are not helping at all.  I just want to be able to update the table using the migrate and upgrade command whenever I add a column. and I have no idea what preventing it from reading my models.

**Comment by miguelgrinberg** [comment]
Those two lines that you get are normal, Alembic always prints those lines to give you some details on how it is going to process migrations. You can ignore those lines.

What is the output of `flask db history`?

**Comment by Calvert-NYSSL** [comment]
I am new to flask and today is my first time doing the flask-migrate thing. I don't know much but I will try to provide as many info needed to fix this. I tried `flask db history` and I get this error.

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

I get those two lines and the process ended without telling me if it detected table changes or not.  I checked the table and no changes have been made after calling the migrate and upgrade command.

**Comment by miguelgrinberg** [comment]
Did you try again after setting your `FLASK_APP` variable? The `flask` command requires this variable to be set.

**Comment by Calvert-NYSSL** [comment]
I feel bad for asking this and FYI I didn't create this web app. I am taking over from someone else and learning to do stuff with it. 

How do you set that? I  did a quick google and do I use export to set the FLASK_APP?

I do not have the init py file but here I have a different name lets call it ABC.py in the ABC folder.
`app = Flask(__name__)`

I tried the command in cmd but failed.
`export FLASK_FLASK=ABC/ABC.py`

**Comment by miguelgrinberg** [comment]
It's impossible for me to tell you that without seeing the code. You should ask the person who maintained this application before you.

**Comment by Calvert-NYSSL** [comment]
I think I got the `flask db history` to work. I went to powershell and typed `$env:FLASK_APP = "ABC.py"`.
This is what I get after running `flask db history`.

Traceback (most recent call last):
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rem\AppData\Local\Programs\Python\Python37-32\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\flask\cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\flask_migrate\cli.py", line 174, in history
    _history(directory, rev_range, verbose)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\flask_migrate\__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "c:\users\rem\appdata\local\programs\python\python37-32\lib\site-packages\flask_migrate\__init__.py", line 333, in history
    config = current_app.extensions['migrate'].migrate.get_config(directory)
KeyError: 'migrate'

**Comment by Calvert-NYSSL** [comment]
I wish I could show you the code but it is not mine. I take your recommendation and hopefully it will be a good news. Thank you

**Comment by Calvert-NYSSL** [comment]
No luck, have to solve it myself. Does anyone know what is this error all about?

`directory = current_app.extensions['migrate'].directory
KeyError: 'migrate'`

**Comment by miguelgrinberg** [comment]
You haven't initialized the Flask-Migrate extension. Read the docs for instructions on how to set it up with your project.

**Comment by miguelgrinberg** [comment]
I don't think you understand what I"m saying. The `KeyError: 'migrate'` means that the extension is not initialized. I'm not making a guess here, I'm telling you what's missing in your application. If you think this other developer initialized the extension, then find that code and investigate why it does not run. Once the initialization works, you will not see this error. If you see this error nothing will work, you cannot ignore it.

**Comment by Calvert-NYSSL** [comment]
In models.py:
`from AppName import db
from flask_login import UserMixin
from sqlalchemy.orm import relationship
from sqlalchemy.ext.mutable import Mutable

class User....`

In AppName:
`from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail

app = Flask(__name__)
app.config.from_pyfile('config.py')

Bootstrap(app)
db = SQLAlchemy(app)
mail = Mail(app)
from views import *

if __name__ == '__main__':
    app.run(debug=True)`

In manage.py:
`from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from models import db
from NYSSLPMS import app

# db migrate
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()`

In config.py:
`import os
from datetime import datetime

SECRET_KEY = 'secret key'
SQLALCHEMY_DATABASE_URI = "this is the uri"`

Based on the knowledge that I have, the initialization is there. Did I miss something?

**Comment by Calvert-NYSSL** [comment]
#In models.py:

> from AppName import db
> from flask_login import UserMixin
> from sqlalchemy.orm import relationship
> from sqlalchemy.ext.mutable import Mutable
> 
> class User....
> 

#In AppName:

> from flask import Flask
> from flask_bootstrap import Bootstrap
> from flask_sqlalchemy import SQLAlchemy
> from flask_mail import Mail
> 
> app = Flask(name)
> app.config.from_pyfile('config.py')
> 
> Bootstrap(app)
> db = SQLAlchemy(app)
> mail = Mail(app)
> from views import *
> 
> if name == 'main':
> app.run(debug=True)

#In manage.py:

> from flask_script import Manager
> from flask_migrate import Migrate, MigrateCommand
> from models import db
> from AppName import app
> 
> migrate = Migrate(app, db)
> manager = Manager(app)
> manager.add_command('db', MigrateCommand)
> 
> if name == 'main':
> manager.run()
> 

#In config.py:

> import os
> from datetime import datetime
> 
> SECRET_KEY = 'secret key'
> SQLALCHEMY_DATABASE_URI = "this is the uri"
> 

Based on the knowledge that I have, the initialization is there. Did I miss something?

**Comment by miguelgrinberg** [comment]
You need to decide if you are going to use the `flask` command to run your application, or you are going to go with a legacy system such as Flask-Script. You are mixing up the two methods here, the code in `manage.py` never runs if you use `flask db ...`.

**Comment by Calvert-NYSSL** [comment]
#In models.py:

> from AppName import db
> from flask_login import UserMixin
> from sqlalchemy.orm import relationship
> from sqlalchemy.ext.mutable import Mutable
>
> **from flask_script import Manager**
> **from NYSSLPMS import app**
> **from flask_migrate import Migrate**
> 
> **migrate = Migrate(app, db)**
> 
> class User....
> 
> **if __name__ == '__main__':**
>     **manager.run()**

#In AppName:

> from flask import Flask
> from flask_bootstrap import Bootstrap
> from flask_sqlalchemy import SQLAlchemy
> from flask_mail import Mail
> 
> app = Flask(name)
> app.config.from_pyfile('config.py')
> 
> Bootstrap(app)
> db = SQLAlchemy(app)
> mail = Mail(app)
> from views import *
> 
> if name == 'main':
> app.run(debug=True)


#In config.py:

> import os
> from datetime import datetime
> 
> SECRET_KEY = 'secret key'
> SQLALCHEMY_DATABASE_URI = "this is the uri"

I added a portion of the code from the manage.py to the model.py and it is showed in bold. Then, I removed the manage.py since it is redundant to have it for my case.  I am guessing this is the legacy system way after reading your blog and the docs. 

After doing so, I managed to run flask fb history and see the history. I ran `python models.py db migrate` and I get an error saying the User table already exist.

```
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'user' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```
Can I say that the migrate is starting to work? I don't get these two lines though after running the migrate command.

```
INFO [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO [alembic.runtime.migration] Will assume transactional DDL.
```

**Comment by miguelgrinberg** [comment]
As I said above, you really need to invest some time and familiarize with the ways of starting a flask application. I suggest you stick to the `flask` command for everything, and remove the legacy Flask-Script things.

**Comment by Calvert-NYSSL** [comment]
#In models.py:

```
from AppName import db
from flask_login import UserMixin
from sqlalchemy.orm import relationship
from sqlalchemy.ext.mutable import Mutable

from AppName import app
from flask_migrate import Migrate

migrate = Migrate(app, db)

class User....
```


#In AppName:

```
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail

app = Flask(name)
app.config.from_pyfile('config.py')

Bootstrap(app)
db = SQLAlchemy(app)
mail = Mail(app)
from views import *

if __name__ == 'main':
app.run(debug=True)
```

#In config.py:

```
import os
from datetime import datetime

SECRET_KEY = 'secret key'
SQLALCHEMY_DATABASE_URI = "this is the uri"
```

I ran many testings  and this is what I have for now.  Legacy stuff should not be here anymore. I ran `flask db init` and I get this message which is great.
`Error: Directory migrations already exists`

I ran `flask db migrate`, showed me the two same messages lines but it is still not detecting new table.

**Comment by Calvert-NYSSL** [comment]
I am wondering if the importing order is causing the problem too. I am doing the testings now but strange thing is the migration works on my co-worker laptop.

**Comment by miguelgrinberg** [comment]
It's impossible for me to know. At this point you appear to have everything well configured. Do you have any differences that need to be captured in a migration? If your database is identical to your models then there will be no migration file generated.

**Comment by Calvert-NYSSL** [comment]
Not identical. I added a large table to the models.py but still the migration is not detecting the new table.  I tested it by removing a table from models.py too but it is not migrating. Is there a way to confirm that it is reading the correct models.py?

**Comment by miguelgrinberg** [comment]
> Is there a way to confirm that it is reading the correct models.py?

Add an intentional syntax error to your model. If the `flask db migrate` command works anyway, that is proof that the model isn't being imported.

**Comment by Calvert-NYSSL** [comment]
That is a great way to test, should have thought of that. After adding the intentional syntax error, it tells me where the error is in the code and it is accurate. I tried messing with the existing models by adding and deleting a table entry but it still wouldn't detect the changes.  Is this the proof of the model not being imported?

**Comment by miguelgrinberg** [comment]
Well, the models are being imported if you get the syntax error, but something must be wrong. Some people make the mistake of initializing a separate `SQLAlchemy` object for Flask-Migrate, while the models are attached to the main one. No idea if that is your case, but my guess is that there is some type of mistake like that in your application. If you have your application available on GitHub or similar I can take a look, if not I can't really know.

**Comment by Calvert-NYSSL** [comment]
I need to ask permission from my boss about that because I am just an intern.  Meanwhile, I will try out the tutorial in your blog to see if I have the migration issue by starting a new project. Also, today I tested the changes that I made and shown here in this forum on my colleague's Mac and it works perfectly. I hope it is not a "works on others people laptop"  issue though.

**Comment by Calvert-NYSSL** [comment]
I tried importing the project to a company laptop, added something to the models.py and ran the migration. It works perfectly on that company laptop. There must be something wrong in the environment of my own laptop specifically to that web app because I started a new project from your blog and the migration works on my own laptop. 

At this point, I may or may not continue to solve the issue on my laptop and whenever I want to make changes to the models I will do it on the company's laptop or maybe I will not use my laptop for that project. Thank you for sharing your knowledge. I learnt one thing among all things from you and that is the existence of the legacy flask-script thing.

**Comment by cancan101** [comment]
I am also seeing something similar where I just get those lines but nothing else (error or success). this happens even when running `flask db current`.

**Comment by cancan101** [comment]
my issue was cauesd by there being two heads in the history without a merge.

**Comment by cancan101** [comment]
https://github.com/miguelgrinberg/Flask-Migrate/commit/2dd45d0037cb62bc7a8a981f0de70071b891a2ff#r30781562

**Comment by miguelgrinberg** [comment]
I'm closing this issue due to being inactive for too long and being unclear on whether this is still a problem. Feel free to reopen if necessary.

**Comment by amrit-instamojo** [comment]
Same Issue, if using local db not getting any Error but after using Heroku db getting above error.

**Comment by nbaryshev** [comment]
Considering the original problem in this topic: check if you are in your Project folder where wsgi.py stores, not app folder (to return one level back use "cd .." command in your terminal). Then try this command once again
