### ISSUE TITLE
Unable to Migrate tables with opposing FK

### ISSUE THREAD

**Issue by thenetimp** [miguelgrinberg/Flask-Migrate#226]
I have 2 models.  One called Account and one called AccountCard.

AccountCard has a FK of account_id linking Account.id
Account has and FK of primary_card linking AccountCard.id

Trying to migrate this fails.  I suspect it is because Flask Migrate builds the table then builds the foreign key, when it should build all the tables (including the fields that are foreign keys), then go back and link all the foreign keys for the tables it just created.

I am moving an application from php to python.  I have created a huge models.py file with models for all of the tables.  I have all the models in alphabetical order, but because Flask Migrate builds all the FKS as it builds the tables, I am now going to have to go through the file and move all the tables around so the migrations don't complain about the table and column not existing yet.

**Comment by thenetimp** [comment]
I worked around this by removing all FK creation in the migration file, running the migration and then creating a 2nd migration that had all the FK in it.

**Comment by miguelgrinberg** [comment]
Glad you figured it out on your own. It is not uncommon to have to make some edits to generated migrations to make things work. Just FYI, keep in mind that Flask-Migrate is a Flask friendly wrapper for Alembic, which is the package where migrations are generated and applied, so you would probably get better help if you ask in the Alembic community.

**Comment by thenetimp** [comment]
Didn't realize it was a wrapper, I am fairly new to Python/Flask.  I'll close this and go post a bug report to Alembic then, and see what their response is.  Thanks.

**Comment by mcauto** [comment]
same here.. Is it fixed?

**Comment by thenetimp** [comment]
mcauto, there is no fix.  You need to edit the migration file and put all the foreign key creations at the bottom, or put into a separate migration file.
