### ISSUE TITLE
Support for TypeDecorator

### ISSUE THREAD

**Issue by sloria** [miguelgrinberg/Flask-Migrate#23]
I currently have a TypeDecorator defined like so:

```python
# in myapp/database.py
class BcryptType(TypeDecorator):
    """Coerce strings to bcrypted Password objects for the database.
    """
    impl = db.String(128)

    def process_bind_param(self, value, dialect):
        return Password(value, crypt=True)

    def process_result_value(self, value, dialect):
        # already crypted, so don't crypt again
        return Password(value, crypt=False)
```

Then when I generate a migration, I get

```python
# in the migration script
def upgrade():
    #...
    sa.Column('password', sa.BcryptType(), nullable=True),
```

This, of course, fails because there is no `sqlalchemy.BcryptType`. It would be nice if Flask-Migrate knew to use the TypeDecorators `impl` when generating the migration.

**Comment by miguelgrinberg** [comment]
Flask-Migrate does not generate migrations directly, it just wraps Alembic. You can request this feature here: https://bitbucket.org/zzzeek/alembic
