### ISSUE TITLE
Help on using flask migrate with blueprints

### ISSUE THREAD

**Issue by akhilputhiry** [miguelgrinberg/Flask-Migrate#231]
I have different blueprints and every blueprint have `models.py` inside them. With in the app factory I am initialising the db with

```
def create_app():

    app = Flask(__name__)

    app.register_blueprint(one)
    app.register_blueprint(two)

    db_from_blue_print_1.init_app(app)
    db_from_blue_print_2.init_app(app)
```

How can I use flask migrate in this case.

**Comment by miguelgrinberg** [comment]
Flask-Migrate does not care about blueprints, it needs to be initialized on the application.

**Comment by akhilputhiry** [comment]
Thank you @miguelgrinberg

**Comment by simanacci** [comment]
What are the implications of initializing some stuff in the app factory and flask-migrate separately on the application?

**Comment by miguelgrinberg** [comment]
@simanacci what do you mean by "separately on the application"?

**Comment by simanacci** [comment]
Doing this for all

    def create_app():
        app = Flask(__name__)
        app.config.from_object('config.DevelopmentConfig')

        from .core.db import db
        db.init_app(app)

        from .core.csrf import csrf
        csrf.init_app(app)

versus what's shown below for flask-migrate when using blueprints.


     app = create_app()
     db = SQLAlchemy(app)

     from app.home.models import *

     migrate = Migrate(app, db)

     if __name__ == '__main__':
         app.run(host='0.0.0.0', debug=True)

**Comment by miguelgrinberg** [comment]
It works either way. No difference.

Flask-Migrate is an extension that is not needed when you are actually running the application, it's only used when you run a `flask db` command. For that reason you do not need to have it initialized along with the application, you can just enable it for CLI use.

**Comment by onlinepresident** [comment]
@miguelgrinberg 
Thanks for your support to the Flask community.

Can you please do a short video to explain how to do migration when the application is "Blueprint" structured.

My application runs fine without any error. When I run "flask db migrate", only a model in one blueprint gets migrated.

**Comment by miguelgrinberg** [comment]
@onlinepresident make sure all your models are imported. If you don't import your models, then Flask-Migrate and Alembic will not know about them.

**Comment by onlinepresident** [comment]
> @onlinepresident make sure all your models are imported. If you don't import your models, then Flask-Migrate and Alembic will not know about them.

This is how I imported the models from the different blueprints, into the main __init__.py
`def register_blueprints(app):
    for module_name in ('auth', ' main'):
        module = import_module('apps.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)`

What do I need to do again, please?

**Comment by miguelgrinberg** [comment]
@onlinepresident Let's do this. If you think this is a bug in Flask-Migrate, then create a small, self-contained application that shows the problem and I'll investigate. Unfortunately I cannot debug your application for you, I have zero context.

**Comment by onlinepresident** [comment]
> @onlinepresident Let's do this. If you think this is a bug in Flask-Migrate, then create a small, self-contained application that shows the problem and I'll investigate. Unfortunately I cannot debug your application for you, I have zero context.

No, not at all. I don't think its a bug.
I feel I'm just not doing something right based on how I structured my application... I will keep investigating. Thanks for your time and  your support to the community.

**Comment by mario-bros** [comment]
@miguelgrinberg , i just having similar issues with blueprint integration. But then i add @app.shell_context_processor so my models can be recognized with `flask db` command. Why don't you mention this ? Thanks

**Comment by miguelgrinberg** [comment]
@mario-bros I don't understand the relation between a shell context processor and the issues described here. Flask-Migrate worked indirectly for you, because you imported all the models for the shell. I mentioned above that as long as you import all the models (for any reason, not necessarily for shell context use) then everything should work.

**Comment by vintello** [comment]
maybe it will be useful for someone else
add import your model in module "auth/__init.py" and it may worked

`from app.auth .models import Users`
