### ISSUE TITLE
flask-migrate commands result in no action at all

### ISSUE THREAD

**Issue by jpotwor** [miguelgrinberg/Flask-Migrate#232]
I am trying to start using migrations for an existing project. I created a file migrate.py, which looks this:

```
from flask_script import Manager
from flask_migrate import MigrateCommand, Migrate
from dream_app import app, db

app.config.from_pyfile('config.py')
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


if __name__ == 'main':
    manager.run()
```

then when I run:

`python migrate.py db init`

I get no output and no action, even the migrations folder is not created. Unfortunately this is an application running on python 2.7.12. The application is a big one and I would like to avoid switching to python3 at the moment. Could this be the reason? I use Flask-Migrate 2.2.1 and Flask-Script 2.0.6

**Comment by jpotwor** [comment]
It looks like I resolved the problem - I startet using the command
`flask db init`
and it works

**Comment by sollyucko** [comment]
Could you mark this as closed?
