### ISSUE TITLE
stuck: cannot migrate, upgrade or downgrade etc

### ISSUE THREAD

**Issue by aherzfeld** [miguelgrinberg/Flask-Migrate#233]
After making a minor change to my models (added last_seen column), running flask db migrate was not working. After some googling I found a couple people who said deleting the alembic_version table from their db helped, so I tried that. 

It didn't work, and now when I try to run **flask db migrate** I receive the following:

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [alembic.env] Target database is not up to date.

When I try **flask db upgrade** I receiving the following error:

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "user" already exists
 [SQL: '\nCREATE TABLE "user" (\n\tid SERIAL NOT NULL, \n\tusername VARCHAR(40), \n\temail VARCHAR(120), \n\tpassword_hash VARCHAR(128), \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)

I've also tried upgrading / downgrading to specific versions , but also receive errors.

When I try to run **flask db current** I receive no info like so:

$ flask db current
....../__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.

My guess is that it has to do with the fact that I dropped the alembic_version table. 

I couuuuuuld drop my db and start fresh as I'm in development, but if there is another fix that would be ideal . 

Cheers,

**Comment by miguelgrinberg** [comment]
You should not have dropped the alembic_version table without understand why you do it. That helps with some types of problems, definitely hurts in your case.

So let's restore your alembic_version first. Start by making a back up of your `migrations` directory and all its subdirectories. Just in case.

Type "flask db history" and look at the top-most migration(s). Make sure the top migration is the last known good migration that was successfully applied to the database. If you see one or more migrations at the top of the list that are not applied to the database yet, then go into the `migrations/versions` directory and delete those migration files. Then type `flask db history` again and make sure all the migrations that you see were successful and are already in your database.

Now type `flask db stamp head` to recreate the alembic_version table.

Then try running `flask db migrate` to generate the migration that gave you trouble, and show me the output. The only thing you said about this is that "it was not working", which is not enough information for me to help you.

**Comment by aherzfeld** [comment]
Thank you very much for that help so far. 

It seems like it worked, in successfully creating the migration version file:

`$ flask db migrate
/Users/appleuser/Box Sync/Personal/coding/projects/mealbot/venv/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.ddl.postgresql] Detected sequence named 'user_id_seq' as owned by integer column 'user(id)', assuming SERIAL and omitting
INFO  [alembic.autogenerate.compare] Detected added unique constraint 'None' on '['title']'
INFO  [alembic.autogenerate.compare] Detected added column 'user.last_seen'
  Generating /............./migrations/versions/241d40abc6ae_.py ... done`

And I just ran `flask db upgrade` and it all seems to have worked as well. 

Thank you so much for the help Miguel! I had scoured through the commands in the flask-migrate documentation , but what `flask db stamp` does must have slipped passed me. 

I'm working on this personal project largely applying concepts learned in your Flask-Mega Tutorial, which was great. Thanks for your contributions to the community!

**Comment by wildoctopus** [comment]
Getting this error while runing flask db migrate
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "idx_indian_geo" already exist

I exactly dont know whats the error. 

Below is my model file - 

class Indian(BaseModel):
  """Airports with its geospatial data."""

  __tablename__="indian"

  name  = db.Column(db.String(255))
  longitude = db.Column(db.Float)
  latitude = db.Column(db.Float)
  geo = db.Column(Geometry(geometry_type="POINT"))

  def __repr__(self):
    return "<Airport {name} ({lat}, {lon})>".format(name=self.name, lat=self.latitude, lon=self.longitude)


Please suggest what can be the error. I dropped and reacted my database as well and ran "flask db init, flask db migrate, again. But while executing flask db upgrade it gives error.

**Comment by miguelgrinberg** [comment]
@wildoctopus this means that your latest migration is trying to create an index that already exists in your database. There is no single fix for this, you have to figure out why the migration is trying to create an index that was already created. At some point your database went out of sync with your models.
