### ISSUE TITLE
flask-migrate + gunicorn

### ISSUE THREAD

**Issue by irmscher9** [miguelgrinberg/Flask-Migrate#239]
Did anyone test it with gunicorn? Seems causing issues..

**Comment by miguelgrinberg** [comment]
Gunicorn is a web server, it has nothing to do with flask-migrate. What issues are you seeing?

**Comment by irmscher9** [comment]
Tanks for prompt reply, Miguel. Yes, I know that gunicorn is a server. Somehow I'm having hard times to deploy the app on gunicorn with the flask-migrate installed. I need to run a few more tests to make sure.

**Comment by irmscher9** [comment]
OK, so it was some weird issue with gunicorn when running 'docker run' 
Something like this: `docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"gunicorn\": executable file not found in $PATH".`
It wasn't because of the Flask-Migrate module.
Anyways, I've fixed it by pre-installing gunicorn with pip before building a docker image. :)

**Comment by miguelgrinberg** [comment]
Awesome, glad you figured it out.
