### ISSUE TITLE
Change from Integer to String not detected.

### ISSUE THREAD

**Issue by playpianolikewoah** [miguelgrinberg/Flask-Migrate#24]
I have a column:
`code = db.Column(db.Integer(unsigned=True,zerofill=True))`
And when I change that column from `Integer` to `String` like so: 
`code = db.Column(db.String())`
And I run:
`python manage.py db migrate`
the migration does not detect any changes. 
Should it not detect at least a change in the column data type?
Migration looks like this after:

	def upgrade():
	    ### commands auto generated by Alembic - please adjust! ###
	    pass
	    ### end Alembic commands ###

	def downgrade():
	    ### commands auto generated by Alembic - please adjust! ###
	    pass
	    ### end Alembic commands ###

**Comment by unionx** [comment]
@davedg629 I add the compare_type args in my env.py, which is created after I ran the init command, but it still did not work. When I was using alembic directly, changing the compare_type arg worked.

**Comment by miguelgrinberg** [comment]
You can now add `compare_type=True` in the `Migrate` constructor.

**Comment by atomicwrites** [comment]
One more note for posterity, SQLite does not support changing the type of a column. Period. You will always get syntax errors.

**Comment by alsmith808** [comment]
Thanks atomicwrites.  So the manual approach is best then i gather.

**Comment by atomicwrites** [comment]
Well if you're using SQLite you can't change the type of a column wether or not you use alembic. It's a limitation of SQLite (thing like this are where the "lite" comes in). You have to either make a new column or jugle with copying into a new table.
