### ISSUE TITLE
Tutorial sections 4.5+ -  No Changes in Schema detected (Solution?)

### ISSUE THREAD

**Issue by JeanNiBee** [miguelgrinberg/Flask-Migrate#242]
Hi

For the command line examples in Section 4.5 - 4.9 to work. Namely the "flask db migrate -m "users table" and subsequent upgrades.

You need the import statements seen in the Shell Context example for Ex 4.10.

As stated in other issues / posts the Model and the DB aren't imported to be seen by the Flask db modules, once you add this, problem solved.

Maybe the tutorial needs an amendment?

Ex:
Compared my 4.5 code base vs the Microblog "source" repo seen here.

``` shell
(microblog_venv) ╭─jrock@ritchie ~/git
╰─$ diff --ignore-all-space ./microblog_source/microblog.py ./jrock/microblog/microblog.py                                                                                      1 ↵
1,7c1,2
< from app import app, db
< from app.models import User, Post
<
<
< @app.shell_context_processor
< def make_shell_context():
<     return {'db': db, 'User': User, 'Post': Post}
---
> # From our module import that app 'file'
> from app import app
\ No newline at end of file
(microblog_venv) ╭─jrock@ritchie ~/git
╰─$                                                                               
```

**Comment by miguelgrinberg** [comment]
I believe you are wrong. The models are imported in `app/__init__.py`. See https://github.com/miguelgrinberg/microblog/blob/32d2eceeb4260b956129a5701271777d55531f11/app/__init__.py#L11.

**Comment by JeanNiBee** [comment]
I will give that a check, maybe I left that out and never realized on
verification.

Thanks for crazy fast reply.

Happy Holidays

-
John
