### ISSUE TITLE
how to disabled param binding ?

### ISSUE THREAD

**Issue by Dog-Lee** [miguelgrinberg/Flask-Migrate#243]
i have the version py like this:

```python
from alembic import op
op.execute('''
        INSERT INTO my_table VALUES ('{\"Global Private Network\":true,\"}');
'''))

```

and i got the error :
```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'true'
```

obviously :true is not a param, so how to pass alembic params binding ?

**Comment by Dog-Lee** [comment]
where i using
```python
op.get_bind().execute('''
             INSERT INTO my_table VALUES ('{\"Global Private Network\":true,\",\"Over 99.99% Availaiblity\":true}');
''')
```

op.get_bind() can pass param binding, but i get another error。
```
sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) not enough arguments for format string
```

**Comment by miguelgrinberg** [comment]
You are asking in the wrong place, this is just a wrapper for Alembic, I do not deal with operations. See the documentation for Alembic, or ask there if that does not help: https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.execute
