### ISSUE TITLE
os.mkdir has no permission when initializing Flask-Migrate

### ISSUE THREAD

**Issue by majaldm** [miguelgrinberg/Flask-Migrate#246]
I'm following the Flask Mega-Tutorial (https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database), but instead of using venv **I'm using an environment created with miniconda**, `FLASK_APP` is set to `microblog.py` and the system os is Linux Debian.
When I try to initialize the migration repo using `flask db init` I get a permission error:
```
  Creating directory /home/maja/projects/flask/microblog-0.4/migrations ... FAILED
Traceback (most recent call last):
  File "/home/maja/.conda/envs/flask/bin/flask", line 11, in <module>
    sys.exit(main())
  [...]
  File "/home/maja/.conda/envs/flask/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'migrations'
```
I realized the directory was owned by root instead then by my user, after changing ownership everything works fine.
`sudo chown maja ~/projects/flask/fallback/microblog-0.4/`

**Comment by miguelgrinberg** [comment]
This is actually working correctly, since you should always be creating the migrations in a place where the current user has write permission.

**Comment by majaldm** [comment]
Indeed, for some reason a directory in my home was owned by the root user, it was a mistake on my part.

**Comment by GO-Shoderu** [comment]
@majaldm you just saved me ... it works ... thanks
