### ISSUE TITLE
Assigning current revision via API to a variable

### ISSUE THREAD

**Issue by muckngrind4** [miguelgrinberg/Flask-Migrate#247]
I'd like to get the current revision via the API and use it for further logic.  It seems when I call current() it outputs to stdout and I can't assign the output to a variable.  I'm likely doing something wrong, but I can't figure out what.  Here is a sample:
```python
from flask_migrate import current
from ui import app

with app.app_context():
    v = current(directory="/path/to/migrations/")
    print(v)
```

The output I get is:
```
c40025995a97
None
```
The first line is the output from the current() call and the second is the variable (v).  My hope was that 'c40025995a97' would have been assigned to v.  Am I doing something wrong, or is this the expected behavior?

Thanks,
Derek

**Comment by miguelgrinberg** [comment]
Unfortunately Alembic does not have a high-level command that returns the current revision, all it does is print it to the console, which is the behavior that I'm invoking in Alembic through the `current()` function.

To get the revision programmatically you will need to use the Alembic APIs directly, or else run `flask db current` as a sub-process and capture the output into a variable.

**Comment by muckngrind4** [comment]
OK.  Thank you for the quick response.  And thank you for this package and your tutorials.  They've are extremely valuable!
