### ISSUE TITLE
Add commands to flask_migrate cli

### ISSUE THREAD

**Issue by LionelR** [miguelgrinberg/Flask-Migrate#249]
Is there a way to add more commands to flask_migrate cli? I tried with this code but nothing is added :-(

```python
from flask.cli import with_appcontext
from flask_migrate.cli import db
import models

@db.command('create')
@with_appcontext
def create_db():
    """
    Initialize the database (should be runs once)
    """
    print("Creating Tables...")
    models.db.create_all(app=current_app)
```

**Comment by miguelgrinberg** [comment]
I don't know, I would think what you did should work, but I never tried something like this. Are you sure your module is getting imported? If you don't import the module, then click will never register your command.

**Comment by LionelR** [comment]
Yes the module is imported at startup as previously the `create_db` method was defined as a click.command. For readability, I want to merge all db related commands as `db` sub-commands.

**Comment by miguelgrinberg** [comment]
Okay yeah, I can confirm that it does not work for me either. My guess is that because your custom command is imported first, Flask's CLI then overrides it fully with the commands that come from the extension.

**Comment by LionelR** [comment]
Playing with the imports order changes nothing. Well, I have to create another group. 
BTW, thanks for the help and for your work

**Comment by miguelgrinberg** [comment]
@LionelR As a side note, why do you prefer `db.create_all()` to `flask db upgrade` to create your tables? What I've seen when people bypass the migrations when creating the tables is that eventually broken migrations creep into the repository and they are not discovered for a long time, since they are not always used. What I always recommend people is to use the migration repository to create your tables. And if you have a lot of migrations and the `upgrade` command becomes too slow, then once in a while collapsing all migrations is a good idea.

**Comment by LionelR** [comment]
Yes I'm agree with you it's not a good idea to use `create_all()`, as I can see on production servers with multiple versions to upgrade to a unique version :-p
However, my code is just for testing, in fact I want to add some seeding (fixtures) capabilities after database creation/upgrade

**Comment by LionelR** [comment]
After digging into your code I found that 'db' is defined in the setup.py file by the `flask.commands` key of the `entry_points` parameter of the setup.
It seems that it's not possible to append commands to `db` if the module defining the commands is not called in another entry in the `flask.commands` key. As of now, my extras sub-commands are appended to the `db` command.

**Comment by miguelgrinberg** [comment]
@LionelR right, the commands that are defined as entry points appear to completely override anything custom you define within your app. You can define your own entry point to override mine if you want, and then pass-through all the sub-commands that you want the extension to handle.

This seems like a very unusual thing to do, so I don't think I'm going to look into ways to hacking the Click support in Flask to combine custom commands.

**Comment by LionelR** [comment]
I don't override your entry point, I extend it and I append another command group :
```python
import click
from flask import current_app
from flask.cli import with_appcontext
from flask_migrate.cli import db
from my_app.db import fixtures

@db.command()
@with_appcontext
def seed():
    """
    Insert datas in tables.
    """
    print("Seeding database...")
    fixtures.insert_fixtures(app=current_app)

@click.group()
def info():
    """
    Show informations.
    """
    pass

@info.command()
@with_appcontext
def config():
    """
    Show current app configuration.
    """
    for k, v in current_app.config.items():
        print("%s: %s" % (k, v))
```

If I add the `info`  command group with `app.cli.add_command(info)`, the `seed` db sub-command is not added, I have to create an entry point and the `seed` will appear:
```python
entry_points={
        'flask.commands': [
            'info=my_app.commands:info',
        ],
```
