### ISSUE TITLE
Set directory of database with sqlite

### ISSUE THREAD

**Issue by charliecrouse** [miguelgrinberg/Flask-Migrate#250]
flask is creating the database file in the /app  (/app/dev.db) directory while flask db migrate is creating the database file in the root directory of the project (/dev.db). Is there any way to handle this?

My current project structure is as follows:

- /
    - /config
        - development.cfg // SQLALCHEMY_DATABASE_URI is set here to 'sqlite:///dev.db'
    - /app
        - \_\_init\_\_.py   // reads in config file and Migrate(app, db) is called here
        - db.py // exports the db
        - dev.db // `db.create_all()` called in `flask shell` creates database file here
    - /migrations  // `flask db init` creates this folder here
    - dev.db  // `flask db migrate` creates database file here

Ideally flask would create the db in the same place as flask migrate.

Thanks in advance!

**Comment by miguelgrinberg** [comment]
You are using a relative path in your database URL. Change it to an absolute path and then the database will always be in the same place. Example of how to use absolute path: https://github.com/miguelgrinberg/microblog/blob/master/config.py#L10-L11

**Comment by charliecrouse** [comment]
Thanks, Miguel
