### ISSUE TITLE
Using migrate with docker and external database

### ISSUE THREAD

**Issue by johnroper100** [miguelgrinberg/Flask-Migrate#251]
I am running my flask app on DigitalOcean using Docker. The app is self-contained inside the Docker container, but the database is in a folder on the host and is linked to the container using the Docker command:

`--mount type=bind,source="$(pwd)"/mnt/volume_nyc1_01,target=/mnt/volume_nyc1_01 johnroper100/myapp:latest`

How can I use flask migrate when the database is outside of the container that the app is in?

**Comment by miguelgrinberg** [comment]
Flask-Migrate uses SQLAlchemy's configuration to access the database. If your application can access the database, then Flask-Migrate will have access to.

**Comment by miguelgrinberg** [comment]
If your container has a start up script, you can add the `flask db upgrade` command to the script, so that every time the container starts the database is upgraded.

Or you can start a one-off container with your command, something like:

    docker run --rm <other-args> image:tag flask db upgrade

**Comment by johnroper100** [comment]
ok, thanks
