### ISSUE TITLE
Migrate doesn't create default value

### ISSUE THREAD

**Issue by omni-vi** [miguelgrinberg/Flask-Migrate#254]
Hi Miguel,

I just added the following line to my model.
`customerComment = db.Column(db.String(500), nullable=False, default="")`

The resulting line in my migration script is
`op.add_column('angebot', sa.Column('customerComment', sa.String(length=500), nullable=False))`

There is no default value, which leads to the following error:
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL [SQL: 'ALTER TABLE angebot ADD COLUMN "customerComment" VARCHAR(500) NOT NULL'] (Background on this error at: http://sqlalche.me/e/e3q8)`

Even stranger, I have a field 
`country = db.Column(db.String(2), nullable=False, default="DE")`
and the resulting script line is
`op.add_column('user', sa.Column('country', sa.String(length=2), nullable=False))`

Am I doing something wrong? Should I use a different default value?
Thanks for your work!

**Comment by miguelgrinberg** [comment]
The `default` value is something that is done at the SQLAlchemy level. If you want the database to insert the default value, use `server_default`.

**Comment by omni-vi** [comment]
Thank you.

**Comment by Kamranbarlas** [comment]
how to make it default and not use use server_default explicitly for each migration.

**Comment by miguelgrinberg** [comment]
@Kamranbarlas this is an Alembic question, not a Flask-Migrate question. If Alembic isn't preserving your `server_default` then it might be a bug, not sure.
