### ISSUE TITLE
How-to not drop tables which are not detected (defined) in models

### ISSUE THREAD

**Issue by XuejiaoZhang** [miguelgrinberg/Flask-Migrate#256]
**Background & Use Case:**
We have multiple tables in our existing database, and only several are used (defined) in Flask models.
If we use Flask-migrate to track database changes, the tables not detected in models would be 
dropped.

**Feature Request:**
I am wondering whether there is a simple way to not revise the tables which are not defined in models.

I would like to hear from you on this. Thank you.

**Comment by miguelgrinberg** [comment]
This has been asked and answered before: https://github.com/miguelgrinberg/Flask-Migrate/issues/129.
