### ISSUE TITLE
--sql option for migrate doesn't make sense

### ISSUE THREAD

**Issue by cancan101** [miguelgrinberg/Flask-Migrate#257]
```
$ flask db migrate --sql
```
yields:
```
Error: Using --sql with --autogenerate does not make any sense
```

**Comment by miguelgrinberg** [comment]
The error message comes from Alembic, and is correct. What are you trying to do?

**Comment by cancan101** [comment]
Why even offer this flag on that command in flask migrate ?

**Comment by miguelgrinberg** [comment]
The `migrate` command is a specialized version of the `revision` command, which does have a use for the `--sql` option. I did not realize this command is incompatible with auto-generation to be honest, I never use the raw sql options myself.

Is this such a big problem? It can be removed, I guess. Do you want to submit a PR for it?
