### ISSUE TITLE
Require a non-empty message for migration/version?

### ISSUE THREAD

**Issue by killthekitten** [miguelgrinberg/Flask-Migrate#259]
Empty migration names do not make sense. If no message provided, there's no way to find and open a recent migration except for `grep`ping or cmd+clicking the output of the migration command.

Would it be better if the `-m` option of `revision` and `migrate` would become required? Could it be a breaking change for anyone?

Every time I accidentally generate a migration without a message, I have to delete and regenerate it with `-m`, which is a distraction.

**Comment by miguelgrinberg** [comment]
You can write a description for your migration after it has been generated. Just add it to your migration script in the first line of the docstring. You can also rename the migration script if you like, but this isn't required.

Given that Alembic does not require descriptions, I prefer to work in the same way in this package.

**Comment by killthekitten** [comment]
Yes, the particular issue I have here is that I end up with a `e9b36b38c378_.py` file that I now have to manually rename.

To change this behavior at the moment I either have to fork `Flask-Migrate` or maintain a custom cli command within the project. Maybe, we could introduce a configuration for that?

**Comment by miguelgrinberg** [comment]
It is not necessary to rename your migration file. The name can be anything you want, it does not even need to include the SHA of the migration. What matters are the data that is stored inside the script. As long as you add your comments in the migration scripts, the `history` command will report them.

Not counting a couple of exceptions, I've tried to keep the commands in sync with those in Alembic. To me this sounds like something that should be implemented upstream. The ideal solution would be to have Alembic open up your text editor to ask you for the text, same as what `git commit` does. But I don't see this project as the proper place for such a feature.

**Comment by killthekitten** [comment]
History does not really matter here, the point of having a sane file name is to fuzzy-match it the way I do with other files in the project, i.e. `cmd+P` in `VSCode`. 

Since we chose `Flask-Migrate` as a front-end to `Alembic`, I expected it to simplify the basic routing. But I get your point and thank you for taking more time to explain it!
