### ISSUE TITLE
hello i want to trans the data from sqlite db to mysql db ,but there is a error

### ISSUE THREAD

**Issue by a108483** [miguelgrinberg/Flask-Migrate#260]
after i chang the url to "mysq//......."in the flask config,then i input the command "python run.py db migrate",the shell will output
"
 INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [root] Error: Target database is not up to date."

how to deal with it?

**Comment by miguelgrinberg** [comment]
Neither Flask-Migrate nor Alembic can move data from one database to another. You will need to do this with a different tool.

**Comment by a108483** [comment]
> Neither Flask-Migrate nor Alembic can move data from one database to another. You will need to do this with a different tool.

OK，thank you i have find another tools;;;;;;;;;and now i want to use cassandra database in the flask ,do you know where to find some docs??

**Comment by miguelgrinberg** [comment]
@a108483 I have no experience with Cassandra, so I cannot recommend a tool or documentation. There are a few Python packages, even Flask extensions, so you have some options.
