### ISSUE TITLE
No changes in schema detected.

### ISSUE THREAD

**Issue by dasani08** [miguelgrinberg/Flask-Migrate#266]
Hello @miguelgrinberg

Thanks for your package 👍 

I have some small troubles, I started my application with simple model as below:

```python
class Test(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(64))
```

Then everything works great until I am going to change the length of column ```name`` from 64 to 128

```python
class Test(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(128))
```

I run command ```flask db migrate``` again and there are no migration is generated. The console printed:  ```INFO  [alembic.env] No changes in schema detected.```

Did I make something wrong or misconfigured?

**Comment by miguelgrinberg** [comment]
This is in the Alembic domain, not this extension which just creates a wrapper for Flask. See https://github.com/miguelgrinberg/Flask-Migrate/issues/24 for a thread related to your situation.
