### ISSUE TITLE
flask db init Error: No such command "init"

### ISSUE THREAD

**Issue by alirezaimi** [miguelgrinberg/Flask-Migrate#271]
Hi
In factory pattern in flask i have this problem with flask-migrate api :
```
$ flask db init
Usage: flask db [OPTIONS] COMMAND [ARGS]...
Try "flask db --help" for help.

Error: No such command "init".

```
I explained it [here](https://stackoverflow.com/questions/56375353/problem-with-flask-migrate-api-and-flask-blurprint-and-app-factory) Where am it wrong ?!

**Comment by miguelgrinberg** [comment]
What's the output of `flask db --help`?

**Comment by alirezaimi** [comment]
@miguelgrinberg 
```
(venv) ali@alilap:~/git_proj/imiphonebook$ flask db --help
Usage: flask db [OPTIONS] COMMAND [ARGS]...

Options:
  -m, --model TEXT            Name of the module that contains the model
  -d, --db TEXT               SQLAlchemy instance name
  -e, --echo / -E, --no-echo  Overrides SQLALCHEMY_ECHO
  --help                      Show this message and exit.

Commands:
  reset

```

**Comment by miguelgrinberg** [comment]
You are using the flask-appconfig extension, which exposes a `flask db` command that collides with the one used by this extension. Because of the order you are initializing these extensions, the `flask db` command from flask-appconfig is shadowing the one from Flask-Migrate.

**Comment by alirezaimi** [comment]
that you very much ...
