### ISSUE TITLE
How can I set MySQLdb connection charset utf-8

### ISSUE THREAD

**Issue by zhenglq** [miguelgrinberg/Flask-Migrate#272]
I execute `flask db upgrade` , but exception:
>   File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 188, in execute
    query = query.encode(db.encoding)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 69-70: ordinal not in range(256)

I know this is charset problem. but I don't know where set. 
official doc too short

> @migrate.configure
def configure_alembic(config):
    # modify config object
    return config

I find solution
> SQLALCHEMY_DATABASE_URL = 'mysql://{user}@{pwd}@{host}/db?charset=utf8

But I want to konw Flask-Migrate config solution.
 thank you!

**Comment by miguelgrinberg** [comment]
Flask-Migrate uses the configuration from Flask-SQLAlchemy. This is probably an issue with the migration script or with data that is already in your database.
