### ISSUE TITLE
alembic.ini documentation for --multidb

### ISSUE THREAD

**Issue by mkortink** [miguelgrinberg/Flask-Migrate#273]
HI, my flask app uses 3 databases and i am using SQLAlchemy and Migrate. When i run

$ flask db init --multidb

it completes successfully but says I have to edit alembic.ini. When i look at alembic.ini it states it is a generic single database ini. I can't find any documentation on what to do to it. 

The end goal is to manage two of the databases (primary and one bind) with SQLAlchemy and one directly.

Mark

![Alembic](https://user-images.githubusercontent.com/27032470/59084579-17fe5680-893f-11e9-9c8a-b6e8aa8c5efc.PNG)

**Comment by miguelgrinberg** [comment]
The "please edit alembic.ini' message is a generic message that Alembic prints. Flask-Migrate provides an alembic.ini file that is appropriate for most use cases, including multiple databases. Only change it if something in there does not work for you.
