### ISSUE TITLE
AttributeError: module 'sqlalchemy' has no attribute 'Variant'

### ISSUE THREAD

**Issue by majinman** [miguelgrinberg/Flask-Migrate#274]
When executing 'python manage.py db upgrade'
I got error message, such as 'AttributeError: module 'sqlalchemy' has no attribute 'Variant''

I installed pip packages following 'https://flask-migrate.readthedocs.io/en/latest/'

Please help me.

**Comment by miguelgrinberg** [comment]
This package does not generate migrations, it uses Alembic for that.

If you want to address the problem easily, just add the missing import in your migration script.
