### ISSUE TITLE
[python3] from . import postgresql, mysql, sqlite, mssql, oracle  # pragma: no cover ImportError: cannot import name 'mysql'

### ISSUE THREAD

**Issue by henrytom1703** [miguelgrinberg/Flask-Migrate#275]
from . import postgresql, mysql, sqlite, mssql, oracle  # pragma: no cover
ImportError: cannot import name 'mysql'

**Comment by miguelgrinberg** [comment]
Why are you importing all these databases, and how is that related to this project?
