### ISSUE TITLE
How do I run flask migration on AWS RDS?

### ISSUE THREAD

**Issue by akbarsha03** [miguelgrinberg/Flask-Migrate#277]
I've my running on AWS Elastic Beanstalk with EC2. I used the AWS CodeCommit to deploy my changes. How do I run migrations script on remote? Do I have to SSH into the EC2 to run the `flask db upgrade` command? or Is there any other way I can do like execute the Migrations script directly through `flask-migrate`? If yes, How can I run `flask db upgrade` sort of execution from my `.py` file

Thanks in advance. I'm very new to AWS and Flask

**Comment by miguelgrinberg** [comment]
You can run flask-migrate from anywhere. The only requirement is that the database URL that you have configured for Flask-SQLAlchemy is valid. If you want to run your migrations from your own computer just make sure you can connect to your database and then flask-migrate should not care.
