### ISSUE TITLE
"flask db upgrade" does not give error, but does not upgrade db successfully

### ISSUE THREAD

**Issue by aaeissa** [miguelgrinberg/Flask-Migrate#281]
Issue: 
Using the commands `flask db migrate` and `flask db upgrade` does not appear to successfully update the database.

Project: 
Flask app (essentially modeled off of the mega-tutorial, using application factory); MySQL; Ubuntu

Description:
In my `models.py` file I declared a column/field with `org_name = db.Column(db.String(240), index=True, nullable=True)`. When adding data to my database (I used `flask db init` before), the 240 length restraint for this field was too small. 

I made the change in `models.py` to `db.Text` to allow for more room. I then ran `flask db migrate` and `flask db upgrade`; the revision scripts were generated without an explicit error.  

I re-ran my data ingestion/collection script, which populated my DB, and got the same error ("Data too long for column "myColumn"..) indicating the change to the column from String(240) --> Text was not successful.  

I checked the latest script generated by flask-migrate:

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_MYTABLE_myColumn', table_name='MYTABLE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_MYTABLE_myColumn', 'MYTABLE', ['myColumn'], unique=False)
    # ### end Alembic commands ###
```

Looking at this script, it seems flask-migrate only accounted for me removing `index=True` and not the change from String(240) --> Text.  

Any ideas why this may be? As of now this is preventing me from successfully using the tool.

**Comment by miguelgrinberg** [comment]
Yes, this is a bit odd, but expected. The Alembic package, which handles the actual migration work, does not recognize type changes in columns by default. If you want that fine level of detection you need to enable the `compare_type` option:

```python
migrate = Migrate(app, db, compare_type=True)
```

**Comment by aaeissa** [comment]
Thank you @miguelgrinberg . I'm not sure how I didn't come across that in my searches, but it seems I may have just missed a few keywords in my queries. I've added: 

```python
migrate = Migrate(compare_type=True)

def create_app():
    ...
    migrate.init_app(app, db)
``` 

to the __init__.py file as well as the `compare_type=True` option to the `env.py` file in the `migrations` directory but the behavior hasn't changed.

**Comment by miguelgrinberg** [comment]
Did you re-generate your migration script? The `flask db migrate` command is the one that changes its behavior with this option, not the `flask db upgrade`.

**Comment by aaeissa** [comment]
Yes, I ran through the following: `rm -rf migrations/`; deleted and re-created db in mysql; ran through flask db init/migrate/upgrade with the initial `models.py`; made the change from db.String(240) to db.Text and ran through flask db migrate/upgrade again, which gave the same behavior I mentioned

**Comment by miguelgrinberg** [comment]
@aaeissa I really don't know then. This is all stuff that's happening at the Alembic level, this package doesn't do any of this, so I'm really out of ideas. The `compare_type=True` option is what I have used and always recommended.

**Comment by aaeissa** [comment]
No problem -  I appreciate the help and ideas so far!

**Comment by EzzEddin** [comment]
> Yes, this is a bit odd, but expected. The Alembic package, which handles the actual migration work, does not recognize type changes in columns by default. If you want that fine level of detection you need to enable the `compare_type` option:
> 
> ```python
> migrate = Migrate(app, db, compare_type=True)
> ```

Thanks, @miguelgrinberg! That really helps.

If someone comes across this kind of error, make sure to just do `flask db migrate` to trigger the configs changes and then `flask db upgrade` to reflect that change on the database.

**Comment by ajharris** [comment]
I think I have this figured out: the migrate and upgrade commands work for me right up until I checkout a different commit from git, then it stops seeing changes made to any of the db.Model classes. I tried adding the migrations/ folder to the .gitignore and doing a checkout, but the .gitignore is tracked by git and my edit to the .gitignore gets reset when I checkout again.
