### ISSUE TITLE
I get this error any time I run flask db migrate

### ISSUE THREAD

**Issue by SarpongAbasimi** [miguelgrinberg/Flask-Migrate#283]
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)

```

I have tried everything I can, but it doesn't seem to work

**Comment by miguelgrinberg** [comment]
The error is:

    sqlite3.OperationalError: unable to open database file

It means that the database connection URI that you are using is probably incorrect, or if the URI is correct then the actual database file is maybe owned by another user and the user you are running on does not have permission to open it.

**Comment by SarpongAbasimi** [comment]
Thanks Miguel, I am sure that the database connection URI is correct because I can add users to the database. 

<img width="1279" alt="Screen Shot 2019-07-20 at 10 01 18" src="https://user-images.githubusercontent.com/37377831/61576747-9240ff80-aad5-11e9-9614-c814a30bab73.png">

And I am the owner of the database file but anyways, I will play around with it to see if I can fix it.

**Comment by miguelgrinberg** [comment]
Okay, then you have to look for possible ways in which Flask-Migrate and Alembic can be seeing a different database URI than your Flask app.
