### ISSUE TITLE
Fix mixed-content on documentation site

### ISSUE THREAD

**Issue by FranklinYu** [miguelgrinberg/Flask-Migrate#286]
The only thing that seems related is

https://github.com/miguelgrinberg/Flask-Migrate/blob/4a180b711bf87572617a0b7caad0a7151f53fde7/docs/_themes/flask_small/layout.html#L18

Simply replace `http` with `https` here. Too small to justify a fork…

**Comment by miguelgrinberg** [comment]
The docs should be migrated to the alabaster theme of sphinx, the current template I'm using is actually the same source on which alabaster is based.
