### ISSUE TITLE
Tests invoke 'python'

### ISSUE THREAD

**Issue by jayvdb** [miguelgrinberg/Flask-Migrate#289]
The tests should use `sys.executable` to get the correct version, as `python` could be a different version.  Also `python` wont exist on many distros when python2 stops providing exe `python`.  Python 3 is usually at `python3` on distro machines.

**Comment by miguelgrinberg** [comment]
Do you have a specific platform or set up in which this does not work? As long as tests run in a virtual environment, `python` is always going to work.

**Comment by jayvdb** [comment]
The tests are also run by distros to validate the rpms/debs they produce, and they do not use virtualenv, because they are validating that the software works on versions of the dependencies that they have in their OS - not the versions the developers for each package choose.

In my case, the cause is setting up python3 only builds
https://build.opensuse.org/request/show/730894
