### ISSUE TITLE
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by shivarajalagond** [miguelgrinberg/Flask-Migrate#291]
What I am trying to do here is,
1. Add a column to the existing table that has constraints
2. Try to delete the recently added column 

I am using flask-sqlalchemy for SQLite
[https://github.com/bstinsonmhk/duffy/commit/f3a31ecee236a10f2c694458975569fb4019be7b](https://github.com/bstinsonmhk/duffy/commit/f3a31ecee236a10f2c694458975569fb4019be7b)  

I followed this for naming convention and render_as_batch. 

when I run `flask db upgrade`  I get this,

> sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL:
DROP TABLE "table"]
(Background on this error at: http://sqlalche.me/e/gkpj)

I am not sure what I am missing and I am not finding example

**Comment by shivarajalagond** [comment]
Also, in the Alembic docs it says, `Changed in version 1.1.1: Support for Python 3.4 was dropped.`
Is it possible to restrict the version being used in flask-migrate?

**Comment by miguelgrinberg** [comment]
Do you have any other tables with foreign keys into the table you are deleting? The problem with that is that those foreign keys are left in an inconsistent state when the table is deleted.

You have to define a "ON DELETE" behavior for your foreign key so that when the table is removed your foreign keys are fixed in a way that makes sense for your application.

**Comment by shivarajalagond** [comment]
@miguelgrinberg : Thanks for your quick response. Yes, one of the column from the table I am trying to delete is a foreign key in another key. What I tried to do was to drop the constraint on other table, however I got the error saying batch_op does not have drop constraint.

Could you please guide me with this or the "ON Delete" you mentioned? Their are very limited examples available online. :(

**Comment by miguelgrinberg** [comment]
Sorry I missed this, but the problem appears to be a typo. You have `drop_constaint` instead of `drop_constraint`.
