### ISSUE TITLE
upgrade  downgrade  generate reverse 

### ISSUE THREAD

**Issue by zx5435** [miguelgrinberg/Flask-Migrate#293]
I add one table column in mysql console

run flask db migrate
generate code is
    upgrade  drop_column
    downgrade  add_column

So I think is reverse error

correct is maybe 
    upgrade  add_column
    downgrade  drop_column

**Comment by miguelgrinberg** [comment]
You are doing it backwards.

You are supposed to change the models, and then Flask-Migrate makes the same change in your database.
