### ISSUE TITLE
Flask-Migrate not generating any migrations.

### ISSUE THREAD

**Issue by impiyush83** [miguelgrinberg/Flask-Migrate#296]
Flask-Migrate not generating any migrations.

         INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
         INFO  [alembic.runtime.migration] Will assume transactional DDL. 
         INFO  [alembic.env] No changes in schema detected.

My folder structure is as follow:

* I don't want to add any code in the __init__.py file
├── insta_backend
│   ├── auth
│   ├── common
│   ├── exceptions
│   ├── schemas
│   ├── app.py
│   ├── extensions.py
│   ├── models
│   │   ├── friend.py
│   │   ├── __init__.py
│   │   ├── user.py
├── migrations
│   ├── alembic.ini
│   ├── env.py
│   ├── env.pyc
│   ├── README
│   ├── script.py.mako
│   └── versions
├── README.md
├── requirements.txt
├── manage.py

# extensions.py 

      import os

      from flask import Config
      from flask_migrate import Migrate
      from sqlalchemy_wrapper import SQLAlchemy

      config_name = 'insta_backend.config.{}Config'.format(
     os.environ.get('INSTA_ENV')) 
     config = Config("") 
     config.from_object(config_name)

  
    db = SQLAlchemy(
         uri=config['SQLALCHEMY_DATABASE_URI'],
        pool_pre_ping=True,
        # tests connections for liveness upon each checkout. By firing select 1; query
        pool_timeout=30,
        # – number of seconds to wait before giving up on getting a connection
       # from the pool
    )
    
    migrate = Migrate(compare_type=True)

# app.py

    from flask import Flask
    from flask_jwt_extended import JWTManager

    from insta_backend.api import restful_api
    from insta_backend.extensions import config_name, db, migrate

    def create_app(config_object=config_name):
        app = Flask(__name__)
        app.config.from_object(config_object)
        restful_api(app)
        register_extensions(app)
        JWTManager(app)
        # register_blueprints(app)
        return app

    def register_blueprints(app):
        pass
    
    def register_extensions(app):
        db.init_app(app)
        migrate.init_app(app)

# env.py configs

    fileConfig(config.config_file_name)
    logger = logging.getLogger('alembic.env')
    
    # add your model's MetaData object here
    # for 'autogenerate' support
    # from myapp import mymodel
    # target_metadata = mymodel.Base.metadata
    from flask import current_app
    config.set_main_option(
        'sqlalchemy.url', current_app.config.get(
            'SQLALCHEMY_DATABASE_URI'))
    target_metadata = current_app.extensions['migrate'].db.metadata

# model - user.py

from insta_backend.extensions import db

     class User(db.Model):
        email = db.Column(db.String, unique=True, nullable=False)
        first_name = db.Column(db.String, nullable=False)
        last_name = db.Column(db.String, nullable=False)
        password = db.Column(db.String, nullable=False)
        gender = db.Column(db.String, nullable=False)
        favourite_color = db.Column(db.String, nullable=False)
        favourite_food = db.Column(db.String, nullable=False)
        favourite_song = db.Column(db.String, nullable=False)
       mobile = db.Column(db.String, nullable=False)
       childs = db.relationship('Friend')
 
 
### All tables get detected if i add tables in extensions.py, but this will be a bad coding practice to add all tables in one file.

**Comment by miguelgrinberg** [comment]
The models need to be imported so that they are registered with SQLAlchemy. If you do not import them, then SQLAlchemy does not know about them, and in turn Alembic will not generate migrations for them.

**Comment by impiyush83** [comment]
@miguelgrinberg  Yes, my file structure gives import error as Circular Dependency is introduced of DB and models. I changed my file structure according to the Mega-Flask Tutorial and it works smooth as butter.
