### ISSUE TITLE
Issue : Existing table won't allow for migration. 

### ISSUE THREAD

**Issue by HectorGit** [miguelgrinberg/Flask-Migrate#297]
Hi Miguel ! 

Thanks for the tutorial.

Working on a flask project.

I am new on this project, and there's been work done, but not all tables were registered on Models.py by preceding project contributors. For this reason, I used the flask-sqlacodegen tool, to 'auto-generate' my tables based on the current model. 

Ideally I would:
* Be able to retain all the data (e.g. not having to drop tables)
* Have the auto-generated Models.py definition be recognized by the application, and from this point onwards to start properly adding any db change to Models.py .

The problem I have right now is that there is (from the previous - 'half defined' models.py) a table already. At the same time - the migration script auto-generated by alembic is attempting to add it, from the new autogenerated Models.py. 

The err0r is n0t unc0mm0n : "sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "components_frames" already exists"

Thanks,
Hector

**Comment by miguelgrinberg** [comment]
This is a question for Alembic, not Flask-Migrate. I honestly don't know, something on that table must be confusing Alembic into thinking it does not exist on the database yet.
