### ISSUE TITLE
Not null error on migrate

### ISSUE THREAD

**Issue by Monduiz** [miguelgrinberg/Flask-Migrate#298]
I have this column in my model:

`image_file = db.Column(db.String(20), nullable=False, default='default.jpg')`

From what I understand, default= is Sqlalchemy so Alembic doesn't add that value.
Is there something more I need to do to get the migration to stop giving me an alter not nullable error?

**Comment by miguelgrinberg** [comment]
You can add `server_default='default.jpg'` so that the default is applied on the database side.

**Comment by Monduiz** [comment]
I changed the line to default_server but I am still getting that error:

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ALTER": syntax error
[SQL: ALTER TABLE user ALTER COLUMN image_file SET NOT NULL]`
