### ISSUE TITLE
Use w/ Reflection

### ISSUE THREAD

**Issue by atwoodjw** [miguelgrinberg/Flask-Migrate#304]
Is it possible to use Flask-Migrate w/ autoloading/reflection? [Link](https://docs.sqlalchemy.org/en/13/core/reflection.html)

I can't seem to get it working. Because Flask-Migrate's commands run `@with_appcontext`, I encounter `sqlalchemy.exc.NoSuchTableError: xxx.tasks` before the migration to create the table runs (i.e. `flask db upgrade`).

**Example:**

**migrations/versions/XXXXXXXXXXXX.py**

```
def upgrade():
    op.create_table(
        "tassk",
        sa.Column("id", sa.INTEGER, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
```

**app/common/models/task.py**

```
from app import db

class Task(db.Model):
    __tablename__ = "tasks"
    __table_args__ = {"autoload": True, "schema": "xxx", "autoload_with": db.engine}
```

**app/__init__.py**

```
db = SQLAlchemy()
migrate = Migrate()

def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(config)

    db.init_app(app)
    migrate.init_app(app, db)

    with app.app_context():
        from app.common import bp as common_bp

        app.register_blueprint(common_bp)

        ...

    return app
```

**Comment by miguelgrinberg** [comment]
First of all, what's the point of using a migration engine if you are going to use table reflection. And second, this is the repository for Flask-Migrate, which is a Flask friendly wrapper for Alembic, the migration engine. Your question really applies to Alembic.

**Comment by atwoodjw** [comment]
Thanks for the response.

Database migrations and model definitions are separate concerns. As a point of comparison, [ActiveRecord](https://api.rubyonrails.org/classes/ActiveRecord/Base.html) supports migrations. And Active Record objects infer their attributes from the database, similar to autoloading/reflection in SQLAlchemy.

If it is possible to make this work, I'd think it would be in Flask-Migrate, not Alembic. In this use case, the issue seems to be with requiring the application context, which requires the model.

**Comment by wgwz** [comment]
One thing I’ve done in the past is swap out the metadata object with the metadata object you get as a result of doing a reflection. I can try to share an example here but I do agree with Miguel here, it really is more of an Alembic question.

**Comment by wgwz** [comment]
Another suggestion is that maybe you can separate the models that you are using reflection on from the models that you are dealing with migrations for. And in that case you wouldn’t necessarily need to be tied to the extra functionality that comes along with Flask-SQLA and Flask-Migrate.

But dealing with migrations gets really tricky unless all the models are being managed via the same mechanism.

**Comment by miguelgrinberg** [comment]
@atwoodjw you seem to think this package does much more than it really does.

If you want to use reflection, that's a SQLAlchemy feature. I assume you got that working, yes?
If you want to work with database migrations, add Flask-Migrate. You will not be able to auto-generate migrations if your models are reflected from the database. This is the source of my "what's the point" statement. You should be fine using manually written migrations.

You are saying something about a context that I do not understand. If you get a no such table error, then you must have an error in your migration. Did you check in your database if this tasks table exists or not? The example migration that you show above creates a `task` table, not `tasks`.

**Comment by atwoodjw** [comment]
I'm not trying to auto-generate migrations. I'm trying to do the opposite -- explicitly create database migrations and infer model attributes using reflection at run-time, similar to ActiveRecord. I was planning to use Flask-Migrate primarily for the Flask CLI wrapper around Alembic commands.

Each wrapper function has the `@with_appcontext` decorator. Ex:

https://github.com/miguelgrinberg/Flask-Migrate/blob/d501d8b2923187df00d6bb1ec1f04694ab3f9667/flask_migrate/cli.py#L131

When I run `flask db upgrade`, Flask-Migrate's CLI function (i.e. `upgrade`) creates an application context (where SQLAlchemy is trying to find the table to look up attributes) before the migration creating the table runs.

It seems like this isn't a use case you support, which is fine. My currently plan is to create my own CLI wrapper functions w/ `with_appcontext=False`.

Sorry for the typo in the original message. The table is `tasks`, which I've corrected.

**Comment by miguelgrinberg** [comment]
@atwoodjw Not sure this is really a workflow that is not supported. You have defined a reflected model for a table that is yet to be created, so there is no way that is going to work. With the way you want to do things, you would need to create and execute the database migration, and only then add the model to your application, and then you should have no problems.

**Comment by atwoodjw** [comment]
Got it. The common workflow for SQLAlchemy + Alembic is opposite what I'm used to in ActiveRecord. Here, we create/update models and generate migrations. In ActiveRecord, we write migrations and infer model attributes.

In the latter approach, Alembic doesn't need access to the models (or the app context). I'll take a stab at getting this to work and report back.

Thanks for the feedback.
