### ISSUE TITLE
How to Dockerize your Flask-Migrate App?

### ISSUE THREAD

**Issue by vvksahoo** [miguelgrinberg/Flask-Migrate#305]
Hi, 
I went through flask_migrate docs. What i understood mentioned below , let me know if i wrong.
Initialization of migration:
      python manage.py db init 
For Applying the changes of model we have to run these two commands.
     python manage.py db migrate 
     python manage.py db upgrade
YAML file:
web:
    build:
      context: .
    expose:
      - "5000"
    depends_on:
      - db 

db:
  image: postgres
  volumes:
    - my_volume:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: somesecret

Qns :
i have to dockerize my application so i am using docker-compose yaml , where will have two container one of my app code and another is db.  so the qns are : 
1: Do i need to copy the migration folder as my part of app code ?
2:  I have separate migration.py which want to run before python app.py 
RUN  python migration db upgrade(Not sure whether its correct or not )
CMD ['python','app.py'] 

How can i do these ?

**Comment by miguelgrinberg** [comment]
> 1: Do i need to copy the migration folder as my part of app code ?

Yes.

> 2: I have separate migration.py which want to run before python app.py

In general what I do is write a boot.sh script that runs all the tasks that need to be executed before the server starts, and then in the final line you can `exec` the server process.

**Comment by vvksahoo** [comment]
Thanks a lot miguel for your reply . I will definitely try it out .

**Comment by vvksahoo** [comment]
I am not able to figure it out  what i am doing wrong .
 **DockerFile**:
FROM tiangolo/uwsgi-nginx-flask:python3.7

# copy over our requirements.txt file
COPY ./requirement.txt /tmp/

# upgrade pip and install required python packages
RUN pip install -U pip
RUN pip install -r /tmp/requirement.txt


# copy over our app code
COPY run.py /app/run.py
COPY mgm_services /app/mgm_services
COPY migrations  /app/migrations
COPY entry-point.sh /app/entry-point.sh
RUN chmod +x entry-point.sh

ENTRYPOINT ["./entry-point.sh"]
EXPOSE 8000

**entry-point.sh**:
#! /bin/bash
python manage.py db migrate
python manage.py db upgrade
python app.py

**ERROR**:
Getting this error always .
standard_init_linux.go:211: exec user process caused "no such file or directory"

**Comment by mifot** [comment]
In my opinion you shouldn't execute "python manage.py db migrate" command  in entry-point script but only that with upgrade. 
Did you try that way? 
I had also a problem with Flask-migrate app using docker so let us know what's was wrong ;)

**Comment by CHuKeR** [comment]
You should make db migrate manually in your project folder and add db upgrade command in your docker-compose file :)

**Comment by mifot** [comment]
ok, that's clear for me. But on which state should I make a pull to github. Before or after db upgrade?
