### ISSUE TITLE
SQL: ALTER TABLE users ALTER COLUMN password SET NOT NULL

### ISSUE THREAD

**Issue by KikeVen** [miguelgrinberg/Flask-Migrate#306]
I am trying to update column from `nullable=True` to `nullable=False` and Flask-Migrate is generating the following error

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ALTER": syntax error
[SQL: ALTER TABLE users ALTER COLUMN password_hash SET NOT NULL]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Upon researching the error:**
`'sqlite3.OperationalError: near "ALTER": syntax error'`

**Found the following**

> "Just figured out the reason, it's because I'm using sqlite and sqlite lacks of ALTER support, a workaround for this is using the batch operation migrations http://alembic.zzzcomputing.com/en/latest/batch.html"

[Stackoverflow](https://stackoverflow.com/a/44635182)

**I need to upgrade my db, what fixes are available for Flask-Migrate**

Thank you

- Enrique

**Comment by miguelgrinberg** [comment]
Have you looked at the batch mode workaround that you found? That's the only one for SQLite.
