### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by rseichter** [miguelgrinberg/Flask-Migrate#307]
Greetings. According to the Travis configuration, Flask-Migrate does not yet seem to be tested with Python 3.8, and I was wondering if there might be an estimate when that particular version will be supported?

**Comment by miguelgrinberg** [comment]
First of all, Python 3.8 is fully supported.

Would you like to have a go at adding 3.8 to the travis configuration? I'll eventually get to it if not, so no worries, but I have several packages that need this work done, and my time is limited.

**Comment by rseichter** [comment]
I think I can manage adding a line to text to a YAML file without breaking it. 😉 I will open a pull request soonish.
