### ISSUE TITLE
App with custom data models doesn't import the app package

### ISSUE THREAD

**Issue by fubuloubu** [miguelgrinberg/Flask-Migrate#309]
Version 2.5.2

Noticed that when trying to upgrade using a migration that adds a custom data type (something that subclasses `TypeDecorator`) the migration script that gets created correctly generates the data model (e.g. `sa.Column('mytype', app.models.CustomType())`); however, it fails to import `app` at the top of the script, and thus raises `NameError: name 'app' is not defined` when you run it.

Simple solution is to import the app.

**Comment by miguelgrinberg** [comment]
Flask-Migrate is a wrapper for Alembic, which is where migrations are generated. This package does not have the migration generation logic.

**Comment by fubuloubu** [comment]
Ah thanks! For anyone else: the solution is to modify the `script.py.mako` file per https://github.com/sqlalchemy/alembic/issues/294
