### ISSUE TITLE
Bug - Table column name change

### ISSUE THREAD

**Issue by duducp** [miguelgrinberg/Flask-Migrate#310]
Hello,

I have a model where there is a column with the following name:
```python
from sqlalchemy.dialects.postgresql import UUID
from app.database import db
from app.models.base import Base

class Model(Base):
    __tablename__ = "ticket_product_lot"
    __table_args__ = (db.UniqueConstraint("package_id", "partner_origin_id"),)

    numberNF = db.Column(db.Integer, nullable=True, default=0)
    package_id = db.Column(db.Integer, nullable=False)
    partner_origin_id = db.Column(UUID(as_uuid=True), nullable=False)
````

I made a change to the column name:
```python
from sqlalchemy.dialects.postgresql import UUID
from app.database import db
from app.models.base import Base

class Model(Base):
    __tablename__ = "ticket_product_lot"
    __table_args__ = (db.UniqueConstraint("package_id", "partner_origin_id"),)

    number_nf = db.Column(db.Integer, nullable=True, default=0)
    package_id = db.Column(db.Integer, nullable=False)
    partner_origin_id = db.Column(UUID(as_uuid=True), nullable=False)
````

When I ran the command to generate the migration "flask db migrate" I was generated the following change:
![2020-01-12_11-57](https://user-images.githubusercontent.com/16366240/72220818-8178c000-3533-11ea-8e17-75b89ccbe3b3.png)

We can see that the change that will be applied to the database is to remove the existing column and create another one.

This is wrong and what should be done is to generate an update for the table column name.
`op.alter_column('ticket_product_lot', 'numberNF', nullable=False, new_column_name='number_nf')`

**Comment by miguelgrinberg** [comment]
First of all, you are asking in the wrong project. Flask-Migrate is an Alembic wrapper for Flask. The migrations are done by Alembic.

Second, Alembic has no way to know if you renamed a column or you deleted one and created another. Both look exactly the same in the models. What you need to do is edit the migration script to be what you want, the expectation that Alembic is always going to guess what you changed is unrealistic, all migrations need to be reviewed and edited for accuracy.

**Comment by duducp** [comment]
Sorry for posting to the wrong project.

It really makes sense the second point raised by you.

Thanks!
