### ISSUE TITLE
`flask db migrate` drop all tables

### ISSUE THREAD

**Issue by sumingfei** [miguelgrinberg/Flask-Migrate#315]
after upgrading flask to > 1.0.0, command `flask db migrate` generates migration script to drop all tables as if the db models are not loaded, downgrading to < 1.0.0 everything works as expected

I've seen previous posts of similar problem such as https://github.com/miguelgrinberg/Flask-Migrate/issues/94 but I haven't been able to figure out what's wrong with my set up, hoping someone may be able shed some lights

1) confirmed FLASK_APP is set up correctly
2) confirmed not setting up different db instances, there's only one `db = SQLAlchemy(app)` which is under `app/__init__.py`
2) confirmed that the models are imported by printing `sys.modules.keys()` under `migrations/env.py run_migrations_online()`

package versions
`Flask==1.0.2`
`Flask-Migrate==2.4.0`
`Flask-SQLAlchemy==2.4.0`
`SQLAlchemy===1.3.8`

under **app/__init__.py**
`app = Flask(__name__)`
`db = SQLAlchemy(app)`
`migrate = Migrate(app, db)`
`ma = Marshmallow(app)`

`from app import views, models`

**Comment by miguelgrinberg** [comment]
Can you try this with 1.0.1, 1.0, 0.12.4, etc. until you find which release is the first that restores the right behavior? Can't think of anything in Flask that could affect this, but if we know the exact release that introduced this problem it'll be easier to identify what is the cause.

**Comment by sumingfei** [comment]
Thank you for responding @miguelgrinberg, I have identified that it is 1.0 that this starts happening, 0.12.5 is okay.

**Comment by miguelgrinberg** [comment]
Using the example app in the `tests` directory I see no issues making migrations with the latest Flask 1.1.1 release. Any idea what might be different in your project?

Really the only logical explanation that I have is that the models were already in your database and that is why they were not detected, but I do understand that this does not agree with the claim that the Flask version influences the behavior.

**Comment by sumingfei** [comment]
I'm not quite sure what's different, I do have other projects with the same package versions without this problem. I have tried to re-init the migrations folder but this problem persist

I was wondering if you have any suggestions on how I can debug this issue.

**Comment by miguelgrinberg** [comment]
If you could create a small self-contained project that shows this problem I could debug it myself. Start from your project and remove as much as you can.

**Comment by sumingfei** [comment]
hi @miguelgrinberg, sorry for the late update here. First I want to thank you, I ended up figuring out the issue with the approach you suggested by stripping the codebase layer by layer as I didn't want to leak any company info due to our policy.

The problem has to do with an `__init__.py` file in our root directory which is actually useless, our directory looks like this
`
/root
        __init__.py
        /client  <- web code
        /flask  <- server code
        /migrations <- migration files
`
we run migrations in the root folder, and I think it was picking up the root __init__.py file which does nothing and causing it to not pick up any db models

we do have FLASK_APP defined, I saw there was quite a bit of changes regarding FLAZK_APP in the 1.0 update

**Comment by Shortz79** [comment]
Hi @sumingfei, I'd some similar structure with your app. If you feel good it would be great to know how you fixed these issue.
I try many way but the flask-migrate always drop all tables.
