### ISSUE TITLE
Migrate always trying to delete tables in upgrade function

### ISSUE THREAD

**Issue by mayurpande** [miguelgrinberg/Flask-Migrate#316]
So I have my models and I create follow the flow of creating the db tables like so;

```
>>> from myapp import create_app
>>> from myapp.models import db
>>> app = create_app()
>>> app.app_context().push()
>>> db.create_all()
```
This works fine and creates the correct tables.

Then in the terminal I run;

```
~/ flask db init #creates the migrations folder
~/ flask db migrate

```
After this step I check the version folder file and it always wants to drop my tables in the ;

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapped_data')
    op.drop_table('test_company')
    op.drop_table('company')
```
So initally I just commented them out and passed the function, but when I made another change and migrated again, it doesn't show the migration, but only wants to drop the tables again.

**Comment by miguelgrinberg** [comment]
The first (maybe only) problem that I see is that you are using both `db.create_all()` and Flask-Migrate. These two ways of managing your database compete with each other. You have to pick one and stop using the other.

**Comment by mayurpande** [comment]
I have done it this way just using migrate before, but it doesn't create the tables. So for example I have just dropped the db and deleted the migrations folder.

Then in my terminal;
```
~/ flask db init
~/ flask db migrate
```
This returned;
```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.

```
Then I run the upgrade and it returned;

```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

```
Then I checked the db and the only table there is the alembic_version one

**Comment by miguelgrinberg** [comment]
Are you importing your models? Even though they are not used, they need to be imported somewhere, so that SQLAlchemy knows about them.

**Comment by mayurpande** [comment]
Sorry a little confused on where to import them? As before when I was using `db.create_all()` I only imported the object. But if I am not supposed to use that method, I am unsure where to import them to.

**Comment by mayurpande** [comment]
Thanks, it was the second, I imported then run the migrate and it worked.
