### ISSUE TITLE
flask db init runs the debugger

### ISSUE THREAD

**Issue by eyalmnm** [miguelgrinberg/Flask-Migrate#320]
As result of running the

> flask db init
I got the following
` flask db init
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 100-555-104
`
I have configured my PyCharm according to the instruction in the following blog
[Setting Up a Flask Application in PyCharm](https://blog.miguelgrinberg.com/post/setting-up-a-flask-application-in-pycharm)
and follow the articles in the [Chapter 4: Database](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database)

How it can be resolved?

`from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)`

**Comment by miguelgrinberg** [comment]
Do you have any calls to `app.run()` in your application? If yes, can you show me that code?

**Comment by eyalmnm** [comment]
I have solved it by creating new project using PyCharm Professional.
