### ISSUE TITLE
@migrate.configure not passing include_object to Alembic

### ISSUE THREAD

**Issue by mfosterw** [miguelgrinberg/Flask-Migrate#323]
I tried to use the @migrate.configure decorator to set the include_object parameter in my` __init__.py` file but it didn't work, and it seemed like the change I made wasn't even included in the `current_app.extensions['migrate'].configure_args` dictionary. I know the callback ran, but when I printed out the `configure_args` dictionary it was empty. My callback function (in `app/__init__.py`) :
```python
#...
migrate = Migrate(app, db)
#...
def include_object(object, name, type_, reflected, compare_to):
    #function copied from Alembic docs

@migrate.configure
def configure_alembic(config):
    config.attributes[include_object] = include_object
    print(config.attributes)
    return config
```

When I modified the `env.py` file directly, passing the argument to both calls of `context.configure`, it worked fine.

**Comment by miguelgrinberg** [comment]
Maybe it was for the missing quotes?

    config.attributes['include_object'] = include_object

**Comment by mfosterw** [comment]
Sorry, I rewrote my code instead of copying and pasting what I originally had. I did not originally have that mistake. I just double checked, and it still does not work.

**Comment by miguelgrinberg** [comment]
Now that I look at this more carefully, was this ever supposed to work this way? I don't think it ever did.

The `configure` decorator is only for modifying the Alembic config file `alembic.ini`. You can only add or edit items that go in this file. The `include_object` is an option for the migration context, which has nothing to do with the config file.

Context options can be passed when you create your `Migrate` instance though:

```
migrate = Migrate(app, db, include_object=include_object)
```

**Comment by mfosterw** [comment]
Ah, thank you, I was confused about the usage because the configure function in `env.py` is ultimately where this parameter is used. It works with the line you gave me. Thank you so much for your help.
