### ISSUE TITLE
Binding Multiple Database error

### ISSUE THREAD

**Issue by rupeshdesai82** [miguelgrinberg/Flask-Migrate#324]
Hi MIguel,

I have installed flask-migrate, but I am having issue with multidb part. The Flask Migrate script that I ran from command line as you suggested works fine for single db. But when I added SQLALCHEMY_BINDS and used db init --multidb. This went through and generated the scripts and the folder. However, the db migrate function failed stating that on line 33 in env.py current_app.config.get("SQLALCHEMY_BINDS") returns a not iterable object. However, my db.create_all() from SQLAlchemy works fine. Can you please look into this issue?

Thanks,

Rupesh Desai

**Comment by miguelgrinberg** [comment]
What's the value of `current_app.config.get("SQLALCHEMY_BINDS")`?

**Comment by rupeshdesai82** [comment]
Hi Miguel,

Thank you for the quick response.

I have set the SQL binds through my config file: Below is how it looks
like. The environment is set to development. The three steps that I have
taken are:

1) db init --multifb
2) db migrate (this is where I got an error)
3) db upgrade (I would have done this if it worked).

environment_type = {
"development": {
"postgres": "postgresql://postgres:postgres@localhost",
"AWS_SECRET_KEY": "aws",
"AWS_SECRET_ACCESS_CODE": "aws",
"SQLALCHEMY_TRACK_MODIFICATIONS": True,
"JWT_SECERET_KEY" : "",
"SQLALCHEMY_BINDS" : {
"core":"postgresql://postgres:postgres@localhost",
"client":"postgresql://postgres:postgres@localhost/client134"
}
},
"staging": {
"postgres": "stagingdb",
"SECRET_KEY": "aws",
"ACCESS_CODE": "aws",
"SQLALCHEMY_TRACK_MODIFICATIONS": False,
"JWT_SECERET_KEY" : ""
},
"production": {
"postgres": "production",
"SECRET_KEY": "secretkey",
"ACCESS_CODE": "Access Code",
"SQLALCHEMY_TRACK_MODIFICATIONS": False,
"JWT_SECERET_KEY" : ""
}
}

**Comment by rupeshdesai82** [comment]
one more thing!
The readme says "Generic single-database configuration."

**Comment by miguelgrinberg** [comment]
Sorry, but this isn't what I'm asking. You said that in line 33 of env.py there is an error because the binds config setting is not iterable. Please add a print statement in line 32 as follows:

```python
print("binds:", current_app.config['SQLALCHEMY_BINDS'])
```

Then include the complete output of the script, including the print statement and the stack trace that follows.

**Comment by rupeshdesai82** [comment]
My bad: The find for some reason says "None".

*Here is the full text:*

(core) root@RupeshLaptop:/mnt/d/Reasonable
Brands/python-dev/dsiq/core/utils/schemas# python migrate.py db migrate
/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:814:
UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set.
Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:835:
FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant
overhead and will be disabled by default in the future.  Set it to True or
False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
*binds: None*
Traceback (most recent call last):
  File "migrate.py", line 49, in <module>
    manager.run()
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/flask_script/__init__.py",
line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/flask_script/__init__.py",
line 386, in handle
    res = handle(*args, **config)
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/flask_script/commands.py",
line 216, in __call__
    return self.run(*args, **kwargs)
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/flask_migrate/__init__.py",
line 96, in wrapped
    f(*args, **kwargs)
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/flask_migrate/__init__.py",
line 212, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/alembic/command.py",
line 214, in revision
    script_directory.run_env()
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/alembic/script/base.py",
line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/alembic/util/pyfiles.py",
line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/mnt/d/Reasonable
Brands/python-dev/dsiq/core/lib/python3.7/site-packages/alembic/util/compat.py",
line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in
_call_with_frames_removed
  File "migrations/env.py", line 34, in <module>
    for bind in current_app.config.get("SQLALCHEMY_BINDS"):
TypeError: <flask_script.commands.Command object at 0x7fc60ce138d0>:
'NoneType' object is not iterable
(core) root@RupeshLaptop:/mnt/d/Reasonable
Brands/python-dev/dsiq/core/utils/schemas#

**Comment by miguelgrinberg** [comment]
Well, you see that you have a configuration problem?

    Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set.

This means that for some reason your db configuration isn't being applied.

**Comment by rupeshdesai82** [comment]
Miguel,

Thank you for the clarification and quick responses. I found the issue.
I was initializing the app before setting the required params.

I have resolved this issue.

Thank you,

Rupesh Desai
