### ISSUE TITLE
Why does each command keep running while it successfully completed?Is there anyway I can make it exit after fail or success?

### ISSUE THREAD

**Issue by zealot-shin** [miguelgrinberg/Flask-Migrate#329]
my code is just like ur example in README.md.
And every db command functions well.

But I'm wondering why don't they exit after success or fail.
When I migrate, upgrade or downgrade, the CLI never exit. So I hava to ctrl+c to 
finish this command.

**Comment by miguelgrinberg** [comment]
This is likely a bug in your application. You are probably starting a background thread that is not configured to exit cleanly when the process ends.

**Comment by zealot-shin** [comment]
What u said inpired me finding what's wrong with my code. Thank u!
It turned out that apschedule jobs made it a backgroud thread, Since in my 
create_app method, I configure apshcedule first.

So in my case , I think I need to configure apshcedule and db migrate in different create_app method, and set FLASK_APP to the module which contains db migreate codes only.
