### ISSUE TITLE
Programmatic access to revision information

### ISSUE THREAD

**Issue by 0xdade** [miguelgrinberg/Flask-Migrate#334]
Miguel,

I was looking through your code because I noticed that `flask_migrate.heads()` and `flask_migrate.current()` don't actually return any values, just print and then exit. I was hoping there would be an easy way to get access to this information because I want to implement a simple check on app start that makes sure the database is on the latest version, and fail gracefully if it is not, rather than fail randomly sometime down the line when something tries to access a table that isn't there.

What I tried:

```
import flask_migrate
app = Flask(__name__)
	initialize_opencensus(config_class, app)

	app.config.from_object(config_class)

	db.init_app(app)
	migrate.init_app(app, db)
	with app.app_context():
		if flask_migrate.current() != flask_migrate.heads():
			print(
				f"[!] Database {config.SQLALCHEMY_DATABASE_URI} needs to be upgraded.\n \
				Please make a backup and run \"flask db upgrade\""
			)
			raise(SystemExit())
```

But they are always equal because they both return NoneType every time. I was hoping to submit a PR to add return values to these, but it is not clear to me where the actual work is getting done to get this information, so I thought I'd file this and see if I'm going down the wrong path or what.

**Comment by 0xdade** [comment]
Nevermind, I found a previous issue (#247) that addresses this problem, looks like it's a shortcoming of Alembic. I'll have to dig deeper, but this issue isn't going to be any more useful than #247 I imagine.

**Comment by miguelgrinberg** [comment]
If you want an alternative method, you can query the `alembic_version` table in your database for the revision.
