### ISSUE TITLE
2.5.3 doesn't work with SQLAlchemy declarative extension

### ISSUE THREAD

**Issue by oleksiivelychko** [miguelgrinberg/Flask-Migrate#335]
Doesn't work with SqlAlchemy library and declarative approach. It's simple example from official documentation, in database.py:
```
...
Base = declarative_base()
...
```
And then I'll try to use with `flask-script`:
```
...
migrate = Migrate(app, Base)
...
```
After was executed `db init` command and was created the migrations directory next commands lke `migrate` and `upgrade` return the error:

```
(venv) alex@thinkpad:~/GitHub/flask-queue$ py manage.py db migrate
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    manager.run()
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 210, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/alembic/command.py", line 214, in revision
    script_directory.run_env()
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/alex/GitHub/flask-queue/venv/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 27, in <module>
    str(current_app.extensions['migrate'].db.engine.url).replace('%', '%%'))
AttributeError: type object 'Base' has no attribute 'engine'

```

Error is not critical, but it is. To fix it I got code from previous version 2.5.2 of library and I've replaced in env.py:
```
# 2.5.3v - lines 25-27
config.set_main_option(
    'sqlalchemy.url',
    str(current_app.extensions['migrate'].db.engine.url).replace('%', '%%'))
```
...to 
```
# 2.5.2v - lines 25-27
config.set_main_option(
    'sqlalchemy.url', current_app.config.get(
        'SQLALCHEMY_DATABASE_URI').replace('%', '%%'))
```
from https://github.com/miguelgrinberg/Flask-Migrate/blob/v2.5.2/flask_migrate/templates/flask/env.py
And It works.

**Comment by miguelgrinberg** [comment]
This code is not Flask-SQLAlchemy compatible, you are using SQLAlchemy directly:

```python
Base = declarative_base()
```

The Flask-Migrate extension expects a `db` instance from Flask-SQLAlchemy there:

```python
db = SQLAlchemy(app)
migrate = Migrate(app, db)
```

This extension does not work with SQLAlchemy when Flask-SQLAlchemy isn't used. If your project uses SQLAlchemy directly then use Alembic for your migrations.

**Comment by oleksiivelychko** [comment]
> This code is not Flask-SQLAlchemy compatible, you are using SQLAlchemy directly:
> 
> ```python
> Base = declarative_base()
> ```
> 
> The Flask-Migrate extension expects a `db` instance from Flask-SQLAlchemy there:
> 
> ```python
> db = SQLAlchemy(app)
> migrate = Migrate(app, db)
> ```
> 
> This extension does not work with SQLAlchemy when Flask-SQLAlchemy isn't used. If your project uses SQLAlchemy directly then use Alembic for your migrations.

Yes, you're right I don't need `flask-migrate` library, It's only SqlAlchemy. I've changed the description of my issue.

**Comment by miguelgrinberg** [comment]
What's your issue? As I said, this extension requires Flask-SQLAlchemy.

**Comment by oleksiivelychko** [comment]
> What's your issue? As I said, this extension requires Flask-SQLAlchemy.

Ok, but why flask-migrate 2.5.2 perfectly works without Flask-SQLAlchemy and can get the object of SqlAlchemy declarative_base() function as second param? Is it ok? or I'm doing wrong? I understand the documentation describes using with Flask-SQLAlchemy, but If i need declarative approach Is it correct to use declarative_base() instead of Flask-SQLAlchemy object ?

**Comment by miguelgrinberg** [comment]
No, the way you are using it is incorrect. As I said above, this extension requires Flask-SQLAlchemy. If it partially worked for you it was just by chance, it was never intended to work that way.

**Comment by oleksiivelychko** [comment]
Ok, thanks. If it works by chance, I will refuse this approach, but I've used it a long time it and migrations were worked with declarative_base() perfectly until 2.5.3. and later if set SQLALCHEMY_DATABASE_URI directly in env.py or just use 2.5.2 version.

**Comment by miguelgrinberg** [comment]
Well, if you are up to editing env.py then you can just edit it back to what it was with your changes, and then I think everything will work. The only thing that changed in 2.5.3 is how env.py finds the database URL, so revert it to your own method if that works better for you.
