### ISSUE TITLE
Randomized naming scheme makes it difficult to unwind

### ISSUE THREAD

**Issue by joegiglio** [miguelgrinberg/Flask-Migrate#336]
I am fairly new to Flask and Flask-Migrate and got myself all tangled up with some database table changes with SQLite.  I am trying to unravel the issues and would like to piece together the migration chain.

It would be helpful to me if the migration .py files had some type of time/date stamp in the filename so they appeared in order in the directory. 

Right now, I think I have to open each .py file individually and track the "down_revision" to put them in order.

**Comment by miguelgrinberg** [comment]
You can use the `flask db history` command to see the list in order. You can also list your migration scripts sorted by creation date, assuming it isn't messed up.

Alembic also supports a filename template, that you can use to configure a different naming scheme for migration scripts. See the `file_template` option of the alembic.ini file in their docs: https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file
