### ISSUE TITLE
Getting "table sqlite_sequence may not be dropped" error

### ISSUE THREAD

**Issue by joegiglio** [miguelgrinberg/Flask-Migrate#338]
I see this mentioned in this blog some time ago but never really resolved:  https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database/page/19.  See #473.

I am seeing the same problem as the original author.

1. Make changes to my models
2. Run flask db migrate and look at the migration file
3. The file has this command which I have to comment out or the upgrade will not run: `op.drop_table('sqlite_sequence')`

I understand this is an internal SQLite table and can't be removed.  

That table still exists in my schema and I never removed it.  Any idea what may cause this?

**Comment by miguelgrinberg** [comment]
This should be raised with Alembic, this project does not generate migration scripts. It seems this is a bug, Alembic should always ignore this table.

**Comment by svanscho** [comment]
I have the same problem. Is there a corresponding alembic ticket?
