### ISSUE TITLE
Don't create DB and migrations from Flask

### ISSUE THREAD

**Issue by DorimenUkraine** [miguelgrinberg/Flask-Migrate#339]
My app.py

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from config import Config

app = Flask(__name__)
app.debug = True
app.config.from_object(Config)

db = SQLAlchemy(app)
from models import Users

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)



if __name__ == '__main__':
    manager.run()
```

models.py

from app import db, app
from datetime import date, datetime

```
class Users(db.Model):
    # Users
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(120), index=True, unique=True)
    last_name = db.Column(db.String(128))
    first_name = db.Column(db.String(128))
    created = db.Column(db.DateTime, default=datetime.now())
    user_days = db.relationship("Days", back_populates="user_days")
    user_tasks = db.relationship("Tasks", back_populates="user_tasks")
    user_chats = db.relationship("Chats", back_populates="user_chats")

    def __init__(self, username, last_name, first_name):
        self.username = username
        self.last_name = last_name
        self.first_name = first_name

    def __repr__(self):
        return '<User {}>'.format(self.username)
```

Run commands:

```
python app.py db init
python app.py db migrate
python app.py db upgrade
```

And have a problem:

```
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from models import Users
  File "C:\Users\vandr\PycharmProjects\telegrambot_with_flask\models.py", line 1, in <module>
    from app import db, app
  File "C:\Users\vandr\PycharmProjects\telegrambot_with_flask\app.py", line 12, in <module>
    from models import Users
ImportError: cannot import name 'Users'
```

Can you help me?

**Comment by miguelgrinberg** [comment]
You have circular dependencies in your application. Take a look at your stacktrace, app.py imports models.py, and models.py imports app.py again.

**Comment by DorimenUkraine** [comment]
> You have circular dependencies in your application. Take a look at your stacktrace, app.py imports models.py, and models.py imports app.py again.

Sorry, but app.py doesn't import models.py. Or I don't see it )

**Comment by miguelgrinberg** [comment]
Yup, you need to look better. Line 12 of app.py. Stack traces do not lie. :)

**Comment by DorimenUkraine** [comment]
Yeap, you right )

Fixed it

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from config import Config

app = Flask(__name__)
app.debug = True
app.config.from_object(Config)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```

But now have another problem:

```
INFO  [alembic.autogenerate.compare] Detected removed table 'days'
INFO  [alembic.autogenerate.compare] Detected removed index 'ix_users_username' on 'users'
INFO  [alembic.autogenerate.compare] Detected removed table 'users'
INFO  [alembic.autogenerate.compare] Detected removed index 'ix_tasks_task_id' on 'tasks'
INFO  [alembic.autogenerate.compare] Detected removed table 'tasks'
INFO  [alembic.autogenerate.compare] Detected removed table 'chats'
```
Don't understand where i was wrong

**Comment by miguelgrinberg** [comment]
Your fix is not good, now you are not importing your models, which means that Flask-Migrate and SQLAlchemy think you have no models in your app.

You have to figure out a way to be able to import your models into the app, without causing the circular import loop.

**Comment by DorimenUkraine** [comment]
> Your fix is not good, now you are not importing your models, which means that Flask-Migrate and SQLAlchemy think you have no models in your app.
> 
> You have to figure out a way to be able to import your models into the app, without causing the circular import loop.

Exactly! That’s exactly what I can’t do (_You have to figure out a way to be able to import your models into the app, without causing the circular import loop_) )))) More precisely, I don’t know how)))

**Comment by DorimenUkraine** [comment]
I don’t know how to connect models correctly if they are in a separate file (it’s more convenient for me)

**Comment by miguelgrinberg** [comment]
The problem is that you are following the "single file" way of structuring your app, and have only separated the models, which creates some complications due to the weird way Python's import system treats the main script. As a long term goal I suggest you use a more broken-up structure using packages, that is a bit more complex to set up but it reduces the chances of circular imports.

But if you want a quick fix, a really obscure change that will probably work in your case is to change the first line in models.py to:

    from __main__ import db, app

**Comment by DorimenUkraine** [comment]
> The problem is that you are following the "single file" way of structuring your app, and have only separated the models, which creates some complications due to the weird way Python's import system treats the main script. As a long term goal I suggest you use a more broken-up structure using packages, that is a bit more complex to set up but it reduces the chances of circular imports.
> 
> But if you want a quick fix, a really obscure change that will probably work in your case is to change the first line in models.py to:
> 
> ```
> from __main__ import db, app
> ```

Sorry to waste your time. But I can not figure out what you suggested. I do not have enough knowledge so far. A direct solution did not help either. Could you look at the code for github?

[](https://github.com/DorimenUkraine/telegrambot_with_flask)

**Comment by miguelgrinberg** [comment]
According to your code listings above, line 1 of models.py reads:

    from app import db, app

Change it to this:

    from __main__ import db, app

Let me know if this helps.

**Comment by DorimenUkraine** [comment]
> According to your code listings above, line 1 of models.py reads:
> 
> ```
> from app import db, app
> ```
> 
> Change it to this:
> 
> ```
> from __main__ import db, app
> ```
> 
> Let me know if this helps.

http://joxi.ru/nAyGvBQcjM97dm

Sorry, but...

**Comment by miguelgrinberg** [comment]
Nevermind your IDE, try running it and show me the error if you get any. As I said, if you want a quick fix, it is going to be obscure.

**Comment by DorimenUkraine** [comment]
> Nevermind your IDE, try running it and show me the error if you get any. As I said, if you want a quick fix, it is going to be obscure.

I replace first line to models.py
from __main__ import db, app

after python app.py db migrate

INFO  [alembic.autogenerate.compare] Detected removed table 'days'
INFO  [alembic.autogenerate.compare] Detected removed index 'ix_tasks_task_id' on 'tasks'
INFO  [alembic.autogenerate.compare] Detected removed table 'tasks'
INFO  [alembic.autogenerate.compare] Detected removed index 'ix_users_username' on 'users'
INFO  [alembic.autogenerate.compare] Detected removed table 'users'
INFO  [alembic.autogenerate.compare] Detected removed table 'chats'

all tables were drop

**Comment by miguelgrinberg** [comment]
Are you still importing models in app.py? That's required for SQLAlchemy to see your models.

**Comment by DorimenUkraine** [comment]
Yeap, now app.py has:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from config import Config
from models import Users, Chats, Days, Tasks


app = Flask(__name__)
app.debug = True
app.config.from_object(Config)

db = SQLAlchemy(app)


migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```
but after init 'python app.py db init' I have 

```
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from models import Users, Chats, Days, Tasks
  File "C:\Users\vandr\PycharmProjects\telegrambot_with_flask\models.py", line 1, in <module>
    from app import db
  File "C:\Users\vandr\PycharmProjects\telegrambot_with_flask\app.py", line 6, in <module>
    from models import Users, Chats, Days, Tasks
ImportError: cannot import name 'Users'
```

**Comment by miguelgrinberg** [comment]
But you moved the models import to the top now. Why did you do that? How are you going to get the models imported above the place where you create the db instance?

**Comment by DorimenUkraine** [comment]
Hm, right you are!!!

model.py

```
from __main__ import db, app
from datetime import date, datetime
```

app.py

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from config import Config


app = Flask(__name__)
app.debug = True
app.config.from_object(Config)

db = SQLAlchemy(app)
from models import Users, Chats, Days, Tasks

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```

main.py

```
from app import db, app
from models import Users, Days, Chats, Tasks
```

and now 
```
python app.py db migrate
python app.py db upgrade
```

create right changes...

Thank you so much!
