### ISSUE TITLE
Error updating different schema's, unable to configure alembic

### ISSUE THREAD

**Issue by bbloks** [miguelgrinberg/Flask-Migrate#342]
Hi Miguel,

First of all, thanks for building this tool, I have been using Flask-Migrate for a while now and like it a lot.

Currently I am using it to upgrade a Postgres database that makes use of different schemas. 
Every time I 'upgrade' a class with a new attribute to a table that is not in the 'public' schema, I receive the following error:
(as an example I use `myschema` as schema name and `mytable` as tablename below)

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "mytable" already exists

[SQL: 
CREATE TABLE schema.mytable (
        id BIGSERIAL NOT NULL, 
        timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
        some_attribute VARCHAR(32), 
        PRIMARY KEY (id)
)]
```
The upgrade can be done after dropping the table completely `DROP TABLE mytable;` and then do the `upgrade`. However this also results in the loss of all the data in the table and is supposedly not the correct nor desired method.

The only thing I could find was that Alembic is not including all other schemas of the database by default, as suggested in this post: https://stackoverflow.com/questions/40577640/flask-migrate-using-different-postgres-schemas-table-args-schema-te
According to the post, it is required to set `include_schemas = True` in the alembic configuration, as described here: https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure.params.include_schemas 

Unfortunately I am unable to figure out how to change the alembic configurations. 
I could not find any clear examples, so are there any documented/available? And should they be included in further documentation?
Secondly, would it not be better to set `include_schemas = True` as default for Flask-Migrate (if this is not yet the case)?

Thanks in advance!

To give some additional context I, closest I think I came to setting the config was with code below, giving an error the 'config` object has no attribute 'include_schemas' :

```
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from alembic.config import Config
alembic_cfg = Config()
...

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db = SQLAlchemy(app)
    migrate = Migrate(app, db)
    ...

    return app, db, migrate, ...

app, db, migrate = create_app()

@migrate.configure
def configure_alembic(config):
    config.include_schemas = True
    return config

configure_alembic(alembic_cfg)
```

**Comment by miguelgrinberg** [comment]
Alembic has different places where options are given. The `@migrate.configure` is a place where you add options that go in the alembic.ini configuration file, which is not where this option goes.

This is an option of the migration engine. You can edit it manually in env.py, or if you prefer you can pass it in the `Migrate()` call:

```
migrate = Migrate(app, db, include_schemas=True)
```

**Comment by bbloks** [comment]
Perfect, it is working now. 
I wasn't aware it could also be places as a parameter to the call. 

Thanks a lot!
