### ISSUE TITLE
INFO  [alembic.autogenerate.compare] Detected column comment

### ISSUE THREAD

**Issue by guhongyeying** [miguelgrinberg/Flask-Migrate#346]
1 step ： python manage.py db migrate 
2   INFO  [alembic.autogenerate.compare] Detected column comment Field
3 However, comment has not changed，

**Comment by miguelgrinberg** [comment]
This is something you need to take up with the Alembic project. Flask-Migrate does not generate the migrations, it just wraps Alembic to make it simpler to use with Flask.
