### ISSUE TITLE
:question How to add default value for exist column

### ISSUE THREAD

**Issue by Ich-bin-naoya** [miguelgrinberg/Flask-Migrate#348]
I tried to add default value into exits column,  I got this 
```
INFO  [alembic.env] No changes in schema detected.
```
Any solutions?

**Comment by miguelgrinberg** [comment]
The default argument is not implemented at the database level, it is handled by SQLAlchemy, so no need to make changes to the schema. The `server_default` option implements defaults at the database level.

**Comment by Ich-bin-naoya** [comment]
@miguelgrinberg 

Thank you for replying

I flask migrate and upgrade with this
role = db.Column(db.Integer)
then I change like this Because I need default value

db.Column(db.Integer,deefault=0)

then INFO  [alembic.env] No changes in schema detected. happend

I want to Flask migrate know I add default value

**Comment by miguelgrinberg** [comment]
I explained this above. The `default` option is implemented in SQLAlchemy, not in your database. The database schema does not change when you use this option.
