### ISSUE TITLE
error when using "flask db migrate"

### ISSUE THREAD

**Issue by zfc9d3f** [miguelgrinberg/Flask-Migrate#352]
I am coming back to a flask project that i was building earlier in the year and trying to reestablish the database connection to a new clean db. 

Previously, i could do `flask db migrate` flask db upgrade` with no problem however, i am receiving an error 
```
AssertionError: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
```

It isn't until i move  the Init_app out of the main excecution block that it actually works. I've never had this issue, what could be the problem ? 

```
if __name__ == "__main__":
    db.init_app(app)
    ma.init_app(app)
    app.run(port=5000, debug=True)
```

**Comment by miguelgrinberg** [comment]
Where are you moving your `init_app` calls? How are you starting your application?
