### ISSUE TITLE
Getting error `Error: Could not import "dms.database"` while doing `flask db init`

### ISSUE THREAD

**Issue by aniketsnv-1997** [miguelgrinberg/Flask-Migrate#353]
I'm trying to perform the db migration but getting the error ```Error: Could not import "dms.database``` when I run the command ```flask db init```

Note that the configuration values of this project are stored in the ```__init__.py``` inside the ```\dms``` directory whereas the ```app.run()``` line of code is in the ```run.py``` file which is outside the ```\dms`` directory

Please find the directory tree for reference
```
|   requirements.txt
|   run.py
|
\---dms
    |   api_file.py
    |   email.py
    |   logout.py
    |   security.py
    |   __init__.py
    |
    +---models
    |   |   __init__.py
    |   |
    |   +---donations
    |   |       ChequeDonationsModel.py
    |   |       DonationsModel.py
    |   |       KindDonationsModel.py
    |   |       ModesModel.py
    |   |
    |   +---donors
    |   |       CountryModel.py
    |   |       DonorsModel.py
    |   |       ReferencesModel.py
    |   |       StatesModel.py
    |   |       __init__.py
    |   |
    |   \---users
    |           CredentialsModel.py
    |           ProjectsModel.py
    |           RightsModel.py
    |           RolesModel.py
    |           TypesModel.py
    |           UsersModel.py
    |           __init__.py
    |
    +---resources
    |   |   __init__.py
    |   |
    |   +---donations
    |   |       Donations.py
    |   |       KindDonations.py
    |   |       Modes.py
    |   |
    |   +---donors
    |   |       Country.py
    |   |       Donors.py
    |   |       References.py
    |   |       States.py
    |   |       __init__.py
    |   |
    |   \---users
    |           Projects.py
    |           Rights.py
    |           Roles.py
    |           Types.py
    |           User.py
    |           __init__.py
    |
    +---static
    \---templates
```

I tried executing the ```flask db init``` command from inside the ```\dms``` dir and from outside the ```\dms``` as well

Currently, I am using a MySQL database on localhost

The ```run.py``` code is as follows
```
from dms import app, api, db, jwt

# Third Party Library Imports
from flask import jsonify
from flask_jwt_extended import JWTManager

# Imports from user related Resources
from dms.resources.users.Projects import Projects, SingleProject
from dms.resources.users.Rights import Rights, SingleRight
from dms.resources.users.Types import Types, SingleType
from dms.resources.users.Roles import Roles, SingleRole
from dms.resources.users.User import (
    Users,
    SingleUser,
    UserLogin,
    UserCredentials,
    TokenRefresh,
    UserLogout,
)

# Imports from donor related Resources
from dms.resources.donors.Donors import Donors, SingleDonor
from dms.resources.donors.References import Reference, SingleReference
from dms.resources.donors.States import State, SingleState
from dms.resources.donors.Country import Country, SingleCountry

# Imports from donations related Resources
from dms.resources.donations.Donations import Donation, SingleDonation
from dms.resources.donations.KindDonations import KindDonations, SingleKindDonation
from dms.resources.donations.Modes import Modes, SingleMode

from dms.models.users.UsersModel import UsersModel
from dms.logout import revoked_store

jwt = JWTManager(app)

# Used to add some more values and functionalities to the existing JWT token, like admin and user access
@jwt.user_claims_loader
def add_claims_to_jwt(identity):
    # TODO: Instead of 1, write the query to get id where user name is Vaishali Modak
    if identity == 8:
        return {"is_admin": True}

    return {"is_admin": False}


# To be used to check whether a token is logged out or not
@jwt.token_in_blacklist_loader
def check_token_in_logout(decrypted_token):
    jti = decrypted_token['jti']
    entry = revoked_store.get(jti)
    if entry is None:
        return True
    return entry == 'true'


# When JWT token sent by user to server is expired (a JWT token expired after 5 minutes)
@jwt.expired_token_loader
def expired_token_callback():
    return jsonify({"message": "The token has expired", "error": "token_expired"}), 401

# When the user does not send any token to the server
@jwt.unauthorized_loader
def no_token_callback():
    return jsonify({"message": "No token provided", "error": "no_token_received"})


# When the server needs a fresh token
@jwt.needs_fresh_token_loader
def no_fresh_token_callback():
    return jsonify({"message": "Send a fresh token", "error": "fresh_token_required"})


# When the server gets a revoked token from user, used in case of logout
@jwt.revoked_token_loader
def revoked_token_callback():
    return (
        jsonify(
            {
                "message": "You have been logged out from the system",
                "error": "revoked_token",
            }
        ),
        401,
    )


api.add_resource(Users, "/users")
api.add_resource(SingleUser, "/users/<int:_id>", "/users")
api.add_resource(UserCredentials, "/change%password")

api.add_resource(Projects, "/projects")
api.add_resource(SingleProject, "/projects/<int:_id>", "/projects")

api.add_resource(Roles, "/roles")
api.add_resource(SingleRole, "/roles/<int:_id>", "/roles")

api.add_resource(Rights, "/rights")
api.add_resource(SingleRight, "/rights/<int:_id>", "/rights")

api.add_resource(Types, "/types")
api.add_resource(SingleType, "/types/<int:_id>", "/types")

api.add_resource(Country, "/country")
api.add_resource(SingleCountry, "/country/<int:_id>", "/country")

api.add_resource(Reference, "/references")
api.add_resource(SingleReference, "/references/<int:_id>", "/references")

api.add_resource(State, "/states")
api.add_resource(SingleState, "/states/<int:_id>", "/states")

api.add_resource(Donors, "/donors")
api.add_resource(SingleDonor, "/donors/<int:_id>", "/donors")

api.add_resource(Donation, "/donations")
api.add_resource(SingleDonation, "/donations/<int:_id>", "/donations")

api.add_resource(KindDonations, "/kind_donations")
api.add_resource(SingleKindDonation, "/kind_donations/<int:id>")

api.add_resource(Modes, "/modes")
api.add_resource(SingleMode, "/modes/<int:_id>", "/modes")

api.add_resource(UserLogin, "/login")
api.add_resource(TokenRefresh, "/refresh")
api.add_resource(UserLogout, "/logout")

if __name__ == "__main__":
    db.init_app(app)
    app.run()
```

whereas the ```/dms/__init__.py``` code is as follows
```
from datetime import timedelta

from flask import Flask
from flask_restful import Api
from flask_sqlalchemy import SQLAlchemy
from flask_jwt_extended import JWTManager
from flask_migrate import Migrate

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "mysql://root:@localhost/dms"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["PROPAGATE_EXCEPTIONS"] = True  # This line enables the Flask app to identify errors and exceptions
# related to FlaskJWT and then report them accordingly


# Authentication related configuration values
app.secret_key = "aniket"
app.config["JWT_SECRET_KEY"] = "aniket"
app.config["JWT_AUTH_URL_RULE"] = "/login"
ACCESS_EXPIRES = timedelta(minutes=15)
REFRESH_EXPIRES = timedelta(days=30)
app.config['JWT_ACCESS_TOKEN_EXPIRES'] = ACCESS_EXPIRES
app.config['JWT_REFRESH_TOKEN_EXPIRES'] = REFRESH_EXPIRES
app.config["JWT_BLACKLIST_ENABLE"] = True
app.config["JWT_BLACKLIST_TOKEN_CHECKS"] = ["access", "refresh"]

# Linkages of the functionalities with the main flask app
db = SQLAlchemy(app)
api = Api(app)
migrate = Migrate(app, db)


def create_db():
    db.create_all()
    print("DB Created Successfully")


@app.before_first_request
def db_creation_command():
    create_db()


jwt = JWTManager(app)
```

Where am I actually going wrong ?

**Comment by miguelgrinberg** [comment]
You are importing `dms.database`, which is not something you have defined.

**Comment by aniketsnv-1997** [comment]
I sincerely apologize if I may sound silly but I am nowhere able to find the code ```dms.database```. I only know that the database name is ```dms```. And while running the ```flask db migrate``` command, I am nowhere using the ```dms.databse```

Do I need to do some changes in the code?

**Comment by aniketsnv-1997** [comment]
And by the way, Thank You for attending the error!

**Comment by miguelgrinberg** [comment]
I'm just interpreting the error message for you. The error must be in a part of the code that you haven't shared, so while I believe you need to make some changes, I cannot tell you where or what to change.

Some part of your application is trying to import `dms.database` and that fails because your `dms` package does not have a `database` member. Do you get a stack trace with the error? Maybe that will give you some clues as to the location of the issue.

**Comment by aniketsnv-1997** [comment]
No, actually the error does not consist of a traceback

here is the ```error``` message when I execute the ```flask db init``` command

```
(venv) C:\Users\admin\Desktop\VSM-DMS\dms>flask db init
Usage: flask db init [OPTIONS]

Error: Could not import "dms.database".
```
Also, I tried executing the command outside the ```dms``` package. But still, I got the same error

And I have shared all the relevant code. Still, if you need to view some other piece of code from other file, I can readily provide it

**Comment by miguelgrinberg** [comment]
Do `flask run` and `flask shell` both work without errors?

**Comment by aniketsnv-1997** [comment]
Both of the above commands give the same error. However, the application is still running fine on localhost

**Comment by miguelgrinberg** [comment]
Sorry, but I don't understand. How can the application run fine if `flask run` ends with an import error?

**Comment by aniketsnv-1997** [comment]
Here are the two screenshots - the first one when I run the app in PyCharm and the second one is the output of the command ```flask run```


![image](https://user-images.githubusercontent.com/34575457/85657541-cd798480-b6cf-11ea-81e1-b1a26b74ddc2.png)
![image](https://user-images.githubusercontent.com/34575457/85657564-d5392900-b6cf-11ea-950a-73052c742f7e.png)

**Comment by miguelgrinberg** [comment]
Did you notice that when you run `flask run` by hand you are in a different directory than when you run it through PyCharm? Why is that?

**Comment by aniketsnv-1997** [comment]
Even if I run the command ```flask run``` by hand from the same directory as that of which I run it through PyCHarm, it gives me the same error message. Here's the screenshot for your reference

Shall I try using an ```SQLite``` DB once? Will that bring any change in the scenario?

![image](https://user-images.githubusercontent.com/34575457/85721688-38967b80-b70f-11ea-91dd-07312a5f76a4.png)

**Comment by miguelgrinberg** [comment]
I can't really help you. When you changed your directory the import error changed from `dms.database` to just `database`. Some part of your application is doing this and failing, and then it prints this error without a stack trace. This makes it impossible for me to tell you where the error is.

Nothing that you have shown me suggests there is an issue with Flask-Migrate, this is all happening within your application. I suspect the reason why you can run the app from PyCharm is that you have added some environment variables that change how the app behaves. I can't really tell you more than this. I assume you've written this application yourself? Think about any imports that you issue that might have the `database` name.

**Comment by aniketsnv-1997** [comment]
Well, Okay! Yes, the entire code is written by me. I am actually trying to develop a donor management system for an NGO. I'll try to figure out where I might have used the name ```database```. Thank You for the responses and assistance given. Will definitely get in touch with you in case if I need assistance on some other topic

**Comment by aniketsnv-1997** [comment]
Okay! I'll try to find the variable name ```database``` in my code so that it does not give me this error. Yes, the application is entirely coded by me. Will close this issue as of now. Will definitely seek for your help if required
