### ISSUE TITLE
How to generate only the configuration file of the main database？

### ISSUE THREAD

**Issue by Gguangdong** [miguelgrinberg/Flask-Migrate#355]
I want to generate a configuration file generated by 【SQLALCHEMY_DATABASE_URI】 corresponding to the database，
Do not want to generate the configuration file of the database corresponding to SQLALCHEMY_BINDS. Thanks!

**Comment by miguelgrinberg** [comment]
Can you explain your issue with more details please? The SQLALCHEMY_BINDS setting is only used if you enable the `--multidb` option for your repository. The default is to use SQLALCHEMY_DATABASE_URI.
