### ISSUE TITLE
ImportError when creating the migration repository

### ISSUE THREAD

**Issue by PavelDymov** [miguelgrinberg/Flask-Migrate#359]
Hello!
Could you help me,please?

I am trying to create the migration repository. Flask-Migrate and Flask-SQLAlchemy were installed to venv without any problems. But when I write in command window the command 'flask db init', the Import Error raised. I can't understand why. I checked the code from __init__.py and config.py. Everything seems to be OK. The structure of the project also seems to be OK like in the course.
I will copy here the screen part with Import Error.
And here is the code of config.py and __init__.py.
config.py is located in microblog 
__init__.py is in app

![1](https://user-images.githubusercontent.com/69386656/89708371-39ae0000-d97f-11ea-8b52-c286f7e24d16.png)

[config.py]

```python
import os
basedir = os.path.abspath(os.path.dirname(__file__))

class Config(object):
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
```

[__init__.py]

```python
from flask import Flask
from config import Сonfig
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object("Config")
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app import routes, models
```

**Comment by miguelgrinberg** [comment]
I'm not sure what the error is. I suggest you use direct copies of the files in this repository to see if those work better. There must be some small and difficult to spot typo in your code.

**Comment by PavelDymov** [comment]
Thanks. I decided to create new venv with new folders and copy your code from course to correct folder. And everything now is correct. The command works. But I have also one small question that have a link with that ImportError.
So the main problem is that I write code form your course and study it in computer without Internet Access at work to save my time. Then I take my code to home laptop with internet and try to get results. So that's why may be there were problems with import. And the question is: how to port my venv to computer without internet that it will work correctly. Because when I downloaded the packages and install them with pip install and the path to file they need to download dependences. 
Thank you for your support!

**Comment by miguelgrinberg** [comment]
@PavelDymov you will need to download the packages and all of its dependencies and copy them to the computer without internet to install locally. You may also be able to backup your entire `venv` directory on the computer with internet and then transfer that to the other computer, but you will need to edit the path to the virtual environment in the activation script if it is different in the new computer.
