### ISSUE TITLE
Add support for exceptions for ignoring existant tables.

### ISSUE THREAD

**Issue by guillep19** [miguelgrinberg/Flask-Migrate#36]
When there are already created tables in the database (without sqlalchemy), the table is detected as it existed but was deleted.
Shouldn't there be a way to provide 'exceptional' tables, so they are not detected as deleted?

**Comment by miguelgrinberg** [comment]
Closing, since this is already supported.

**Comment by Sphinxs** [comment]
@miguelgrinberg , can I ignore a table that doesn't exist (how) ? I don't want to create some tables, but I need the structure of them to create and use a decorator to check the user token. When I `migrate` all tables are created, [context](https://github.com/sqlalchemy/sqlalchemy/issues/4478#issuecomment-459106709).

**Comment by miguelgrinberg** [comment]
The advice from Mike is valid. Create your second database not as a bind, but as a completely separate SQLAlchemy instance. Then use Flask-Migrate only on your main SQLAlchemy object and leave the other one alone.
