### ISSUE TITLE
Challenges with schema conflicts

### ISSUE THREAD

**Issue by jmoheywood** [miguelgrinberg/Flask-Migrate#362]
Hi Miguel, 

My co-developer and I have run into conflicts with schemas...

I found your article https://blog.miguelgrinberg.com/post/resolving-database-schema-conflicts which was helpful.

I have now merged, however now getting a different error and can't run an upgrade as 'table already exists'...

Full error: `psycopg2.errors.DuplicateTable: relation "table_name" already exists`

Is there a way to get around this?

Thanks!

**Comment by miguelgrinberg** [comment]
I don't know the particulars, but clearly you have a migration script that is creating a table that already exists in the database. Why is that?

**Comment by jmoheywood** [comment]
Yes - I have now managed to sort - it was a complex conflict where had managed to upgrade previously and then merged.

Had to go through and edit each of the migration files accordingly to get it to work :)

**Comment by miguelgrinberg** [comment]
Yeah, unfortunately that's usually the only way forward.
