### ISSUE TITLE
Ability to poll db to pull current alembic version

### ISSUE THREAD

**Issue by 120GBSSD** [miguelgrinberg/Flask-Migrate#363]
### **Desired Behavior**

When running a new build from Jenkins it creates a new build environment 'flask db init' migration folder and has the ability to poll the database to pull the current alembic version and then perform migration, upgrade, downgrade as needed as the migrations folder is not saved between build environments or between builds.

### **Current Behavior**
I need to remove the current alembic table from the database OR save the migrations folder and move it between builds and build environments to then perform an upgrade otherwise I receive the following complaint.

(venv) root@build1:~/manual_build_dirs/balance_service# flask db migrate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [root] Error: Can't locate revision identified by '42f262e6ba92'

**### Environment**
* Python version: 3.6.9
* Flask-SQLAlchemy version: 2.4.4
* Flask-Migrate version: 2.5.3
* SQLAlchemy version: 1.3.19

**Comment by miguelgrinberg** [comment]
I have several comments to make:

- First of all, this is a wrapper for Alembic. The features that you want, if they get implemented, would not be done by me or in this package. They would be done in Alembic.
- The correct workflow is to save your migrations folder with your source code. You do not run `flask db init` or `flask db migrate` during a build, because all the migrations should be in your code and should not change from one build to the next (except that new migrations might be added at the end)
- It is a really bad practice to reuse the db between builds. You should destroy it completely so that each build starts from a known state.
- Are you familiar with the `flask db stamp` command? You can use it to set the value stored in the alembic_version table anything you want.

**Comment by 120GBSSD** [comment]
Thanks for such a quick response I appreciate it :) 

_First of all, this is a wrapper for Alembic. The features that you want, if they get implemented, would not be done by me or in this package. They would be done in Alembic._

Ah ok sorry my mistake I thought it was here but now I know, thanks for letting me know that.


_The correct workflow is to save your migrations folder with your source code. You do not run flask db init or flask db migrate during a build, because all the migrations should be in your code and should not change from one build to the next (except that new migrations might be added at the end)_

The database updates are not done form a local machine they are being executed on a build server which is also wiped after the build has been completed, during the the pipeline it goes from 2 test env's which have individual db's that are created with the env creation and then the prod env which has a long living db.

once all test env's were passed a prod image was then built where any db changes are pushed to prod and the migrations folder is then sucked into the prod docker image, by the sounds of it though it sounds like i need to setup a multi db migrations folder that lives with the code the whole way through the journey.


_It is a really bad practice to reuse the db between builds. You should destroy it completely so that each build starts from a known state._

Clean db's are created each time an env is created, prod is the only long living db.


_Are you familiar with the flask db stamp command? You can use it to set the value stored in the alembic_version table anything you want._

Ill have a look at this and also explore the multi db function as I was hoping there would be a way around having a long living migrations folder in the repo but if thats what it needs to be then ill set it up to have that as im not overly precious about how this is achieved.

Ill also close this as its the wrong place for it, again cheers for the quick response.
