### ISSUE TITLE
`flask_migrate.upgrade()` breaks logger

### ISSUE THREAD

**Issue by BenjaminPelletier** [miguelgrinberg/Flask-Migrate#364]
I would like to automatically upgrade my database under certain conditions, so I add this code:
```python
app.logger.info('Before block')
with app.app_context():
  app.logger.info('In block')
  flask_migrate.upgrade()
  app.logger.info('Exiting block')
app.logger.info('After block')
```
I expect to see all four statements printed to the log, or at least `Before block` and `After block` at a minimum.  Instead, I see `Before block` and `In block`, but `Exiting block` and `After block` are not printed at all.  Instead, I see something like:

```
INFO:Before block
INFO:In block
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> bd8cf5f2c853, add users
 * Serving Flask app "myapp" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO  [werkzeug]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

I get identical results if I use the built-in logger:
```python
import logging

logging.info('Before block')
with app.app_context():
  logging.info('In block')
  flask_migrate.upgrade()
  logging.info('Exiting block')
logging.info('After block')
```

**Comment by miguelgrinberg** [comment]
This is something that Alembic does, not this extension. You can configure how you want Alembic to log in the `alembic.ini` file. See https://github.com/miguelgrinberg/Flask-Migrate/issues/227 for a related discussion on this topic.
