### ISSUE TITLE
Issue in SQAlchemy stopped allowing me to make changes to a database with flask migrate

### ISSUE THREAD

**Issue by ofw24** [miguelgrinberg/Flask-Migrate#366]
Hello,

I created a pretty basic interface to help with data collection and I was initially able to make changes to the database using `flask db migrate` , but a few weeks ago the database stopped accepting any new changes without any warning. Any time I update/add columns in `models.py` and try creating a new migration, I get an error: `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: image.flag` where in this case flag is the column that I was just trying to add in the migration to the image database. The relevant bits of code are below, it's modeled off of your flask megatutorial which worked fantastically.

View function:
``` 
from flask import render_template, Flask, flash, get_flashed_messages, redirect, url_for
from app import app, db
from app.forms import LoginForm, ImageForm
import datetime
from app.models import Image

@app.route('/image', methods=['GET', 'POST'])
def image():
    imageform = ImageForm()
    fname = 'static/2019-03/camera3/camera3_2019-03-31-17-15-01.jpg'
    img = {'fname':fname}

if imageform.validate_on_submit():
        new_image = Image(date=t_dt, classification=imageform.classification_btns.data,
                          color=imageform.color_btns.data, camera=camera, datestr=datestr, timestr=timestr,
                          user=user)
        db.session.add(new_image)
        db.session.commit()
        flash('Last classification: cloudiness classification: {} and color classification: {}'.format(
            imageform.classification_btns.data, imageform.color_btns.data))
        return redirect(url_for('image'))
    return render_template('image.html', title='Site image', img=fname, user=user, imageform=imageform, dt=datestr, 
        tm=timestr, camera=camera)
```

Database model:
```
from datetime import datetime
from app import db

class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, index=True)
    classification = db.Column(db.Integer)
    color = db.Column(db.Integer)
    camera = db.Column(db.Integer)
    datestr = db.Column(db.String(140))
    timestr = db.Column(db.String(140))
    user = db.Column(db.String(140))
```

Essentially, whenever I'd add the column `flag` to the model and `flag=imageform.flag_btn.data` to the line where I generate a new Image object and tried to run a migration it wouldn't recognize the new column. It worked without a hitch up until a few weeks ago, when I tried this migration and it stopped working.

Any help is appreciated, thanks so much!

**Comment by miguelgrinberg** [comment]
I need to see the stack trace of the error. The problem is likely in your application or in a previous migration file.

**Comment by ofw24** [comment]
I just realized that I never got back to this comment. It turns out that the issue was in a snippet where I tried counting the number of entries in the database. All I needed to do was remove those few lines, update the database, then reinsert those lines and then the db worked fine. Not sure why that was the issue, but glad it was resolved. Thanks!
