### ISSUE TITLE
db migrate drop all tables in my database

### ISSUE THREAD

**Issue by lsm-5** [miguelgrinberg/Flask-Migrate#367]
First of all, thanks for building this tool, Miguel.

I am starting to use this tool and I have seen your video explaining how to add it to an existing project, I have also researched the issues here and have not yet detected a way to solve my problem.

My problem is this, I imported flask-migrate into my project and started it, but every time I run 'python app.py db migrate', the migration created suggests that I remove all of my tables, as shown in the image.

![image](https://user-images.githubusercontent.com/32796404/93134129-b0d96100-f6ae-11ea-9766-e6d8f46feddd.png)

I already saw that it may be a problem with the models' initialization, so it doesn't identify it, but I already put imports in the app.run even without using them and even so I still want to delete all tables.

app.py
```python
from flask_login import LoginManager
from flask import Flask, jsonify, request, Response
from flask_cors import CORS, cross_origin
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from settings import app
from routes.UserRoutes import *
from routes.TutorRoutes import *
from routes.AssistedRoutes import *
from routes.ScheduleRoutes import *
from routes.MedicineRoutes import *

CORS(app, resources={r"/medicines/*": {"origins": "*"},
                     r"/schedules/*": {"origins": "*"},
                     r"/persons/*": {"origins": "*"},
                     r"/tutors/*": {"origins": "*"},
                     r"/assisted/*": {"origins": "*"}
                     })
CORS_HEADERS = 'Content-Type'

db = SQLAlchemy()
migrate = Migrate()
manager = Manager(app)
manager.add_command('db', MigrateCommand)
login_manager = LoginManager()

from models.AssistedTutorModel import Assisted, Tutor, User, TutorNetwork, AssistedTutor
from models.MedicineModel import Medicine, ActiveIngredient
from models.ScheduleModel import Medicine, Schedule, ScheduleMedicine, Assisted
from models.UserModel import User

def create_app():
    db.init_app(app)
    migrate.init_app(app, db)

    login_manager.session_protection = 'strong'
    login_manager.init_app(app)
    login_manager.login_view = '/login'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter_by(id=int(user_id)).first()

    # with app.app_context():
    # Extensions like Flask-SQLAlchemy now know what the "current" app
    # is while within this block. Therefore, you can now run........
    # db.create_all()
    return app


if __name__ == "__main__":
    app = create_app()
    manager.run()
```

I also thought it was an initial migration problem so I ran the command 'python app.py db stamp head' but it doesn't work.

I found that my database already has an alembic table.

![image](https://user-images.githubusercontent.com/32796404/93134904-d5820880-f6af-11ea-823a-2f47e0740e16.png)

and to finish my models are organized as follows:

part of the code

```python
import json
from sqlalchemy.orm import backref, relationship

from settings import app
from .Orm import Base
from .MedicineModel import Medicine
from .AssistedTutorModel import Assisted

db = SQLAlchemy(app)


class ScheduleMedicine(db.Model):
    __bind_key__ = 'ScheduleDB'
    __tablename__ = 'ScheduleMedicine'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    schedule_id = db.Column(db.Integer, nullable=False)
```

thanks for your attention!

**Comment by miguelgrinberg** [comment]
You have multiple `db` instances in your application. You should use only one, that is imported in all the places you need it.
