### ISSUE TITLE
Usage with plain SQLAlchemy

### ISSUE THREAD

**Issue by spichkaa** [miguelgrinberg/Flask-Migrate#368]
Is it possible to use Flask-Migrate with SQLAlchemy, not the "Flask-SQLAlchemy"? If so, what should I pass to migrate.init_app(app, db) instead of 'db'?
Thanks in advance!

**Comment by miguelgrinberg** [comment]
No, this extension works with Flask-SQLAlchemy only. Sorry.

**Comment by spichkaa** [comment]
Gotcha, thanks!
