### ISSUE TITLE
Schema conflict 

### ISSUE THREAD

**Issue by sp1rs** [miguelgrinberg/Flask-Migrate#371]
I have a particular situation.

1. My friend add the migration on Branch1 and tested on the staging environment. 
Now staging has new revision.

2. In the meantime, I tested my change on Branch2 and tried to push it on staging, but failed since `flask db upgrade` will fail.

How to manage such type of situation?

**Comment by miguelgrinberg** [comment]
I'm not sure I can give you a great answer here. My opinion is that a staging environment should not have unfinished features. I don't think it is a good idea to have a shared deployment where developers can deploy unfinished changes, as that creates a management nightmare.

Things you can do:

- When a developer deploys to your staging environment the database is recreated from scratch,
- Or when a developer finishes testing on the staging environment it restores the deployment back to the latest official release.
- Or you allocate separate staging deployments for each developer.
- Or you require that to deploy to staging the code must be on committed to the main branch (which would enable other developers to merge any new migrations).
