### ISSUE TITLE
Add additional database after db init has been run - Stam Head Issue

### ISSUE THREAD

**Issue by Daniel-UWAA** [miguelgrinberg/Flask-Migrate#372]
I've been following your instructions to add a new database from here:
https://github.com/miguelgrinberg/Flask-Migrate/issues/179

Whenever I run the `flask db stamp head ` it raises the following error

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked

Would you know why this is happening?

**Comment by miguelgrinberg** [comment]
Your database file is locked, I don't think this is related to the stamp command, it's just that the file cannot be opened because some other process has an exclusive lock on it.

**Comment by Daniel-UWAA** [comment]
I was using DB Browser (SQLite). To be sure, I've restarted my computer and run the instructions again from Issue #179 . I still get the error though.

Could it be that I'm using two SQLite databases?

**Comment by miguelgrinberg** [comment]
I don't really know, but if you have the databases open in a third party db administration tool then maybe that's the problem. But as I said, this is not related to Flask-Migrate, the database cannot even be open due to this lock held by another client.

**Comment by Daniel-UWAA** [comment]
I've managed to fix the issue. I forgot to put the __bind_key__ referencing the new database. As the model had the same name as the 'base' database, I think that was causing the error
