### ISSUE TITLE
Errors aren't logged by application

### ISSUE THREAD

**Issue by maquino1985** [miguelgrinberg/Flask-Migrate#373]
Your logging should declare a logger name, otherwise it will clash with other logging configurations used by your consumers and not display any information in the console,

e.g. 
__init__.py 
line 17:
change
log = logging.getLogger() to log = logging.getLogger(__name__)

**Comment by miguelgrinberg** [comment]
Sounds good. Would you like to submit a pull request with this change?

**Comment by miguelgrinberg** [comment]
Fixed in #374
