### ISSUE TITLE
alter declarative columns with flask migrate

### ISSUE THREAD

**Issue by waakanni** [miguelgrinberg/Flask-Migrate#377]
Hi,

I wonder if you cold help. I have the follow model classes:

```
class SampleRequiredMetadataMixin(object):
    ena_ers_sample_id = db.Column(db.String, unique=True)
    
    @declared_attr
    def sample_type(self):
        return db.Column(db.String, server_default=self.__class__.__name__)

class MasterSample(SampleRequiredMetadataMixin, Dictable, db.Model):
    """
        .....
    """
    __tablename__ = 'master_sample'
    __display_columns__ = ['sample_id', 'environment_material', 'timepoint',
                           'geographic_location', 'environment_feature']
    __csv_columns__ = [ 'environmental_package', 'latitude', 'longitude', 'sample_type', 'tax_id', 'tax_scientific_name']
```
I would like to change the column name of the callable method `sample_type` to:
```
     @declared_attr
     def new_sample_type(self):
         return db.Column(db.String, server_default=self.__class__.__name__)
```

After making this change in the code, I run 
`flask db migrate --message "rename sample_type column"`
which return:
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```
It seems it is not picking up the change in the model code
Any suggestions?

Thank you

**Comment by miguelgrinberg** [comment]
This would be a question for the Alembic team, Flask-Migrate is just a Flask friendly wrapper for Alembic and it has nothing to do with actual database migrations. I'm not sure if Alembic picks up declared attributes, but you can always hand edit your changes into your migration.

**Comment by waakanni** [comment]
Thank you for the reply. 

Yes, I ended up just creating a revision migration and editing it manually. ;)

Happy holiday!
