### ISSUE TITLE
3rd-party dependency problem (missing import) 

### ISSUE THREAD

**Issue by muffmolch** [miguelgrinberg/Flask-Migrate#383]
Hi Miguel
I have got a problem. I try to use flask_authorize. Also I don't get any error at _flask db upgrade_, no tables have been created.
I tokk a closer look at the migration file and found the problem at:

~~~py
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('groups_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('desc', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('restrictions', flask_authorize.mixins.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('end_transaction_date', sa.DateTime(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
~~~

sa.Column('restrictions', **flask_authorize**.mixins.JSON(), autoincrement=False, nullable=True)

But there's no **import flask_authorize**

How can thus problems be solved? And how do I get the errors at during the migration?

**Comment by miguelgrinberg** [comment]
Just add the import by hand.

**Comment by muffmolch** [comment]
Thanks a lot!

**Comment by muffmolch** [comment]
> Just add the import by hand on the migration file. Alembic isn't always able to generate correct code, you can fix it yourself.

Directly into the versions file? O

**Comment by miguelgrinberg** [comment]
Yes, add it in the generated migration script. These files are supposed to be reviewed and hand-edited to be accurate.
