### ISSUE TITLE
Can't add migrations on table generated with db.create_all()

### ISSUE THREAD

**Issue by luap42** [miguelgrinberg/Flask-Migrate#385]
Hey everyone,

first of all thanks for the generally awesome migration tool.

For my local development I'm using Flask-Migrate with Flask-SQLAlchemy on a SQLite database. On production I plan to use MySQL though.

Now I have come across an issue, when there is a database change, SQLite can't handle (deleting columns). Naturally, the `flask db upgrade` failed. So I tried to fix the issue by editing the deletion rule out of the migration, running it and re-adding it. That kind of worked, but now the relevant column deletion will be added to every future migration (I assume, because it compares the model to the DB).

Therefore I tried to delete my development database and to recreate it. To do so, I seem to have two options:

1. Run `flask db upgrade` to apply all migrations in order and to get a clean database.
2. Run `db.create_all()` in my code, to create all tables from the model.

However, both methods do not work for me.

1. doesn't work, because the drop column migration still fails, as it is still not supported by SQLite.
2. doesn't work either, because now the upgrade tool is complaining about tables already existing. And the migration tool is complaining about the target database not being up to date.

How can I bring my database back in order and continue making migrations? The (most likely) easiest solution I've been looking for, was to trick Flask-Migrate into "thinking", that all migrations have already been run.

I can create provide a minimum reproducible example, if this is deemed neccessary.

Thanks in advance for helping me!  
luap

**Comment by miguelgrinberg** [comment]
Have you seen the `flask db stamp` command?

**Comment by luap42** [comment]
Oh thank you very much! That's exactly what I had been looking for.

Weird. I am sure I haven't seen it on the list shown at `flask db` before, but it definitely is there now ;)
