### ISSUE TITLE
Is it possible to ignore a table not in models.py when auto-generating migration scripts?

### ISSUE THREAD

**Issue by y-himanen** [miguelgrinberg/Flask-Migrate#386]
Hello!

We have a project where we are using a models.py file and a separate python script to manage our database. 

We have both straightforward tables for adding information that we get from the users of our app, but also a reasonably large table with data read from a CSV file. This table, along with all its data was added with a separate script using pandas, so it does not exist in our models.py file at all. For reasons specific to the project, the column names are also read in from the CSV rather than hard-coded.

We obviously don't want to run this script and re-add tens of thousands of rows of data every time we make changes to our other tables, so it's only run as and when this data is changed (very very infrequently). This means that when we run migrations, Alembic generates a drop command for this particular table. 

Editing the migration script is straightforward enough, and this is what we have been doing before running upgrade to ensure that this table isn't actually dropped. However, is it possible to have this table ignored completely when generating the migration scripts, so that we would not have to go in and manually delete the drop command?

Grateful for any help or advice.

Best,
Yasmine

**Comment by miguelgrinberg** [comment]
This is an Alembic question, not Flask-Migrate. You can use the [include_object](https://alembic.sqlalchemy.org/en/latest/api/runtime.html?highlight=include_object#alembic.runtime.environment.EnvironmentContext.configure.params.include_object) directive to provide a callback function that determines which tables are considered for autogenerated migrations.

**Comment by y-himanen** [comment]
Thanks for your help.
