### ISSUE TITLE
Multiple heads are no longer detected as an issue, silent fail instead

### ISSUE THREAD

**Issue by viorelspinu** [miguelgrinberg/Flask-Migrate#387]
**Affected version:** 
flask-migrate==2.7.0

**Steps to reproduce:** 

1. create a revision: "flask db revision -m "some_revision"
2. move the file created by alembic outside of your project (e.g. on Desktop)
3. create another revision: "flask db revision -m "some_other_revision"
4. move the first file back
4. run "flask db upgrade"

**Expected behaviour:**
As now you have two heads, the upgrade operation should explicitly fail with an error message.

**What it happens instead:**
Nothing happens, no error is reported.

**Additional checks:**
Having the two heads still active, drop all tables and run "flask db upgrade". You would expect either your tables to be created, or an error message on the two heads to be displayed. Instead, nothing happens (silent fail). You delete the two new files which introduced the two heads issues. As expected, your tables are being created.

**Comment by miguelgrinberg** [comment]
There were some bugs in the logging configuration in the past. Are you using a brand new migration repository or an old one created some time ago? If it is older, the alembic.ini might need to be refreshed. See the version in the flask_migrate/templates/flask directory.

**Comment by viorelspinu** [comment]
Thanks, Miguel. Adding the logger fixes this issue.
