### ISSUE TITLE
Add echo to env.py template

### ISSUE THREAD

**Issue by delijati** [miguelgrinberg/Flask-Migrate#39]
`SQLALCHEMY_ECHO` should be added to `env.py`

I use this line:
```python
config.set_main_option('sqlalchemy.echo',
                       str(current_app.config.get('SQLALCHEMY_ECHO', True)).lower())
```

**Comment by miguelgrinberg** [comment]
Also, you can use the `--sql` option to dump the SQL for upgrade/downgrade migrations to stdout as way of dry run.
