### ISSUE TITLE
`Flask-Migrate` uses abandoned project `Flask-Script`

### ISSUE THREAD

**Issue by jugmac00** [miguelgrinberg/Flask-Migrate#398]
The latter is no longer maintained for years, and also issues an deprecation warning, which may break the app in future:

```
/home/jugmac00/Projects/Flask-Migrate/.tox/py39/lib/python3.9/site-packages/flask_script/commands.py:118: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, defaults = inspect.getargspec(func)
../home/jugmac00/Projects/Flask-Migrate/.tox/py39/lib/python3.9/site-packages/flask_script/commands.py:118: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, defaults = inspect.getargspec(func)
```

I noticed that when running the tests with `unittest` testrunner, as this one shows deprecation warnings, unlike `python setup.py tests`, also see https://github.com/miguelgrinberg/Flask-Migrate/pull/397

**Comment by miguelgrinberg** [comment]
Flask-Script is optional, so claiming that this project "uses" it is incorrect.

**Comment by jugmac00** [comment]
Right! I should have looked into `setup.py`.
