### ISSUE TITLE
Alembic does not detect models.

### ISSUE THREAD

**Issue by brotatos** [miguelgrinberg/Flask-Migrate#4]
I set up Flask-Migrate using your suggested changes to `__init__.py` and initialized the migrations and attempted to generate a file. However, this migration showed no changes to the db even though I had clearly added a users table.

``` bash
.
├── Procfile
├── README.md
├── TODO.md
├── bin
├── calpoly
├── config.pyc
├── flask_migrate
├── include
├── lib
├── manage.py
├── migrations
├── requirements.txt
├── run.py
└── runtime.txt
```

Here's the migration:

``` py
"""empty message

Revision ID: 2812f95cc1be
Revises: None
Create Date: 2013-09-17 23:05:53.508999

"""

# revision identifiers, used by Alembic.
revision = '2812f95cc1be'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
```

And finally, the [code](https://github.com/brotatos/ieee/tree/add-users).

**Comment by iUwej** [comment]
@brotatos you need to run `alembic upgrade head` to avoid the `alembic.util.CommandError: Target database is not up to date.`
I suppose the tool requires you apply existing migrations before creating new ones

**Comment by notfresh** [comment]
One more tip, I met the same problem, but my solution is to check the module load order.

if your model definition python script,( such as XXX.py)  is not in the app init load process, it will not find the model you create. 

The case like, you import db to app.py and use db.init(app), but the model definition is ingnored. 
so you better import the model-define python script into your app.py.

**Comment by push001** [comment]
For my first Database migration. I was facing some error after "flask db migrate -m "users table". Then I set FLASK_APP to the value microblog.py Then error was resolved and got the output as yours.

My doubt: When I have followed all the steps for "automatic import of envirnoment variable" and created ".flaskenv" then why am I supposed to set FLASK_APP value manually. Am I missing something?

**Comment by miguelgrinberg** [comment]
> When I have followed all the steps for "automatic import of envirnoment variable" and created ".flaskenv" then why am I supposed to set FLASK_APP value manually.

If you have python-dotenv installed in your environment and have a .flaskenv file, then there is no need to manually set FLASK_APP.
