### ISSUE TITLE
Remove legacy flask-script CLI

### ISSUE THREAD

**Issue by ThiefMaster** [miguelgrinberg/Flask-Migrate#403]
Flask-Script is dead - no release since 4 years and the github repo has been archived, and it's no longer compatible with the latest Flask 2.0 release.

This might be a good opportunity to remove support for it from flask-migrate as well.

**Comment by miguelgrinberg** [comment]
Yes, this is good motivation to finally do it. Thanks.

**Comment by loleg** [comment]
Could you, please, remove the Flask-Script section from the docs - perhaps with a deprecation tip (like a link to [this article](https://blog.miguelgrinberg.com/post/migrating-from-flask-script-to-the-new-flask-cli)). The release notes should also mention this.

**Comment by miguelgrinberg** [comment]
@loleg Sorry, forgot to update the docs. All references to Flask-Script are now removed.

**Comment by loleg** [comment]
Thank you, great!
