### ISSUE TITLE
ImportError: cannot import name 'MigrateCommand'

### ISSUE THREAD

**Issue by yulihav** [miguelgrinberg/Flask-Migrate#406]
I started getting an error in a repo that I'm maintaining:
```
Traceback (most recent call last):
  File "registry/manage.py", line 3, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: cannot import name 'MigrateCommand'
```

This is how the command is used in code:
```
app = Flask(__name__)
ApplicationConfiguration.load()
app.config['SQLALCHEMY_DATABASE_URI'] = ApplicationConfiguration.get_db_uri()
DatabaseService.init_db(app)

migrate = Migrate(app, DatabaseService.db())
manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```
The person who wrote this code is no longer here and I can't find documentation on `MigrateCommand` in your docs. Has this been deprecated? What should it be replaced with?

**Comment by miguelgrinberg** [comment]
Flask-Script is not supported anymore. You have to use an older release, or else migrate to the Flask CLI.

**Comment by prowler0305** [comment]
Could you give some advice on how to use the Flask CLI commands in order to execute the "DB" commands like migrate and upgrade similiar to the way it was with Flask-Script. The doc doesn't really cover this other than they are there, but not sure how to invoke them programmatically through my app. I used to just pass the argument `db upgrade` or `db migrate` to my `python app.py` command. 

Unless this already exists somewhere in the documentation and I missed it.

Thank you.

**Comment by miguelgrinberg** [comment]
@prowler0305 the same commands are available through the Flask CLI. Like for example, `flask db migrate`, `flask db upgrade`, etc.

**Comment by matuskosut** [comment]
@prowler0305 if you haven't solved it, or for anyone intersted

I was using flask_script only for one subcommand of `myflaskapp` like this:
```
if len(sys.argv) > 1 and sys.argv[1] == 'db':
    from flask_script import Manager
    from flask_migrate import MigrateCommand
    from myflaskapp.models import db, migrate  # noqa
    app = create_app(__name__)
    manager = Manager(app)
    manager.add_command('db', MigrateCommand)
    manager.run()
```

Easiest way to keep that functionality seems to be embedding flask cli. It is also possible to adjust to other commands beside just limiting db subcommand.
```
if len(sys.argv) > 1 and sys.argv[1] == 'db':
        from flask.cli import cli
        cli.main(args=sys.argv[1:])
```

It makes it simpler while still allowing same usage:
```
myflaskapp db --help
```
