### ISSUE TITLE
cannot import name 'MigrateCommand' from 'flask_migrate'

### ISSUE THREAD

**Issue by vanloctech** [miguelgrinberg/Flask-Migrate#407]
File "manage.py", line 4, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: cannot import name 'MigrateCommand' from 'flask_migrate'

**Comment by miguelgrinberg** [comment]
Flask-Script is not supported anymore. Switch to the Flask CLI or downgrade Flask-Migrate to an older version.
