### ISSUE TITLE
Regarding the execution of db migrate and db upgrade, after reporting the sqlalchemy.exc.ProgrammingError SQL statement, even if db migrate is executed again after correcting the model, db upgrade cannot retrieve the latest version.

### ISSUE THREAD

**Issue by yangyuexiong** [miguelgrinberg/Flask-Migrate#408]
Regarding the execution of db migrate and db upgrade, after the sqlalchemy.exc.ProgrammingError SQL statement is reported, even if you execute db migrate again after correcting the model, db upgrade cannot retrieve the latest version because there is already an error in the folder migrations/versions/xxxx.py How to solve the migration? At present, I manually delete the wrongly migrated xxxx.py, and then re-execute db migrate and db upgrade. Is there a better solution?

For example

class Order(BaseModel):
    __tablename__ = 'ec_order'
    __table_args__ = {'comment': 'order'}
    order_type_1 = db.Column(db.String(32), server_default=text('NORMAL'))

Get sql statement
[SQL: ALTER TABLE ec_order ADD COLUMN order_type_1 VARCHAR(32)  DEFAULT NORMAL]

class Order(BaseModel):
    __tablename__ = 'ec_order'
    __table_args__ = {'comment': 'order'}
    order_type_1 = db.Column(db.String(32), server_default=text("'NORMAL'"))

Get sql statement
[SQL: ALTER TABLE ec_order ADD COLUMN order_type_1 VARCHAR(32)  DEFAULT "NORMAL"]

Correction from server_default=text('NORMAL')  to server_default=text("'NORMAL'")  Reproduce the above problem

**Comment by miguelgrinberg** [comment]
Deleting the bad migration file is the correct solution.

**Comment by yangyuexiong** [comment]
ok
