### ISSUE TITLE
Is There a way to ignore a model not to generate op.create_table for the model?

### ISSUE THREAD

**Issue by ericleemz** [miguelgrinberg/Flask-Migrate#410]
I'm using multiple databases with MySQL and BigQuery by declaring the binds

```
SQLALCHEMY_BINDS = {
     'bigquery': BIGQUERY_URI,
}
```

```
app = Flask(__name__)
from models import db, migrate
db.init_app(app)
migrate.init_app(app=app, db=db)
```

the bigquery table is already created but when I execute `flask db migrate` It generate create_table function with bigquery table in a migration file.

Is there a way to prevent or ignore models not to generate a migration file?

**Comment by miguelgrinberg** [comment]
Yes, the `include_object` option from Alembic can do this. See [this issue](https://github.com/miguelgrinberg/Flask-Migrate/issues/270) for an example.

**Comment by ericleemz** [comment]
Thanks! It was really helpful!!
I was trying to declare Sqlalchemy() twice for mysql db and bigquery db to migrate only mysql.
but this way is a lot easy!
