### ISSUE TITLE
Migrate question,  duplicate UniqueConstraint

### ISSUE THREAD

**Issue by onlyone-tsq** [miguelgrinberg/Flask-Migrate#411]
Hello,

I found that migrate operation generated duplicate UniqueConstraint.

Flask-Migrate 3.0.1

My models:

```
class User(db.Model):
    __tablename__ = 'user'
    id = db.Column('id', db.Integer, primary_key=True)
    username = db.Column('username', db.String(64), unique=True, nullable=False)
    password = db.Column('password', db.String(128))
```

flask run migrate

migrations/versions/3c5ce55b6808_.py

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
```

There are two UniqueConstraint('username') in function upgrade().

Please help to deal with it, thank you!

**Comment by miguelgrinberg** [comment]
Wrong project. Alembic generates your migrations. This project is just a wrapper that configures Alembic to work with your Flask application.

I suggest you fix this manually in your migration script, and if you feel this is a bug in Alembic, then report it on their project.
