### ISSUE TITLE
QUESTION: Not able to rename a Table name.

### ISSUE THREAD

**Issue by aalokrmb** [miguelgrinberg/Flask-Migrate#413]
Whenever I try to rename a table name it actually doesn't run op.rename, but deletes the table and creates a new table.
Now In my case, I don't want my existing data to be gone, I want it to persistent but whenever I just rename the model and run `flask db migrate` and then` flask db upgrade`, I encountered this error: 

`sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1217, 'Cannot delete or update a parent row: a foreign key constraint fails')
[SQL: 
DROP TABLE person]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
`

**Comment by miguelgrinberg** [comment]
Did you try editing the migration script to do a rename instead of of delete and a create? Alembic cannot know what you want to do, it does its best to generate a migration, it is your job to make it 100% accurate.

**Comment by aalokrmb** [comment]
> Did you try editing the migration script to do a rename instead of delete and a create? Alembic cannot know what you want to do, it does its best to generate a migration, it is your job to make it 100% accurate.

Okay, Just one more thing, is there any command to create a script empty file just with the upgrade and downgrade function nothing else? so that we can write our own alembic code manually over there Like I want to rename almost 10 tables, so I just run a command which generates an empty file, and then I can call the op.rename function manually in that file for the 10 tables which I want to rename.

**Comment by miguelgrinberg** [comment]
@aalokrmb Yes, use `flask db revision` for that.

**Comment by aalokrmb** [comment]
> @aalokrmb Yes, use `flask db revision` for that.

It worked, Great, thanks for the help.
