### ISSUE TITLE
My first migration script seems back to front.

### ISSUE THREAD

**Issue by derekpa** [miguelgrinberg/Flask-Migrate#42]
I have an existing database with data. I installed Flask_Migrate as per the docs.

First I ran a db init which created the environment, then (assuming this is correct when you have an existing DB) ran an initial migrate to capture the current state of the database. This produced a migrations script which seemed back to front. That is, upgrade function drops all the tables, downgrade creates them (ie the database I started with) This is the exact opposite of what I've seen elsewhere with an example using just alembic, where downgrade drops all the table, which makes sense.

Is this right?

**Comment by miguelgrinberg** [comment]
No, this is not expected.

If you've got all table drops, that means that Alembic is able to see the database, but it is not seeing any models, so it thinks all the models have been removed from the database. You are probably not importing models in the right place for Flask-Migrate/Alembic to see.

**Comment by derekpa** [comment]
But it has the correct commands to build the tables in the downgrade. How can it do that if it can't see the tables?

**Comment by derekpa** [comment]
OK, now just getting a list of unique constraints, so I suppose that's fixed my initial problem. Thanks :-)
