### ISSUE TITLE
ModuleNotFoundError: No module named 'flask._compat'

### ISSUE THREAD

**Issue by RyanAquino** [miguelgrinberg/Flask-Migrate#423]
Error encountered when using Flask v2+. 

Answer stated here https://stackoverflow.com/a/67874648/8153960 temporary fixes the issue. But I think its not the proper solution since it instructing to edit the package files. We should have the proper fix on the package itself and to have support on Flask v2 and future versions.

**Comment by miguelgrinberg** [comment]
First of all, Flask-Script is not supported anymore.

Second, the fix that you linked to has to be made on the Flask-Script source files, Flask-Migrate has nothing to do with the error or the fix. Flask-Migrate is 100% compatible with Flask 2.
