### ISSUE TITLE
running migration has no affect

### ISSUE THREAD

**Issue by radiantone** [miguelgrinberg/Flask-Migrate#424]
Hi,
  I run flask-migrate programmatically. I add a Column to one of my database models. Then run the migration. database has not changed.

```
    from flask_migrate import Migrate, init as migrate_init, upgrade as migrate_upgrade

    migrate = Migrate(app, database)
    migrate_init(directory='migration')
    migrate_upgrade(directory='migration')
```

Version 3.0.1

**Comment by miguelgrinberg** [comment]
You are not generating a migration. You may want to review how to work with this extension and Alembic using the CLI, then you may be able to create a scripted solution around the correct workflow.

**Comment by radiantone** [comment]
Unfortunately, the documentation is not detailed enough. Also I cannot use the flask cli. I was able to find this answer, which I followed and it did not work. Thus, here I am
https://stackoverflow.com/questions/44961622/how-to-call-flask-migrate-api-in-script

**Comment by radiantone** [comment]
I think I found the missing function
