### ISSUE TITLE
Handling changes to enum types

### ISSUE THREAD

**Issue by derekpa** [miguelgrinberg/Flask-Migrate#43]
Hi,

I know this is a limitation of Alembic but thought you might know the answer. How would you handle changes to enum types?

Cheers!

**Comment by miguelgrinberg** [comment]
I haven't tried this on enums, but you should be able to use Alembic's `alter_column()` function to change the column's type.

**Comment by derekpa** [comment]
OK, actually that doesn't seem to work. It was suggested by the owner of alembic to use raw SQL.

Looks like using enum in a DB isn't necessarily a good idea anyway, so might consider replacing with reference tables.

Thanks anyway :-)

**Comment by Devking** [comment]
@derekpa It's been a while, but can you cite where the owner of alembic has said to use raw SQL?

**Comment by derekpa** [comment]
@Devking No, he suggested just using alter column, so in Mysql -

`op.alter_column("my_table", "my_column", existing_type=ENUM(...), type_=ENUM())`

Hope that helps.

**Comment by bbbart** [comment]
I just wanted to create an issue for this and then found this discussion here. I just stumbled over this, that flask-migrate (alembic) didn't catch the addition of a few lines to an Enum class to alter the corresponding db.Enum() column constraint, resulting in exceptions from SQLAlchemy.

Any chance of supporting this, or is this a question for Alembic directly?

**Comment by miguelgrinberg** [comment]
@bbbart this package does not know anything about the actual migrations, it's just a wrapper for Alembic. So yeah, this is all in Alembic's camp.

**Comment by bbbart** [comment]
got it, thanks.
