### ISSUE TITLE
Flask Migrate does not detect string column length changes on SQL alchemy objects

### ISSUE THREAD

**Issue by nlapierre-isp** [miguelgrinberg/Flask-Migrate#430]
Using SQL-Alchemy v2.5.1, Flask-Migrate v3.1.0
```
class Foo(db.model):
    __tablename__ = 'foo'
     id = db.Column(db.Integer, primary_key=True)
     name = db.Column(db.String(100), nullable=False, unique=True)
```
To
```
class Foo(db.model):
    __tablename__ = 'foo'
     id = db.Column(db.Integer, primary_key=True)
     name = db.Column(db.String(255), nullable=False, unique=True)
```
After running `flask db upgrade` to ensure all the current migrations are applied to the database, running a `flask db migrate` results in:

INFO  [alembic.env] No changes in schema detected.

**Comment by miguelgrinberg** [comment]
Alembic does not detect column type changes by default. You have to enable this as follows:

```python
migrate = Migrate(app, db, compare_type=True)
```

**Comment by Adithya-K-Shetty** [comment]
Thanks @miguelgrinberg

**Comment by linuxmathew** [comment]
Thanks, @miguelgrinberg ... you are a lifesaver :100:

**Comment by yeboah326** [comment]
Thanks @miguelgrinberg
