### ISSUE TITLE
Flask `MigrateCommand` import error

### ISSUE THREAD

**Issue by mbrsagor** [miguelgrinberg/Flask-Migrate#431]
from main import app, db
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()

**Comment by miguelgrinberg** [comment]
It's easy to search the issues to see if someone already had the same problem.

See #406 or #407 or #425.
