### ISSUE TITLE
Adding Boolean column to sqlite table using flask migration

### ISSUE THREAD

**Issue by SahooAshis** [miguelgrinberg/Flask-Migrate#437]
I'm trying to add a new Boolean column to the SQLite database using flask migration. But getting [SQL: ALTER TABLE post ADD COLUMN private BOOLEAN NOT NULL] error even though I have specified default=False.

**private = db.Column(db.Boolean, nullable=False, default=False) **

Find below the complete Model code

```
class Post(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	title = db.Column(db.String(100),nullable=False)
	date_posted = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
	content = db.Column(db.Text,nullable=False)
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)
	img = db.Column(db.String(20), nullable=True)
	private = db.Column(db.Boolean, nullable=False, default=False)   
```

**Comment by miguelgrinberg** [comment]
This has been asked several times already. For example: https://github.com/miguelgrinberg/Flask-Migrate/issues/254.

**Comment by SahooAshis** [comment]
The table was altered by replacing default=False with server_default='false'. However, when I'm querying the boolean value it is always returning True. 

@miguelgrinberg Is there something wrong with the server_default='false' parameter?

**Comment by miguelgrinberg** [comment]
@SahooAshis I don't think so. You may want to look for answers in Alembic forums, because that is the package that generates the migrations. Flask-Migrate is a wrapper to make Alembic easier to use under Flask.

**Comment by SahooAshis** [comment]
> @SahooAshis I don't think so. You may want to look for answers in Alembic forums because that is the package that generates the migrations. Flask-Migrate is a wrapper to make Alembic easier to use under Flask.

For the Boolean field, server_default should be '0' for False and '1' for True. Any other string value will be treated as True

**Comment by miguelgrinberg** [comment]
@SahooAshis That depends on the database that you are using.
