### ISSUE TITLE
No changes in schema detected

### ISSUE THREAD

**Issue by jadsonbr** [miguelgrinberg/Flask-Migrate#442]
I'm doing all the configuration but I don't get the initial migration file.

```bash
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.env] No changes in schema detected.
```

Here is the boot code

```python
from flask import Flask
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session
from sqlalchemy.orm import sessionmaker
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from paranoid.models import Query
from paranoid.models import Session
from config import Config

engine = create_engine(Config.SQLALCHEMY_DATABASE_URI)
session = scoped_session(sessionmaker(bind=engine, class_=Session, query_cls=Query))
db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    migrate.init_app(app, db)    
    app.logger.info('Backend startup')
    return app

from app import models
```
requirements.txt
```
alembic==1.6.5
Flask-Migrate==3.0.1
Flask-SQLAlchemy==2.5.1
psycopg2
sqla-paranoid
SQLAlchemy==1.4.20
SQLAlchemy-SQLSchema
sqlalchemy-utils
Werkzeug
Flask==2.0.1
psycopg2-binary
requests
flask_cors
flask-shell-ipython==0.4.1
python-dotenv==0.19.0
marshmallow
```

I use the [sqla-paranoid](https://github.com/jeanphix/sqla-paranoid) library for soft delete with SQLAlchemy

Follow the example application to reproduce
[example-application.zip](https://github.com/miguelgrinberg/Flask-Migrate/files/7281080/example-application.zip)

**Comment by miguelgrinberg** [comment]
> I'm doing all the configuration

Impossible for me to check what you are doing if you don't provide details.

**Comment by jadsonbr** [comment]
It has an attachment like the whole project that has the same behavior of not generating the initial migration

**Comment by miguelgrinberg** [comment]
The issue is with your database very likely, not with the code.

**Comment by jadsonbr** [comment]
It is a new database with only public and auth schema created without any tables. After running the migration command the alembic_version table in public is generated but no migration files are generated.

**Comment by miguelgrinberg** [comment]
Then you are not importing the models into the application.

**Comment by jadsonbr** [comment]
Inside `app\__init__.py` I added `from app import models`

**Comment by miguelgrinberg** [comment]
Okay. The problem is that you are not using Flask-SQLAlchemy for your models, you are creating your own declarative base. So none of your models is seen by Flask-SQLAlchemy and Flask-Migrate.

**Comment by jadsonbr** [comment]
I use sqla-paranoid to implement soft delete and the library uses SQLAlchemy for that. Unless you have to explicitly enter only `db.Model`.

Here is the model startup trace via the paranoid lib

1) [Model = model_factory()](https://github.com/jeanphix/sqla-paranoid/blob/dev/paranoid/models.py#L162)
2) [def model_factory(BaseModel=BaseModel)](https://github.com/jeanphix/sqla-paranoid/blob/dev/paranoid/models.py#L110)
3) [BaseModel = declarative_base()](https://github.com/jeanphix/sqla-paranoid/blob/dev/paranoid/models.py#L107)


[Direct import from sqlalchemy](https://github.com/jeanphix/sqla-paranoid/blob/dev/paranoid/models.py#L13)
```python
from sqlalchemy.ext.declarative import (
    declared_attr,
    declarative_base,
)
```

**Comment by jadsonbr** [comment]
Solved using imports below

```python
from paranoid.flask import SQLAlchemy

db = SQLAlchemy()
Model = db.Model
```
