### ISSUE TITLE
Identifying and dealing with potentially reserved names (i.e. in MySQL)

### ISSUE THREAD

**Issue by andreit23** [miguelgrinberg/Flask-Migrate#446]
I ran into an issue deploying a project on Linux using MySQL.
I had named one of my tables "Lead" which didn't go well with MySQL on Ubuntu 20.

Didn't have trouble on Windows though.

Here is the initial error:

        sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lead (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\t`fName` VARCHAR(64), \n\t`lName` VAR' at line 1")
        [SQL:
        CREATE TABLE lead (
                id INTEGER NOT NULL AUTO_INCREMENT,
                `fName` VARCHAR(64),
                `lName` VARCHAR(64),
    (...)

This error can be avoided either if we use the following command:

        CREATE TABLE `lead` ( id INTEGER NOT NULL AUTO_INCREMENT, `fName` VARCHAR(64), PRIMARY KEY (id));

So I'm guessing we can either add the " ` " to all table names in CREATE TABLE  and other commands; or warn the user about potentially using a reserved name.

**Comment by miguelgrinberg** [comment]
Flask-Migrate is a simple wrapper for Alembic, which is the database migration engine. If the content of the migration script is incorrect, then you have to discuss this with the Alembic team.
