### ISSUE TITLE
Proper way to update env.py when updating package?

### ISSUE THREAD

**Issue by lleontop** [miguelgrinberg/Flask-Migrate#447]
Hi,

thank you for this amazing package! I was wondering what is the recommended approach to update env.py (and the templates in general) in projects with existing migrations when upgrading the Flask-Migrate package. Since the templates are committed with my migration revisions I can't `db init` it again and get any template upgrades. Is copy/pasting the templates from here to my project the only solution or I am missing something trivial?

Thank you!

**Comment by miguelgrinberg** [comment]
The process that I've used on some projects is as follows:

- Rename your `migrations` folder to `migrations-old` (or something similar)
- Upgrade Flask-Migrate and all of its dependencies to their latest releases
- Create a new migration repository with `flask db init`, or `flask db init --multidb` whichever applies to you.
- Copy all your migrations scripts from `migrations-old/versions` to `migrations/versions`.
- If you've made custom modifications to `env.py` or `alembic.ini`, manually merge those changes into the new versions of these files.
- Create a test database, point your database URL to it, and make sure that the command `flask db upgrade` runs through all your migrations without errors.
- Once you are 100% sure the upgrade went well, you can delete `migrations-old`.

**Comment by lleontop** [comment]
Thank you! I was hoping for a more straightforward way (provided that there aren't any custom modifications in `env.py` or `alembic.ini`) but the proccess you described sounds also good! Thanks again!
