### ISSUE TITLE
Set custom log settings for Alembic

### ISSUE THREAD

**Issue by JVT038** [miguelgrinberg/Flask-Migrate#449]
Hi,
I'm using Flask-migrate through my python app, not through the CLI, and I'd like Alembic to use custom log settings, such as log level on WARN instead of INFO, use my custom log object, and use a custom log format.

I've tried this:
```python
    @migrate.configure
    def configure_alembic(config):
        config.set_section('logger_alembic', 'handlers', logger)
        return config
```
But it gives me this error: `AttributeError: 'Config' object has no attribute 'set_section'`
How can I manually command alembic to use my log object?

**Comment by miguelgrinberg** [comment]
The `Config` object is documented in Alembic's docs: https://alembic.sqlalchemy.org/en/latest/api/config.html.

**Comment by JVT038** [comment]
Thanks for that link.
However, it `set_section_option` doesn't work for me for some reason.
I'm doing this:
```python
    @migrate.configure
    def configure_alembic(config):
        config.set_section_option('logger_alembic', 'level', 'WARN')
        config.set_section_option('logger_flask_migrate', 'level', 'WARN')
        return config
```

**Comment by miguelgrinberg** [comment]
What would be the benefit of doing this instead of editing alembic.ini? When you call `set_config_option` you are just updating the memory representation of the config file. The alembic.ini file is not updated, and if Alembic already loaded the logging configuration then the change isn't going to do anything.

For a global change like yours, editing alembic.ini is the correct solution.

**Comment by JVT038** [comment]
I know, however, I want to make sure that the configuration will automatically be changed when someone sets up this program.

I'm making an app and I'm expecting other people to use it as well. So I want the database to be set up automatically, and I'm using Flask-migrate to automatically create the tables and the database, just so the user doesn't have to do it manually with `flask db init`, `flask db migrate` & `flask db upgrade`. Instead of these 3 commands, the user can just start the python file, and it will happen automatically.
Additionally, I also want to hide the INFO log messages automatically, because I find them annoying.
That's why I'm trying to do this through python, and not by editing the `alembic.ini` file

**Comment by miguelgrinberg** [comment]
@JVT038 this might be a misunderstanding on your part, because you are supposed to set up the migration repository and the migration scripts (ie the `init` and `migrate` commands, along with any customizations to alembic.ini and env.py). Your users are only supposed to run the upgrade command.

If your use case does not agree with this standard usage, then this extension if probably not going to work for you.

**Comment by JVT038** [comment]
I figured it out, through the [file_config](https://alembic.sqlalchemy.org/en/latest/api/config.html#alembic.config.Config.file_config) attribute and the [ConfigParser](https://docs.python.org/3/library/configparser.html) object. 
Basically, I'm manually setting the file, and overwriting the current `alembic.ini` file. 
Like this:
```python
    @migrate.configure
    def configure_alembic(config):
        parser = config.file_config
        try:
            parser["logger_alembic"]["LEVEL"] = 'WARN'
            parser["logger_flask_migrate"]["LEVEL"] = 'WARN'
            parser["formatter_generic"]["format"] = str(logger.handlers[0].formatter._fmt).replace('%', '%%')
            parser["formatter_generic"]["datefmt"] = str(logger.handlers[0].formatter.datefmt).replace('%', '%%')
            with open(config.config_file_name, 'w') as file:
                parser.write(file)
        except Exception as e:
            logger.debug(str(e))
        return config
```
Thanks for the link of the Alembic Config object!

**Comment by miguelgrinberg** [comment]
@JVT038 you are obviously free to do whatever you like, but for future readers, I can really leave this without adding that this is a bad solution that works backwards to what most people will expect.

The normal way this and most other config files are supposed to work is that the software creates an initial version with sane defaults, and the user modifies those defaults to suit their needs.

Your solution rewrites the config file with your software's favorite settings, so you are effectively preventing your users from changing settings themselves. I don't see any situation in which this is a good idea.

You also haven't commented on what I said earlier, which is that the developer is supposed to ship an alembic.init, env.py and migration scripts to their users, so the users should never need to generate these files themselves. The `flask db init` and `flask db migrate` are commands that are only to be used by the developer. The `flask db upgrade` command is for developers and users.
