### ISSUE TITLE
Error: No such template 'custom_template'

### ISSUE THREAD

**Issue by arunpersaud** [miguelgrinberg/Flask-Migrate#451]
Hi

just trying to build the package for openSUSE and I'm getting 

Error: No such template 'custom_template'

when running the tests. The tar-ball seems to have the custom_template directory missing that's in the test directory, is that the issue?

**Comment by miguelgrinberg** [comment]
Including the tests in the Python package is actually a mistake, there is no point in installing tests when users install the package, so I'm going to remove them. If you need to run the tests then get them directly from GitHub.

**Comment by arunpersaud** [comment]
ok. Although many other packages include them in the tar-ball on pypi. This makes it easier for distributions to package, since they like to run the tests ;) Also, if you download the tar-ball from pypi and not the wheel, you might actually want to run the test?

**Comment by miguelgrinberg** [comment]
This is a neverending discussion that I don't think we'll be able to settle here. The fact is that the vast majority of people do not need or care about the tests when they install the package with pip, they just want the install to be as fast as possible. I don't install tests on my packages, this one slipped, it seems this was done many years ago and I didn't realize I was still shipping tests.

**Comment by arunpersaud** [comment]
sounds good. I'll pull in the test from github. Thanks for the fast response
