### ISSUE TITLE
How to Combine with Old Database？

### ISSUE THREAD

**Issue by systemime** [miguelgrinberg/Flask-Migrate#454]
Hello, I have a remote database, and there are some data that cannot be deleted in the database. Now I have a new project of flask. I want to use flask_migrate to manage subsequent database migration. What should I do?

I tried to fake the database migration.
```
❯ flask db init
❯ flask db migrate
❯ flask db stamp head
# Modify database model
❯ flask db migrate
```

In my imagination, the second migrate should only be what I modified for the model, but the generated migration script is almost the same as the first generated migration script.

**Comment by miguelgrinberg** [comment]
See this blog post for instructions: https://blog.miguelgrinberg.com/post/how-to-add-flask-migrate-to-an-existing-project

**Comment by systemime** [comment]
Well, I re-operated according to the blog content, but the problem still exists.

For example：
After I execut' flask db init', I perform the' migrate' and' stamp head' operations, and then add a field to my UserModel，such `user = db.Column(db.String(20))`.
According to the blog, I will perform the' migrate' operation at this time. the migration file should only is' op.add_column('api_user',sa. column('user',sa. string (length = 20),nullable = true))'. in fact, the migration file generated in the second time almost copies the contents of the migration file generated in the first 'migration'

**Comment by miguelgrinberg** [comment]
Go back to the article and reread the part about using an empty database to generate the initial migration.

**Comment by systemime** [comment]
I found some other problems in the database that affected the migration. Thank you for your correction.
