### ISSUE TITLE
Add timezone support

### ISSUE THREAD

**Issue by atugushev** [miguelgrinberg/Flask-Migrate#456]
#### What's the problem this feature will solve?

If you try to generate a migration that requires a DateTime with timezone support you'll get the following error:

```
ERROR: MainProcess<flask_migrate> Error: The library 'python-dateutil' is required for timezone support
```

It seems `python-dateutil` is optional dependency since [alembic==1.7.0](https://alembic.sqlalchemy.org/en/latest/changelog.html#change-c01e812b3ac23a262b2c9c343f009aad) and can be installed via extras:`pip install alembic[tz]`. 

#### Describe the solution you'd like

Would it make sense to reflect this change to `flask-migrate` by adding `flask-migrate[tz]` extras which would require `alembic[tz]`?

#### Alternative Solutions

Add manually `alembic[tz]` or even `python-dateutil` to pip-tools/poetry/pipenv/reqirements.txt requirement flies.

#### Additional context

- https://github.com/sqlalchemy/alembic/issues/674#issuecomment-604585944
- https://github.com/sqlalchemy/alembic/blob/a9e6f9079a7d0157a842b3786ebd4f7031b08912/setup.cfg#L53-L55

P.S. I'd like to shoot a PR if the maintainer is on board.

**Comment by miguelgrinberg** [comment]
Given that the error provides useful instructions to address the problem I don't think it is necessary to complicate things with an extra that not even the error message suggest you should use.

**Comment by atugushev** [comment]
> an extra that not even the error message suggest you should use.

That sounds right. Thanks for the prompt response 🙏🏻
