### ISSUE TITLE
❓ Directory Structure For Large Apps

### ISSUE THREAD

**Issue by diloreto** [miguelgrinberg/Flask-Migrate#457]
I'm creating an app that is becoming quite large, requiring multiple directories to organize all the models, [schemas](https://flask-marshmallow.readthedocs.io/en/latest/), routes, functions, etc. What is the recommended approach for splitting / organizing the application for ease of understanding and still functional to migrate? Could I do something like this:

```
src/
    app.py
    models/
        entity1.py
        entity2.py
        entity3.py
    schemas/
        entity1.py
        entity2.py
        entity3.py
    functions/
        entity1.py
        entity2.py
        entity3.py
```

Would flask-db migrate still function if all the data models were split? How do you recommend structuring the application?

Thanks!

**Comment by miguelgrinberg** [comment]
The only thing that Flask-Migrate needs is that the models are imported. How do you structure them is really up to you, there are no requirements.

**Comment by a0s** [comment]
In what way we could automate importing every models? Do you have any valuable example?

**Comment by miguelgrinberg** [comment]
@a0s What is the problem with using rails or django then? If you like an all-in-one experience those frameworks are more appropriate. Flask has a difference philosophy. To import your models, you just import your models. The fact that your application is large does not change this.

**Comment by a0s** [comment]
> To import your models, you just import your models.

Its true until you start using Flask-Migrate. Now you need *all* you models in local space in before Migrate() initialization.

In the end, I unraveled this tangle. I built [simple template app](https://github.com/a0s/flask-app-template) which makes autoloading. Steep learning curve.
