### ISSUE TITLE
Specify different username:password for Alembic than for SQLAlchemy

### ISSUE THREAD

**Issue by L0uisc** [miguelgrinberg/Flask-Migrate#460]
I want to be able to specify a username:password to Flask-Migrate with permissions to alter tables and drop and create tables, but I don't want my SQLAlchemy user to have those permissions. SQLAlchemy should only be able to insert, update, select and join. Is this possible at the moment? If so, how would I do that?

**Comment by miguelgrinberg** [comment]
This is unrelated to this package, and directly influenced by how you control your Flask configuration, from which the database URL is extracted. For example, if you set your database URL from an environment variable, then you can change the variable before you run a `flask db` command.
