### ISSUE TITLE
Recovering from hung migration due to MYSQL Lock

### ISSUE THREAD

**Issue by scath999** [miguelgrinberg/Flask-Migrate#461]
Hi Miguel,

Thanks for building this project out, and for posting so much great help online - much appreciated.

That said, I'm having trouble recovering from a migration that got hung during execution because alembic couldn't obtain a lock from MySQL.

I use MySQL Workbench to quickly scan tables and data as I develop. However, if I leave that tool open during migrations (by mistake), alembic isn't able to obtain a lock from mysql and hangs.

This hung execution is not recoverable: I cannot stop migration script execution, and it will hang seemingly indefinitely (I've left the terminal open for hours with no progress).

My only recourse is to close the terminal, which (as you might imagine) has some pretty gross repercussions that are proving difficult to recover from.

My questions are these:

1) How can I recover? I'm fine with removing flask_migration, manually rolling back the db, and starting again but I wonder if there's a better way?

2) How can I avoid this in future? I'm human like everyone else, and I'm going to make mistakes going forward, but is there some step  or feature I'm missing that can help me avoid this situation? I admit I'm not a mysql expert - far from it - and welcome advice or help, or even a point in the direction of that help.

3) Does flask-migrate have a process for detecting these kinds of issues (perhaps a time-out to other solution) and failing safely? 

4) If not, can this be built out? I'm sorry to ask, and normally I'd just offer to do it myself, but I'm committed to getting my project off the ground and can't divert time away. If the answer is "no", I'll certainly accept it, respectfully.

Kindest wishes and thanks again - you're a fabulous creator :)

**Comment by miguelgrinberg** [comment]
This is really not the appropriate project for this question. Flask-Migrate is just a wrapper that integrates Alembic and Flask. There is no code in this project that works with databases directly, all work is done through Alembic, SQLAlchemy and Flask. This is either an Alembic or SQLAlchemy issue, so I suggest you search on user community forums for those projects.

**Comment by scath999** [comment]
Thanks for the point in the right direction - I'll head over there.

Cheers!
