### ISSUE TITLE
Working with multiple bases

### ISSUE THREAD

**Issue by lougeo** [miguelgrinberg/Flask-Migrate#469]
working with multiple BASES (not databases), as described in the Alembic documentation here does not work:
[https://alembic.sqlalchemy.org/en/latest/branches.html#working-with-multiple-bases](https://alembic.sqlalchemy.org/en/latest/branches.html#working-with-multiple-bases)

When attempting to run the initial revision command (with the --version-path flag set) to create a labeled base revision, I cannot find a way to properly specify the version path, and am presented with the following error:
`Error: Path users/migrations/versions is not represented in current version locations`

To reproduce, start a project, run the init command, and then try to run a revision command with the appropriate flags set, for example:
`flask db revision -m "create new base" --head=base --branch-label=users --version-path=users/migrations/versions`

As far as I can tell the only additions to the alembic.ini file which are necessary are:
```
version_path_separator = os
version_locations = %(here)s/users/migrations:%(here)s/versions
```

Ideally the file structure would look something like:
```
.
└── main_project/
    ├── migrations/
    │   ├── versions/
    │   │   └── ...
    │   ├── alembic.ini
    │   ├── env.py
    │   └── script.py.mako
    ├── users/
    │   ├── migrations/
    │   │   ├── versions/
    │   │   │   └── ...
    │   │   └── ...
    │   └── models.py
    └── ...
```

If I'm doing something wrong please let me know, I've been going a bit crazy trying to figure out what's happening

**Comment by miguelgrinberg** [comment]
I don't understand what's broken. You followed the instructions in the alembic docs and you got it working right?

Alembic does not include these options by default so why should this extension?

**Comment by lougeo** [comment]
Alembic does offer the ability to work with multiple heads, as described in the link I shared. 

I'm having a hard time determining what is preventing flask-migrate from operating in the same way as Alembic.

The flask-migrate docs include the --version-path flag, and there is no error calling it, it just doesn't seem possible to use - that is unless I'm completely missing some configuration detail.

**Comment by miguelgrinberg** [comment]
Do you have a working alembic project that I can use to debug this?

**Comment by miguelgrinberg** [comment]
Here's an idea. The alembic.ini file is inside the `migrations` directory, and you are using `%(here)s` in this file, but you are assuming that maps to the current directory, the parent of `migrations`. You may need to add a `..` to navigate one parent up.

**Comment by lougeo** [comment]
Sincere apologies, honestly not sure what I changed that allowed it to start working but it did. Been banging my head against the keyboard all day. The related bits in the alembic file that are currently set and working are:
```
[alembic]
script_location = %(here)s/

version_path_separator = os
version_locations = ./user/migrations/versions:%(here)s/versions
```
