### ISSUE TITLE
Migrations dir default may be outside of the package

### ISSUE THREAD

**Issue by OJFord** [miguelgrinberg/Flask-Migrate#471]
If you have a `FLASK_APP` such as `=myapp.app`, the default value of `Migrate`'s `directory` kwarg puts `migrations` in the cwd, a sibling to the `myapp` package.

I think a better default would be to ensure it's sibling to the module containing the app instance/factory.

I don't know though if Flask offers a convenient way of finding this location without duplicating its `FLASK_APP` parsing logic and defaults.

**Comment by miguelgrinberg** [comment]
I'm  not open to changing the default directory, as that is going to break lots of current installs. But the directory is easy to change. Here is an except from the docs that shows you how:

- All commands also take a `--directory DIRECTORY` option that points to the directory containing the migration scripts. If this argument is omitted the directory used is migrations.
- The default directory can also be specified as a `directory` argument to the `Migrate` constructor.

Hope this helps.

**Comment by OJFord** [comment]
Fine, just a suggestion (not a question..), up to you of course.

>  that is going to break lots of current installs

Would it? My suggestion would only break layouts like:

```
.
├── mypackage
│   ├── __init__.py
...
│   └── app.py
...
└── migrations
```

which seems unusual and undesirable. If it was desired, the fix would be a simple excerpt from the docs, as you say.

I did mention the `directory` argument in my very first sentence, I already fixed it for myself and moved on, this was not a support request or question. Simply a suggestion to make the default behaviour more intuitive and robust - as it is, a user changing how their own package is installed (anything that requires the first part of `FLASK_APP`, the path to the module, to change) can break it, if they're relying on the default.

**Comment by miguelgrinberg** [comment]
> which seems unusual and undesirable

I run all my products like this. My tutorials are also organized in this form. Not sure why you think this is undesirable or unusual. Migration scripts are not application code, they do not belong in the application package.
