### ISSUE TITLE
Generate sql from specific migration file

### ISSUE THREAD

**Issue by d9k** [miguelgrinberg/Flask-Migrate#472]
I want to generate upgrade sql code for specific migration files (for example `1d9e835a84f9_.py`) to manually fix database after switching code branch.
How can I achieve that?

**Comment by d9k** [comment]
I think it can be achieved with pure alembic by command

```
alembic upgrade <rev1>:<rev2> --sql
```

https://stackoverflow.com/a/37683059/1760643

How to achieve it with flask-migrate?

**Comment by d9k** [comment]
Ok, found I can do `DELETE FROM alembic_version;` and generate sql for all migrations at once with `db upgrade --sql`

**Comment by d9k** [comment]
Also I would really like to know how to ignore errors during generation.

**Comment by miguelgrinberg** [comment]
I'm sorry, but I don't understand what you are asking. Why would you ignore errors? The solution is to fix your data inconsistencies problems, wouldn't you think? Ignoring errors is almost never a good idea. In any case, I wouldn't know what to respond to this, you would need to look at the stack trace and find the correct place to modify Flask-Migrate or more likely Alembic or SQLAlchemy code to prevent the error from stopping. Not what I would recommend, anyway.

**Comment by miguelgrinberg** [comment]
@d9k Did you try `flask db upgrade --sql`? All the Alembic commands are available through `flask db`.

**Comment by d9k** [comment]
@miguelgrinberg, thanks it works

```
superset db upgrade 3dda56f1c4c6:1d9e835a84f9 --sq

**Comment by d9k** [comment]
Made simple script for getting sql code of migration for Superset which uses flask-migrate:

```
#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function echoerr {
  printf "%s\n" "$*" >&2;
}

function echo_help {
  echoerr "Utility to get resulting sql code from migration"
  echoerr
  echoerr "Usage:"
  echoerr "    running-superset-app-migration-get-sql MIGRATION_ID"
}

if [ "$#" -lt 1 ]; then
  echo_help
  exit
fi

MIGRATION_ID="$1"

DOCKER_MIGRATIONS_DIR="/app/superset/migrations/versions"

# fail on error
set -e

# fail on variable abscense
set -u

function require_variable { VAR_NAME="$1"
  VAL="${!VAR_NAME}"

  if [[ -z "$VAL" ]]; then
    echoerr "Error: variable \"$VAR_NAME\" is required but not set:"
    exit 1
  fi
}

MIGRATION_FILE=$(docker exec superset_app ls "$DOCKER_MIGRATIONS_DIR/" | grep "${MIGRATION_ID}" | head -n 1)

if [[ -z "$MIGRATION_FILE" ]]; then
  echo "Migration not found"
  exit
fi

echo "Migration file:"
echo "  $MIGRATION_FILE"

MIGRATION_CONTENT=$(docker exec superset_app cat "$DOCKER_MIGRATIONS_DIR/$MIGRATION_FILE")

REVISION=$(echo "$MIGRATION_CONTENT" |  grep "^revision = " | cut -d '"' -f2)
DOWN_REVISION=$(echo "$MIGRATION_CONTENT" |  grep "^down_revision = " | cut -d '"' -f2)

require_variable "REVISION"
require_variable "DOWN_REVISION"

# no fail on error
set +e

( set -x; docker exec superset_app superset db upgrade "$DOWN_REVISION":"$REVISION" --sql )

echo "=== Entering superset PostgreSQL REPL ==="
bash "$SCRIPT_DIR/running-db-connect.sh"
```
