### ISSUE TITLE
Integrate updates into app

### ISSUE THREAD

**Issue by eljeffeg** [miguelgrinberg/Flask-Migrate#474]
I sort of expected `migrate.init_app(app, db)` (or some additional command) would include database creation (if not existing) and automatic upgrade if available.  I use to do this in Alembic, what is the best way to do it with flask migrate?

I just want the user to be able to do a `git pull` and restart.  They shouldn't need to know that a `flask db upgrade` is required in any update.  It should just happen auto-magicly.

```py
from alembic.config import Config, command

def update_db(update=True):
    logging.info("Checking for Database Updates...")
    db_connection = DatabaseConnection(
        database=options.sql_database,
        hostname=options.sql_host,
        port=options.sql_port,
        username=options.sql_user,
        password=options.sql_password,
        dialect=options.sql_dialect,
        ssl_ca=options.sql_sslca,
    )
    alembic_cfg = Config("alembic/alembic.ini")
    alembic_cfg.attributes["configure_logger"] = False
    alembic_cfg.set_main_option("sqlalchemy.url", unquote(str(db_connection)))
    if update:
        command.upgrade(alembic_cfg, "head")
    else:
        command.stamp(alembic_cfg, "head")
```

**Comment by eljeffeg** [comment]
So it is pretty easy and this should be in the setup documentation, but here is what I did.

```
from flask_migrate import upgrade

db.create_all()
try:
    upgrade()
except Exception as e:
    print(e)
```

**Comment by miguelgrinberg** [comment]
Keep in mind that this way of doing upgrades will not work well if you have multiple server workers, as each worker will try to run the upgrade at the same time.

**Comment by eljeffeg** [comment]
I've learned to put `if exists` checks in my scripts. lol
