### ISSUE TITLE
Flask Migrate not compatible with Flask 2.2.0

### ISSUE THREAD

**Issue by johaven** [miguelgrinberg/Flask-Migrate#476]
The application context is no longer stored in Werkzeug's LocalStack :)

https://github.com/pallets/flask/pull/4682

**Comment by miguelgrinberg** [comment]
What is specifically that you found to be incompatible? I can run all the tests under 2.2.0 and everything seems to work.

**Comment by johaven** [comment]
Ah?! I got this error when i upgrade to Flask 2.2.0 (Werkzeug 2.2.1 / Flask-Migrate 3.1.0)
```sh
Usage: db migrate [OPTIONS]
Try 'db migrate --help' for help.

Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.
```
I use a CLI based on click that import the your, like this:
```python
from click.testing import CliRunner
from flask_migrate import Migrate
from flask_migrate.cli import click
from flask_migrate.cli import db as db_cmd
from webapp import app, db

def custom_migrate():
    ...
    Migrate(app, db, compare_type=True)
    runner = CliRunner()
    r = runner.invoke(db_cmd, ['migrate'], catch_exceptions=False)
    ...
```
After digging `current_app` seems to be not found but it's working with the previous version of Flask.
That's why I thought the problem was with your plugin :(

**Comment by miguelgrinberg** [comment]
Impossible for me to tell from the partial code you shared, but maybe you should set your app context before calling Flask-Migrate?

**Comment by johaven** [comment]
You put me on the right track, indeed this way it works perfectly.

```python
def custom_migrate():
    ...
    Migrate(app, db, compare_type=True)
    with app.app_context():
        runner = CliRunner()
        r = runner.invoke(db_cmd, ['migrate'], catch_exceptions=False)
    ...
```
I don't know why the context is well found on all previous versions of Flask and not on this new release :S
Thank you for your time anyway, you do a great job with the plugins you offer to the community.
