### ISSUE TITLE
Peewee support

### ISSUE THREAD

**Issue by Kenuat** [miguelgrinberg/Flask-Migrate#49]
Hi, I'm using peewee ORM for my Flask application, are there any plans to support this excelent module in Flask-Migrate? Peewee already have some helper functions which should greatly simplify its integration:
http://peewee.readthedocs.org/en/latest/peewee/playhouse.html#migrate
Thanks

**Comment by miguelgrinberg** [comment]
Flask-Migrate relies heavily on Alembic, all this extension does is make Alembic better integrated with Flask. So really supporting a different ORM will require a major rewrite.

**Comment by Kenuat** [comment]
Thank you for the explanation Miguel, well, maybe it's a good idea to rename the extension to something less confusing? Like Flask-SQLAlchemy-Migrate? So people like me won't ask the same question.

**Comment by miguelgrinberg** [comment]
Back when I started this project I wanted to call it Flask-Alembic, but the name was taken.

**Comment by gerosalesc** [comment]
:(
