### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by kasium** [miguelgrinberg/Flask-Migrate#492]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Type hints are added to the project since both flask and alembic have them.

**Describe alternatives you've considered**
Added them to typeshed but I first want to check if they could be added as inline types.

**Logs**
n/a

**Additional context**
n/a

**Comment by miguelgrinberg** [comment]
I'm not currently planning to add inline type hints. Typeshed sounds like a great option.

**Comment by kasium** [comment]
Thanks for the info. Let me add it there then
