### ISSUE TITLE
flask db migrate taking ~30min to autogenerate and throwing unrelated warnings

### ISSUE THREAD

**Issue by mnemyx** [miguelgrinberg/Flask-Migrate#497]
**IMPORTANT**: If you have a question, or if you are not sure if you have found a bug in this package or in your own code, then you are in the wrong place. Hit back in your web browser, and then open a GitHub Discussion instead. Likewise, if you are unable to provide the information requested below, open a Discussion to troubleshoot your issue.

**Describe the bug**
Whenever I run `flask db migrate`, the process takes an incredibly long time (almost 30min) and prints out unrelated warnings before succeeding and autogenerating the migration script.

![image](https://user-images.githubusercontent.com/770706/203180362-7943f29c-36f4-482b-a83d-086e45801462.png)

As far as I know: 
- We aren't using a geometry/geography enabled database
- All the types defined in the Python models are simple types: boolean, biginteger, integer, string, unicode
- We only have 12 tables
- This may be an alembic issue but I'm not sure where to start in reporting this with them

It seems to notice new/removed table changes quickly, then hangs, then it'll notice the rest of the changes to the models fairly quickly.

**To Reproduce**
1. `flask db migrate`
2. Wait ~30min and see warnings
3. Eventually see all the detected changes and get an autogenerated migration script

**Expected behavior**
Generating a migration script for 12 tables shouldn't take 30 minutes.

**Logs**
![image](https://user-images.githubusercontent.com/770706/203180362-7943f29c-36f4-482b-a83d-086e45801462.png)

**Additional context**
requirements.txt:
```
alembic==1.7.7
blinker==1.5
click==8.0.4
colorama==0.4.5
config==0.5.1
dataclasses==0.8
Flask==2.0.3
Flask-HTTPAuth==4.5.0
Flask-JWT-Extended==4.3.1
Flask-Login==0.5.0
Flask-LoginManager==1.1.6
Flask-Mail==0.9.1
flask-marshmallow==0.14.0
Flask-Migrate==3.1.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.1
greenlet==1.1.3.post0
importlib-metadata==4.8.3
importlib-resources==5.4.0
itsdangerous==2.0.1
Jinja2==3.0.3
langcodes==3.3.0
language-data==1.1
Mako==1.1.6
marisa-trie==0.7.8
MarkupSafe==2.0.1
marshmallow==3.14.1
marshmallow-sqlalchemy==0.27.0
numpy==1.19.5
pandas==1.1.5
PyJWT==2.3.0
pyodbc==4.0.34
python-dateutil==2.8.2
python-dotenv==0.20.0
pytz==2022.4
six==1.16.0
SQLAlchemy==1.4.41
typing-extensions==4.1.1
Werkzeug==2.0.3
WTForms==3.0.0
zipp==3.6.0
```

**Comment by miguelgrinberg** [comment]
Flask-Migrate does not have any database migration logic, this is all done by Alembic, so I suggest you ask in the [Alembic discussions board](https://github.com/sqlalchemy/alembic/discussions). Note that the `flask db migrate` command is equivalent to `alembic revision --autogenerate` when using Alembic without Flask-Migrate, which should help them know exactly what you are doing.

**Comment by mnemyx** [comment]
Thank you, I'll go do that!
