### ISSUE TITLE
Enum Field changes, but no changes in schema detected when run "flask db migrate"

### ISSUE THREAD

**Issue by hifiveszu** [miguelgrinberg/Flask-Migrate#513]
**Describe the bug**
Enum Field changes, but no changes in schema detected when run "flask db migrate"

```code
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.
```

before:

```code
class DocumentSourceType(Enum):
    FILE = "File"
    URL = "Url"
```

after:

```
class DocumentSourceType(Enum):
    FILE = "File"
    URL = "Url"
    WEBSITE = "Website"
    SITEMAP = "Sitemap"
```

This is really sucks!

**Comment by miguelgrinberg** [comment]
Flask-Migrate is the Flask integration for the Alembic database migration engine. Migrations are handled by Alembic. Detecting changes to enums automatically has not been implemented, see https://github.com/sqlalchemy/alembic/issues/363.
