### ISSUE TITLE
Do not automatically import of  sqlalchemy_utils 

### ISSUE THREAD

**Issue by zanghuahua** [miguelgrinberg/Flask-Migrate#515]
![image](https://github.com/miguelgrinberg/Flask-Migrate/assets/131878053/3faf83cd-f981-4b7b-a289-8a41439a3944)

**Comment by miguelgrinberg** [comment]
Flask-Migrate is a Flask extension that wraps Alembic. If you have problems with the migration generation, then you need to talk to the Alembic project.
