### ISSUE TITLE
The pgvector vector field cannot generate a normal migration script

### ISSUE THREAD

**Issue by glacierck** [miguelgrinberg/Flask-Migrate#518]
Pgvector is a vector extension plugin for PostgreSQL databases。

This is my code.
![image](https://github.com/miguelgrinberg/Flask-Migrate/assets/21599896/b27db33e-e7e1-4547-9e8d-29e9d2703e42)

Run `flask db migrate`, generated an error migration script with missing pgvector.
![image](https://github.com/miguelgrinberg/Flask-Migrate/assets/21599896/6b74d155-2421-40e8-a6a9-22b1cffc3ab1)

**Comment by miguelgrinberg** [comment]
Flask-Migrate does not generate migrations, it just integrates Alembic with Flask. If you have issues with generated migrations, you need to discuss with the Alembic project.

That said, looks like your issue would be easily solved if you add the missing import, right?
