### ISSUE TITLE
Latest version of Alembic breaks flask-migrate

### ISSUE THREAD

**Issue by kevgliss** [miguelgrinberg/Flask-Migrate#52]
The latest version of alembic (alembic 0.7.5.post1) breaks some assumptions in flask migrate.

      File "/apps/python/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 9, in <module>
          alembic_version = tuple([int(v) for v in __alembic_version__.split('.')])

Filed issue with alembic but it seems this is a valid pypi package version.
https://bitbucket.org/zzzeek/alembic/issue/286/version-075post1-breaks-some-downstream

**Comment by miguelgrinberg** [comment]
Just pushed version 1.3.1 with a fix.
