### ISSUE TITLE
Problems connecting to Postsgress Because of no encryption

### ISSUE THREAD

**Issue by Bozabit** [miguelgrinberg/Flask-Migrate#524]
While deploying my appplication I was getting an error connecting to my db. I worked the bug until I realized that the problem came from the flask db upgrade command that is part of my deploy pipeline. 

Running flask db migrate in my local dev I could replicate the error. here is the las bit of it 

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "xxxx" (xx.xx.xx.xx), port 5432 failed: FATAL:  password authentication failed for user "xxxxxxxxx"
connection to server at "xxxxxxxxxxxxxxx" (xx.xx.xx.xx), port 5432 failed: FATAL:  no pg_hba.conf entry for host "xx.xx.xx.xx", user "xxxxxxxx", database "xxxxxxxxx", no encryption

This are my requirements as of now. Which I updated cause it seemed that everything worked fine until this 

alembic==1.11.2
bcrypt==4.0.1
bidict==0.22.1
blinker==1.6.2
boto3==1.28.24
botocore==1.31.24
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
dnspython==1.16.0
ecdsa==0.18.0
email-validator==1.3.1
eventlet==0.30.2
Flask==2.3.2
Flask-AWSCognito==1.3
Flask-Bcrypt==1.0.1
Flask-Cors==4.0.0
Flask-JWT-Extended==4.5.2
Flask-Login==0.6.2
Flask-Mail==0.9.1
flask-marshmallow==0.15.0
Flask-Migrate==4.0.4
Flask-SocketIO==5.3.5
Flask-SQLAlchemy==3.0.5
Flask-WTF==1.1.1
greenlet==2.0.2
gunicorn==21.2.0
idna==3.4
importlib-metadata==6.8.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
Mako==1.2.4
MarkupSafe==2.1.3
marshmallow==3.20.1
marshmallow-sqlalchemy==0.29.0
numpy==1.25.2
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
psycopg2-binary==2.9.7
pyasn1==0.5.0
PyJWT==2.8.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-engineio==4.5.1
python-jose==3.3.0
python-socketio==5.8.0
pytz==2023.3
requests==2.31.0
rsa==4.9
s3transfer==0.6.1
six==1.16.0
SQLAlchemy==2.0.19
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
Werkzeug==2.3.6
WTForms==3.0.1
zipp==3.16.2

Please let me know if in fact is a migrate problem or am I missing something?... Tried to find some config on the documentation but could not know whic one would help me

thanks

**Comment by miguelgrinberg** [comment]
This is a postgres configuration issue, not related to Flask-Migrate or SQLAlchemy. See https://dba.stackexchange.com/questions/320468/postgresql-fatal-no-pg-hba-conf-entry-for-host-ipv6-user-user-databas

**Comment by Bozabit** [comment]
I see... I will look into it... But why when I go back to this package versions... everything works?

alembic==1.4.3
astroid==2.4.2
autopep8==1.5.4
bcrypt==3.2.0
blinker==1.4
boto3==1.15.3
botocore==1.18.3
cffi==1.14.3
click==7.1.2
dnspython==2.0.0
email-validator==1.1.1
Flask==1.1.2
Flask-Bcrypt==0.7.1
Flask-Login==0.5.0
Flask-Mail==0.9.1
flask-marshmallow==0.13.0
Flask-Migrate==2.5.3
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
idna==2.10
isort==5.5.2
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
lazy-object-proxy==1.4.3
Mako==1.1.3
MarkupSafe==1.1.1
marshmallow==3.8.0
marshmallow-sqlalchemy==0.23.1
mccabe==0.6.1
Pillow==7.2.0
psycopg2==2.8.6
pycodestyle==2.6.0
pycparser==2.20
pylint==2.6.0
pylint-flask==0.6
pylint-plugin-utils==0.6
PyMySQL==0.10.1
python-dateutil==2.8.1
python-dotenv==0.14.0
python-editor==1.0.4
s3transfer==0.3.3
six==1.15.0
SQLAlchemy==1.3.19
toml==0.10.1
urllib3==1.25.10
Werkzeug==1.0.1
wrapt==1.12.1
WTForms==2.3.3

I mean, between those two requirements files, the Postgres Server it's the same, with the same configuration. Should not that fail on every case?...

**Comment by Bozabit** [comment]
And I can connect through SQLAlchemy just fine...

**Comment by miguelgrinberg** [comment]
You are jumping from SQLAlchemy 1.3 to 2.0. That is a huge difference as many changes went into versions 1.4.x and 2.0.x, and Flask-Migrate needed to make some big changes as a result of that.

What I suggest is that you try upgrading the env.py in your `migrations` directory, which was likely generated for the 1.3 release of SQLAlchemy. If you haven't made any custom changes to this file, you can grab an updated copy from [here](https://github.com/miguelgrinberg/Flask-Migrate/blob/main/src/flask_migrate/templates/flask/env.py) and replace it in your `migrations` directory.

**Comment by Bozabit** [comment]
It worked perfectly... Thanks for your help and the information, the project and everything you've published... I've been a fan for many years now.
