### ISSUE TITLE
Support for Alembic branches

### ISSUE THREAD

**Issue by yoanisgil** [miguelgrinberg/Flask-Migrate#56]
Hi,

I was just wondering if Flask-Migrate supports alembic branches : http://alembic.readthedocs.org/en/latest/branches.html 

Thanks,

Yoanis.

**Comment by miguelgrinberg** [comment]
They should, this extension is just a thin wrapper around Alembic, all the options from Alembic are accessible.

**Comment by yoanisgil** [comment]
@miguelgrinberg Thanks. I will take a look and let you know how that goes.
