### ISSUE TITLE
Do something after executing a command such as `revision`

### ISSUE THREAD

**Issue by chavz** [miguelgrinberg/Flask-Migrate#60]
I would like to know if there is a way for me listen/tap into revision command in such a way that i could extend it to do something more.

My end game here is, I would like for `revision` to, after doing its thing =), create a new folder  inside my application with the new revision number as its folder name. This new folder is where i am planning to place my seed data in the form of csv files (one for each table), and then I will create a new command `seed()` which will in turn read these csv files depending on the current alembic version.

**Comment by miguelgrinberg** [comment]
Take a look at this example:

https://github.com/miguelgrinberg/flasky/blob/master/manage.py#L65

Here I run an upgrade, then do some more stuff, and the whole thing is wrapped as a Flask-Script command.

**Comment by chavz** [comment]
I see, just as I thought i will have wrap it under a different command, I was hoping for more a pub/sub kind of way (coming from javascript background =D ) but this will do. Thanks!

Although I'll probably go with a alembic's `-x` option to achieve my end game here as its more fitted for the job.
