### ISSUE TITLE
The multidb is not putting changes in the correct database.

### ISSUE THREAD

**Issue by jontayesp** [miguelgrinberg/Flask-Migrate#73]
I am having an issue where my schema changes are not showing up in the correct database. Furthermore, the test_multidb_migrate_upgrade fails when running "python setup.py test".

When I run these commands:

```sh
cd tests
rm *.db && rm -rf migrations # cleanup
python app_multidb.py db init --multidb
python app_multidb.py db migrate
python app_multidb.py db upgrade
```

I get this version. Which is wrong, because User should be in upgrade_, not upgrade_db1.

```python
"""empty message

Revision ID: af440038899
Revises: 
Create Date: 2015-08-17 14:24:58.842302

"""

# revision identifiers, used by Alembic.
revision = 'af440038899'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_db1():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_db1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    op.drop_table('user')
    ### end Alembic commands ###
```

Using the latest libraries, not sure if a recent upgrade broke it:

```
$ pip freeze
Flask==0.10.1
Flask-Migrate==1.5.0
Flask-SQLAlchemy==2.0
Flask-Script==2.0.5
Jinja2==2.8
Mako==1.0.1
MarkupSafe==0.23
SQLAlchemy==1.0.8
Werkzeug==0.10.4
alembic==0.8.0
itsdangerous==0.24
python-editor==0.3
wsgiref==0.1.2
```

For sanity, can you confirm unit tests still pass with alembic 0.8, which I believe was released a few days ago? Thanks!

**Comment by jontayesp** [comment]
Confirmed that test_multidb_migrate_upgrade passes when downgrading to alembic 0.7.7, so something new in alembic 0.8 breaks it.

**Comment by miguelgrinberg** [comment]
@jontayesp Okay, thanks for your detailed investigation. I'll figure out what changed in 0.8 that breaks.

**Comment by jontayesp** [comment]
All tests now pass with alembic>=0.8.1. (test_multidb_migrate_upgrade only fails with alembic==0.8.0.) I assume they fixed an issue and not relevant to Flask-Migrate.

This may have been the fix: https://bitbucket.org/zzzeek/alembic/commits/e05f0c370dd93a2295e3ebfdffba9d37bd732b48
