### ISSUE TITLE
Flask-Migrate not creating tables

### ISSUE THREAD

**Issue by mateen-dar** [miguelgrinberg/Flask-Migrate#8]
Hi,

The following is my app_db.py file at the root of my project. 

import os 
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.script import Manager
from flask.ext.migrate import Migrate, MigrateCommand

if os.environ.get('DATABASE_URL') is None:
    SQLALCHEMY_DATABASE_URI = 'postgresql://mramgokrujqfer:tIkrP25gX9XQBpZsl7W3MQtrw0@ec2-184-73-175-240.compute-1.amazonaws.com:5432/dev03fouea9lm'
else:
    SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']

app = Flask(**name**)
app.config['SQLALCHEMY_DATABASE_URI'] = SQLALCHEMY_DATABASE_URI
db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

def load_models():
    from app.models.models import User,Address,NewTable,NewTable23,NewTable45
    print 'loaded'

if **name** == '**main**':
    load_models()
    manager.run()

I then have a apps/models/models.py file that contains the following models

import os
from app_db import db
from flask.ext.sqlalchemy import SQLAlchemy

class JSONSERIALIZER(object):
    def to_dict(self):
        return {c.name: getattr(self, c.name) for c in self.**table**.columns}

class User(db.Model,JSONSERIALIZER):
    **tablename** = 'users'
    **public** = ('my_id', 'name')
    my_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    addresses = db.relationship("Address",  backref=db.backref("user"))
    def **init**(self, id, name):
        self.my_id = id
        self.name = name
    def **repr**(self):
        return "<User('%d','%s')>" % (self.my_id, self.name)

class Address(db.Model,JSONSERIALIZER):
    **tablename**='addresses'
    id = db.Column(db.Integer, primary_key=True)
    email_address = db.Column(db.String, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.my_id'))

```
def __init__(self, email_address):
    self.email_address = email_address

def __repr__(self):
    return "<Address('%s')>" % self.email_address
```

class NewTable(db.Model):
    **tablename**='newtable'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(128))

class NewTable23(db.Model):
    **tablename**='newtable23'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(128))

class NewTable45(db.Model):
    **tablename**='newtable45'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(128))

db.create_all()

Now using python app_db db migrate and then python app_db db update no tables are created. If i create the tables my self, the update command removes them ? What am i doing wrong  ?

**Comment by danidee10** [comment]
@miguelgrinberg i don't think it's necessary to drop all the db tables (especially when you have important information in them)....in my case i simply commented out `db.create_all()` deleted the new table that was created....after that alembic detected the new table and the migration worked without any problem

**Comment by miguelgrinberg** [comment]
@danidee10 you need to delete only the tables that you want the migration to pick up. In the case of this issue, the OP needed all the tables added to the migration, that is why I recommended all of them to be dropped.
