### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL 

### ISSUE THREAD

**Issue by scheung38** [miguelgrinberg/Flask-Migrate#81]
After successful 
$python application.py db init
$python application.py db migrate

But upon
$python application.py db upgrade

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL [SQL: u'ALTER TABLE user ADD COLUMN title VARCHAR(10) NOT NULL']

In my database the new column is defined a 'title' as in:

```
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(10), unique=False, nullable=False, info={'validators': InputRequired()})
    firstname = db.Column(db.String(30), unique=False, nullable=False, info={'validators': InputRequired()})
    middlename = db.Column(db.String(30), unique=False, nullable=True, info={'validators': Optional()})
    lastname = db.Column(db.String(30), unique=False, nullable=False, info={'validators': InputRequired()})
    email = db.Column(db.String(120), unique=True, nullable=False, info={'validators': Email()})
    password = db.Column(db.String(80), nullable=False)
    posts = db.relationship('Post', backref='user', lazy='dynamic')

    def __init__(self, title, firstname, middlename, lastname, email, password):
        self.title = title
        self.firstname = firstname
        self.middlename = middlename
        self.lastname = lastname
        self.email = email
        self.password = flask_bcrypt.generate_password_hash(password)

```

Or do I need to add attribute server_default or default to 'title' attribute? as previously defined data didn't have it

I do see some solutions but these are all in SQL syntax, staying within Python-Migrate constraint would be preferable.

**Comment by miguelgrinberg** [comment]
Right, the problem is that when you add a column that is not nullable the db does not know what to put as value for all the existing rows, you have to pass a default.

**Comment by scheung38** [comment]
Thanks Miguel could you let us know what a default value would be? Default for the existing Column or new attribute?

**Comment by miguelgrinberg** [comment]
If you set nullable=True then things should work, your existing rows will have NULL as value for the new column.

Alternatively, you can set a default to an empty string, that should work too.

**Comment by scheung38** [comment]
I did and it is still returning the same

**Comment by miguelgrinberg** [comment]
Did you check the migration code to see if it was updated to nullable=True?

**Comment by smalekzadeh** [comment]
I have the same problem. Did you find a solution? In my case the field must be nullable=False, but even with adding default="" in both the model and migration script I still get the same error. 
Can you help please

**Comment by miguelgrinberg** [comment]
@smalekzadeh your field cannot be nullable=False if you have existing columns that are NULL. Fix those columns first, then the migration will work.

**Comment by ilumer** [comment]
I have a same problem,. I want to change the primary key column.
```
old user 
followed = db.relationship('Follow', foreign_keys=[Follow.follower_id], 
                               backref=db.backref('follower', lazy='joined'), 
                               lazy='dynamic', cascade='all, delete-orphan') 
followers = db.relationship('Follow', foreign_keys=[Follow.followed_id], 
                                backref=db.backref('followed', lazy='joined'), 
                                lazy='dynamic', cascade='all, delete-orphan')
old follow
follower_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True) 
followed_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True) 
```
```
user
following = db.relationship('Follow', foreign_keys=[Follow.follower_id],
                                backref=db.backref('followers', lazy='joined'),
                                lazy='dynamic', cascade='all, delete-orphan')
followers = db.relationship('Follow', foreign_keys=[Follow.following_id],
                                backref=db.backref('following', lazy='joined'),
                                lazy='dynamic', cascade='all, delete-orphan')
follow
follower_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True)
following_id = db.Column(db.Integer, db.ForeignKey('Users.id'), primary_key=True)
```
the sqlite3 output `(sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL [SQL: 'ALTER TABLE follows ADD COLUMN following_id INTEGER NOT NULL']`.
The `following_id` is primary_key and can not be set null.Can you give some ways that can try to solve this problems. I am sorry for my English.

**Comment by graydenshand** [comment]
Try setting the server_default parameter in your migration script/model.
default is handled by SQLAlchemy. 
server_default actually sets this in your DB

**Comment by mzord** [comment]
> @smalekzadeh your field cannot be nullable=False if you have existing columns that are NULL. Fix those columns first, then the migration will work.

I`ve just deleted my migrations folder and run the flask db init, flask db migrate, flask db upgrade again and everything went fine!

**Comment by graydenshand** [comment]
@mzord kind of defeats the purpose of using alembic/flask-migrate eh? 

> I`ve just deleted my migrations folder and run the flask db init, flask db migrate, flask db upgrade again and everything went fine!

**Comment by aramhamidi** [comment]
I had the same problem, but as Miguel suggested, I checked the migration code and I noticed although I have changed the nullable to True, but in migration script it was still False. I changed it to False manually in migration script, and it worked with the following warning:
```
UserWarning: Skipping unsupported ALTER for creation of implicit constraint
  "Skipping unsupported ALTER for "
```
And everything seems to be fine now.

**Comment by prashantjeena** [comment]
> I had the same problem, but as Miguel suggested, I checked the migration code and I noticed although I have changed the nullable to True, but in migration script it was still False. I changed it to False manually in migration script, and it worked with the following warning:
> 
> ```
> UserWarning: Skipping unsupported ALTER for creation of implicit constraint
>   "Skipping unsupported ALTER for "
> ```
> 
> And everything seems to be fine now.

how to change migration script manually?

**Comment by miguelgrinberg** [comment]
@prashantjeena migration scripts are auto-generated Python files. Once the migration is generated, you can open it in a text editor and make changes to it as you see fit.

**Comment by anakorellana** [comment]
> I had the same problem, but as Miguel suggested, I checked the migration code and I noticed although I have changed the nullable to True, but in migration script it was still False. I changed it to False manually in migration script, and it worked with the following warning:
> 
> ```
> UserWarning: Skipping unsupported ALTER for creation of implicit constraint
>   "Skipping unsupported ALTER for "
> ```
> 
> And everything seems to be fine now.

what do you mean by doing it manually in migration script?

**Comment by aramhamidi** [comment]
Please read one post above yours:

> @prashantjeena migration scripts are auto-generated Python files. Once the migration is generated, you can open it in a text editor and make changes to it as you see fit.

**Comment by anakorellana** [comment]
@aramhamidi so open the models document in a text editor?

**Comment by jativar** [comment]
> Did you check the migration code to see if it was updated to nullable=True?
> 
> On Fri, Sep 11, 2015, 11:48 AM Sebastian M Cheung [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > I did and it is still returning the same
> > Sent from my iPhone
> > > On 11 Sep 2015, at 19:38, Miguel Grinberg [notifications@github.com](mailto:notifications@github.com)
> > > wrote:
> > > If you set nullable=True then things should work, your existing rows
> > > will have NULL as value for the new column.
> > > Alternatively, you can set a default to an empty string, that should
> > > work too.
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > [#81 (comment)](https://github.com/miguelgrinberg/Flask-Migrate/issues/81#issuecomment-139625486)
> > .

after editing the migration code generated by Alembic:

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nadadores', sa.Column('credencial', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###

nullable=False is replaced by nullable=True


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nadadores', sa.Column('credencial', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###

and when executing the command "python3 main.py db upgrade" again:

$ python3 main.py db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 285c1125963c, empty message
(allaboutpython3.8) [tecna@localhost recordsv1.0.33]$ 

the upgrade is successful.

Thanks!!!
-Ramiro Jativa jativar@hotmail.com

**Comment by SahooAshis** [comment]
I'm trying to add a new Boolean column to my Sqlite database using migration. But getting [SQL: ALTER TABLE post ADD COLUMN private BOOLEAN NOT NULL] error even though I have specified default=False.

class Post(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	title = db.Column(db.String(100),nullable=False)
	date_posted = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
	content = db.Column(db.Text,nullable=False)
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)
	img = db.Column(db.String(20), nullable=True)
	private = db.Column(db.Boolean, nullable=False, default=False)   # Trying to add this new culumn

**Comment by israel-oye** [comment]
If anyone has the same issue in 2023, run `flask db migrate` again after you get the error

**Comment by Mastermori** [comment]
What you actually need to do, if you encounter this error now like I did, ist to set the server_default value in your db.Column instead of the default value. [This](https://stackoverflow.com/a/16100442) stackoverflow answer cleared this up for me.
Apparently default does not do what you would think it does. 
Hope this helps anyone finding this issue before that stackoverflow page like me :)

**Comment by bazuchan** [comment]
> @smalekzadeh your field cannot be nullable=False if you have existing columns that are NULL. Fix those columns first, then the migration will work.

Why? Having to modify migration scripts by hand is wrong and should be considered a bug

**Comment by graydenshand** [comment]
> Having to modify migration scripts by hand is wrong and should be considered a bug

Sorry @bazuchan, but that is just wrong.

> It is critical to note that autogenerate is not intended to be perfect. It is always necessary to manually review and correct the candidate migrations that autogenerate produces.

From [alembic's documentation](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#what-does-autogenerate-detect-and-what-does-it-not-detect). Hand-editing migration scripts is not just not a bug, it's a best practice.
