### ISSUE TITLE
Question: Keeping Empty Database in Version Control

### ISSUE THREAD

**Issue by nfarrar** [miguelgrinberg/Flask-Migrate#82]
Sorry - if this is a *silly* question, I'm new in general to flask, web apps, and database migrations.

I've got a flask app I'm working on that uses sqlite for the 'development' database. I'm using flask-migrate for the migrations.

The application is version controlled with git - including the database. What I'd like to do is keep the database in version control, but in a 'default' state - so that when a coworker checks it out they don't get my test data ... and vice-versa.

I'm unsure how to make this work. Any suggestions?

**Comment by nfarrar** [comment]
Think I just figured it out - should have played around just a little bit more. 

- don't commit the database into version control
- run `python manage.py db init` (creates a database and sets up migrations)
- run `python manage.py db migrate` (creates the upgrade script)
- run `python manage.py db upgrade` (upgrades the database to the latest version)
- remove the database (i.e. simulating no database in the repository)
- run `python manage.py db upgrade` (creates a new database with the latest schema)

Seems to work just fine.

**Comment by miguelgrinberg** [comment]
Here is how I do it:

- don't commit the database into version control
- commit the migrations directory and all its contents to version control, and keep it updated as migrations are added
- each developer cloning the repo just needs to run `python manage.py db upgrade` to get a fresh, empty database.

**Comment by nfarrar** [comment]
Thank you. That workflow seems to work perfectly!
