### ISSUE TITLE
Changing filename formats in migrations folder

### ISSUE THREAD

**Issue by HanSooloo** [miguelgrinberg/Flask-Migrate#86]
It would be nice if it were possible to change the way the migration script file names are generated.

How can one override the configuration for alembic in a typical `manage.py` file that calls on Flask-Migrate?

My sample `manage.py` is below:
```
#!/usr/bin/env python
import os

from app import db, models

from flask import Flask
from flask_script import Manager, Shell
from flask_migrate import Migrate, MigrateCommand

app = Flask(__name__)
app.config.from_object('config')

manager = Manager(app)
migrate = Migrate(app, db)

def make_shell_context():
    return dict(app=app, db=db, models=models)

manager.add_command('shell', Shell(make_context=make_shell_context))
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```

I am essentially trying to set this somewhere, but not sure where to do it:
```
config.set_main_option('file_template', '%%(year)s%%(month)s%%(day)s-%%(hour)s%%(minute)s-%%(second)s_%%(rev)s_%%(slug)s')
```
I don't want to edit the source code of Flask-Migrate to change the templated `env.py` file, since I will later be deploying this code to Heroku.

**Comment by miguelgrinberg** [comment]
You can edit the `env.py` that is installed in the `migrations` directory right after calling `db init`.

**Comment by HanSooloo** [comment]
Thank you for the pointer.

Somehow when I added the `config.set_main_option` line to `env.py`, it didn't work.  

But when I edited `alembic.ini` file's `file_template` field directly it worked.
