### ISSUE TITLE
multidb support

### ISSUE THREAD

**Issue by iurisilvio** [miguelgrinberg/Flask-Migrate#9]
Alembic and Flask-SQLAlchemy has support to multidb. Flask-Migrate should work with them.

**Comment by nchauhan5** [comment]
@miguelgrinberg - I have been trying to update the configurations in the env.py file to handle multiple PostgreSQL database migrations represented by 'SQLALCHEMY_BINDS'.  Can you explain in a simple way as to how can we do that with a  code snippet.

**Comment by miguelgrinberg** [comment]
@nchauhan5 I have the env.py and alembic.ini templates for multi-db here: https://github.com/miguelgrinberg/Flask-Migrate/tree/master/flask_migrate/templates/flask-multidb.

**Comment by nchauhan5** [comment]
@miguelgrinberg - I tried using it by 1. Deleting existing migrations folder, 2. removing the alembic version table and then again running the commands :
1. python manage.py db init --multidb
2. python manage.py db migrate
3. python manage.py db upgrade

I have this in my app.py file

POSTGRES_URL = os.environ.get('POSTGRES_URL', '127.0.0.1:5432')
POSTGRES_USER = os.environ.get('POSTGRES_USER', 'postgres')
POSTGRES_PW = os.environ.get('POSTGRES_PW', 'admin')
USERS_POSTGRES_DB = os.environ.get('POSTGRES_USERS_DB', 'vendor_portal_users')
PRODUCTS_POSTGRES_DB = os.environ.get('POSTGRES_PRODUCTS_DB', 'vendor_portal_products')

# Aggregated User Database URL
USER_DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}/{db}'.\
    format(user=POSTGRES_USER, pw=POSTGRES_PW, url=POSTGRES_URL, db=USERS_POSTGRES_DB)

# Aggregated Product Database URL
PRODUCT_DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}/{db}'. \
    format(user=POSTGRES_USER, pw=POSTGRES_PW, url=POSTGRES_URL, db=PRODUCTS_POSTGRES_DB)

# to be able to connect to multiple databases at once
SQLALCHEMY_BINDS = {
    'products_database': PRODUCT_DB_URL
}

# Initialize app
app = Flask(__name__)

# Integrate postgresql, sqlalchemy with flask
app.config['SQLALCHEMY_BINDS'] = SQLALCHEMY_BINDS
app.config['SQLALCHEMY_DATABASE_URI'] = USER_DB_URL
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False  # silence the deprecation warning
db = SQLAlchemy(app)

import models.user_models

But it still doesn't work, it just creates alembic version table in both these databases - products_database (PRODUCT_DB_URL), USER_DB_URL (users_database )

**Comment by miguelgrinberg** [comment]
> it just creates alembic version table in both these databases

That's expected. How does the first migration look?

**Comment by nchauhan5** [comment]
@miguelgrinberg  - If I have just one database configured in flask the three steps init, migrate, upgrade, even created tables in the database from the models that i define along with the alembic version table along with a random named migration.py file and version number row inside the alembic version table. But if I have two databases configured the three steps again - just init, migrate, upgrade does not create tables in my PostgreSQL database from the user models that are defined still the same and no random named migration python file gets created.

You are saying thats expected ? What do I need to do to see these three steps - init, migrate, upgrade create tables in two of those databases based on their bind key. Right now it just creates alembic version tables in the two databases, which are empty, no version number inside

**Comment by nchauhan5** [comment]
@miguelgrinberg - Any thoughts ?

**Comment by miguelgrinberg** [comment]
@nchauhan5 Sorry, I don't really follow what you are describing. You need to show me the exact commands that you are running with their output, and the contents of the migration files generated.

If you want to test a project that is proven to work, the `app_multidb.py` application in https://github.com/miguelgrinberg/Flask-Migrate/tree/master/tests is part of the unit tests and creates models in two databases.
